### DISCUSSION TITLE
Suggested cache key for OS release version?

### DISCUSSION THREAD

**Discussion by eirrgang** [actions/cache#1025] [Q&A]
I saw that the release associated with the `ubuntu-latest` image will be changing (https://github.com/actions/runner-images/issues/6399) but I can't find a [context](https://docs.github.com/en/actions/learn-github-actions/contexts), [expression](https://docs.github.com/en/actions/learn-github-actions/expressions), or (default) [environment variable](https://docs.github.com/en/actions/learn-github-actions/environment-variables) that I could include in my cache key to distinguish the environment after the update.

Suggestions?

**Comment by natsuk4ze** [comment]
Hi @eirrgang. To include the specific version of the Ubuntu release in the cache key, you can use a shell command to obtain the release version, and then utilize that information in the cache action.

Here's an example of how you might achieve this:
```yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Ubuntu version
        id: ubuntu-version
        run: echo "UBUNTU_VERSION=$(lsb_release -rs)" >> $GITHUB_ENV
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache
          key: ubuntu-${{ env.UBUNTU_VERSION }}-${{ hashFiles('**/lockfiles') }}
```
