### DISCUSSION TITLE
Java Maven cache not works for me

### DISCUSSION THREAD

**Discussion by sotobotero** [actions/cache#1138] [Q&A]
Hi Guys, could any body help me please, I have tried it with n variations but it not works.

This is my code on workflow 
```yaml
######################################################## 
# 3-  Cache local Maven repository
########################################################               

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: $HOME/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

######################################################## 
# 4-  create custom maven stting.xml
########################################################          
        
      - name: create custom maven stting.xml 
        uses: s4u/maven-settings-action@v2.8.0
        with:
          mirrors: '[{"id": "maven-default-http-blocker", "name": "Pseudo repository to mirror external repositories initially using HTTP.", "mirrorOf": "external:dont-match-anything-mate:*", "url": "http://0.0.0.0","blocked":"false"}]'

######################################################## 
# 5- Build with Maven
########################################################

      - name: Build with Maven
        env:
          MAVEN_OPTS: '-Dmaven.repo.local=$HOME/.m2/repository'
      #The "SNAPSHOT" term means that the build is a snapshot of your code at a given time    
      #The --batch-mode flag indicates that the build should be run without any user interaction
      #(Avoid caching versions of your own code)The --update-snapshots flag tells Maven to check for any updated snapshots of dependencies and use those instead of the versions specified in the project's pom.xml file. 
      #The package argument tells Maven to package the project into a distributable format, such as a JAR or WAR file.
        run: mvn --batch-mode --update-snapshots package


######################################################## 
# 6- Merge to development branch
######################################################## 
      - name: Merge to development branch
        if: ${{ success() }}  
        run: |
          git config --global user.email "sotobotero@digitalthinking.biz"
          git config --global user.name "IDE" 
          git merge --no-ff ${{ github.event.pull_request.head.ref }} -m "Merge pull request #${{ github.event.number }}"
```
Cache is created with each executions, but is no restored or used

![image](https://user-images.githubusercontent.com/1613851/226189311-6a06f6e0-3c14-4311-bbc4-c58a22afe40c.png)

I and getting this message 

![image](https://user-images.githubusercontent.com/1613851/226189410-fd49b115-a65f-4955-9ec4-361e2bef837a.png)

I have also tried the example in the readme, but it doesn't work either.

```yaml
- name: Cache local Maven repository
  uses: actions/cache@v3
  with:
    path: ~/.m2/repository
    key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
    restore-keys: |
      ${{ runner.os }}-maven-
```

Thanks in advance.
