### DISCUSSION TITLE
Cache missed when shared between jobs

### DISCUSSION THREAD

**Discussion by avallete** [actions/cache#1144] [Q&A]
Hey there.

I have a workflow defined like so:

```yml
name: E2E CLI

on:
  pull_request:
    types: [ready_for_review, opened, synchronize]
    branches:
      - main

concurrency:
  group: e2e-cli-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      # Get yarn cache directory path in order to cache it
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: |
          echo "::set-output name=dir::$(yarn config get cacheFolder)"
          echo "::set-output name=version::$(yarn -v)"
        shell: bash
      # Cache the dependencies between jobs
      - uses: actions/cache@v3.3.1
        id: yarn-cache
        with:
          path: |
            **/node_modules/*
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-deps-${{ hashFiles('yarn.lock') }}-${{ hashFiles('./prisma/schema.prisma') }}
      # Install the dependencies if they aren't cached
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn install --immutable
        shell: bash

      # Cache the build between jobs
      - uses: actions/cache@v3.3.1
        id: build-cli-cache
        with:
          path: |
            ./cli/dist
            ./cli/bin
            ./packages/cli/dist
          key: ${{ runner.os }}-cli-build-${{ hashFiles('./cli/src/**', './packages/sdk/src/**', './packages/cli/**') }}-${{ hashFiles('yarn.lock') }}
      - name: Build cli
        if: steps.build-cli-cache.outputs.cache-hit != 'true'
        working-directory: ./cli
        run: |
          yarn build
          yarn build:package

  tests-performances:
    needs: build
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - uses: actions/cache@v3.3.1
        id: yarn-cache
        with:
          path: |
            **/node_modules/*
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-deps-${{ hashFiles('yarn.lock') }}-${{ hashFiles('./prisma/schema.prisma') }}
          fail-on-cache-miss: true
      - uses: actions/cache@v3.3.1
        id: build-cli-cache
        with:
          path: |
            ./cli/dist
            ./cli/bin
            ./packages/cli/dist
          key: ${{ runner.os }}-cli-build-${{ hashFiles('./cli/src/**', './packages/sdk/src/**', './packages/cli/**') }}-${{ hashFiles('yarn.lock') }}
          fail-on-cache-miss: true
         ...
      ...

  tests-e2e:
    needs: build
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - uses: actions/cache@v3.3.1
        id: yarn-cache
        with:
          path: |
            **/node_modules/*
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-deps-${{ hashFiles('yarn.lock') }}-${{ hashFiles('./prisma/schema.prisma') }}
          fail-on-cache-miss: true
      - uses: actions/cache@v3.3.1
        id: build-cli-cache
        with:
          path: |
            ./cli/dist
            ./cli/bin
            ./packages/cli/dist
          key: ${{ runner.os }}-cli-build-${{ hashFiles('./cli/src/**', './packages/sdk/src/**', './packages/cli/**') }}-${{ hashFiles('yarn.lock') }}
          fail-on-cache-miss: true
         ...
```

And in the first "build" step, in between my run I can see that the cache exist and is used:
<img width="1683" alt="Screenshot 2023-03-30 at 14 58 00" src="https://user-images.githubusercontent.com/8771783/228860076-9879dbff-77d0-461e-a1cb-f619687ba5ca.png">

So here we can see the key `Linux-yarn-deps-36fdbe6f8090aece958f295c8ac3883736dd57ea22192a2250c46227dd993bd0-1a11cd124cc1124187ccef56609eea06762fed32c56c2fd43093e51ab857b52b` properly restore as expected.

The issue is when I try to restore the exact same cache in "test-e2e" or "test-performances" I have the following:
<img width="1684" alt="Screenshot 2023-03-30 at 15 00 35" src="https://user-images.githubusercontent.com/8771783/228860741-57070435-b3fd-4379-9b92-f422ac11749f.png">

Here I searched for the key inside action "basic" to make sure they're the same. So I don't understand why it fail.

The strange thing is that if I duplicate the "build" phase into the two tests jobs. Then, the cache is properly hit.

Am I missing something or is that a bug ?
I have found this who seems related, but also resolved: https://github.com/actions/cache/issues/1114

I've also tried to enable "enableCrossOsArchive" just for the sake of it, but it doesn't fix the issue.
