### DISCUSSION TITLE
How to handle error in multiple commands inside cache step?

### DISCUSSION THREAD

**Discussion by yh-sb** [actions/cache#1240] [Q&A]
Let's say I have the following entry in GitHub Actions:

```yaml
      - name: Cache some heavy library
        uses: actions/cache@v3
        id: cache
        with:
          key: ${{ runner.OS }}-cache-${{ hashFiles('.github/workflows/build.yml') }}
          path: C:/mylib

      - name: Build some heavy library (if cache not found)
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl.exe -L https://some-link.com/to-the-library-src -o src-lib.zip
          tar -xf src-lib.zip -C C:\mylib
          command-1
          command-2
          command-3

```

I found that `if: steps.cache.outputs.cache-hit != 'true'` line makes the step run even if some of its command fails. This leads to massive time wasted on running the next commands even if some of them already failed. `continue-on-error: false` doesn't help in this case.

How do you handle it in an elegant way?
