### DISCUSSION TITLE
Restoring cache seems to be restoring more than expected

### DISCUSSION THREAD

**Discussion by spongeBri** [actions/cache#1293] [General]
I am seeing some strange behavior when saving and restoring cache.

I have a scenario when i only need to restore 5-6 files during the build, so this is the path i am passing into the cache step and this seems to work. The cache is created and is very small.

When i run the workflow again and the cache is hit, i notice that new changes i have made to the code are missing and i think the cache is not only restoring the file path but the entire project. 

Is there anyway i can stop this from happening because i need the workflow to get the latest changes from the project but these 5-6 cached files need to be inserted. 

Below is the restore step
``` yaml
      - name: Cache test output
        id: cache
        uses: actions/cache/restore@v3
        env:
          cache-name: cache-test-output
        with:
          path: ${{ github.workspace }}/e2e/e2e_tests/fixture_pickles/*
          key: splat-test-data
```

Here is the save cache step
``` yaml
      - name: Cache test output
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        env:
          cache-name: cache-test-output
        with:
          path: ${{ github.workspace }}/e2e/e2e_tests/fixture_pickles/*
          key: splat-test-data
```

Any help is highly appreciated
