### DISCUSSION TITLE
How do you cache based on multiple paths at once?

### DISCUSSION THREAD

**Discussion by hirehamir** [actions/cache#1368] [Q&A]
For example, if I want to cache package downloads based on whether or not any `lock` files change, but I separately want to cache compiled output based on whether or not any `*.bar` files in `src/` change, how would I go about doing so?

**Comment by ShreeChaturvedi** [comment]
Use two `actions/cache` steps, each with its own key.

```yaml
- name: Cache package downloads
  uses: actions/cache@v4
  with:
    path: path/to/package-cache
    key: ${{ runner.os }}-pkgs-${{ hashFiles('**/package-lock.json', '**/yarn.lock', '**/pnpm-lock.yaml') }}
    restore-keys: |
      ${{ runner.os }}-pkgs-

- name: Cache compiled output
  uses: actions/cache@v4
  with:
    path: path/to/build-output
    key: ${{ runner.os }}-build-${{ hashFiles('src/**/*.bar') }}
    restore-keys: |
      ${{ runner.os }}-build-
```

Point each `path` at the real folder on the runner. A key only changes when its `hashFiles` inputs change.

Pitfall: one step with both dirs and one key means a lockfile change also busts the compile cache.
