### DISCUSSION TITLE
How to override/delete cache?

### DISCUSSION THREAD

**Discussion by ghost** [actions/cache#488] [General]
I have a workflow and need to override the cache. What should I do?
(or is there any way to delete the cache)

**Comment by dhadka** [comment]
There is currently no way to overwrite or delete an existing cache.  What you'll need to do is use a new/different key when you want to create a new cache.  

If, for example, you want to create a new cache every run and restore from the previous run, you can add the Run Id to the key:

```
- uses: actions/cache@v2
  with:
    path: foo/
    key: ${{ runner.os }}-cache-${{ github.run_id }}
    restore-keys: |
      ${{ runner.os }}-cache-
```
