### DISCUSSION TITLE
Download cache

### DISCUSSION THREAD

**Discussion by Derad6709** [actions/cache#513] [General]
Hello. How can I get link to the cache archive/download it after completing the action?

**Comment by dhadka** [comment]
@Derad6709 Are you just trying to verify what's in the cache?  The simplest way would be to use the `upload-artifact` action to store the contents of the cache path immediately after the cache is restored.

```
- uses: actions/cache@v2
  with:
    key: ...
    path: ~/path/
- uses: actions/upload-artifact@v2
  with:
    name: cache_contents
    path: ~/path/
```

There's currently no way to access the cache contents outside of running this action.
