### DISCUSSION TITLE
What does `restore-keys` do?

### DISCUSSION THREAD

**Discussion by nchammas** [actions/cache#578] [Q&A] [answered]
The README says:

> `restore-keys` - An ordered list of keys to use for restoring the cache if no cache hit occurred for key

I don't understand what this means. If there is no hit on `key`, then that means any previous caches are likely not useful (e.g. because our dependencies have changed). So what cache is there to restore when `key` has changed?

Looking at the [pip example](https://github.com/actions/cache/blob/main/examples.md#python---pip), for example, I don't follow what this part is doing for us:

```yaml
    restore-keys: |
      ${{ runner.os }}-pip-
```

What do we lose if we remove that part from the Action inputs? Can someone illustrate with an example scenario?

**Comment by domjtalbot** [comment, marked as answer]
Hey @nchammas!

The `restore-keys` option works as a backup for when the specific cache key you want doesn't return any results.

For instance a minimal setup could look like this:

```yml
- uses: actions/cache@v2
   with:
     path: ~/.cache/pip
     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
```

In this example, we're requesting that `~/.cache/pip` is cached using the key provided which could look like `Linux-pip-8156c`. However, the cache will only be restored if the key is a perfect match. This might be exactly what you want it to do, but you might also want it to restore another cache as a backup, which is where `restore-keys` comes into play!

```yml
- uses: actions/cache@v2
   with:
     path: ~/.cache/pip
     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
     restore-keys: |
       ${{ runner.os }}-pip-
```

With the addition of `restore-keys`, now if no cache matches our key perfectly, we have defined what cache to use as a backup. For example, if no cache exists for our key `Linux-pip-8156c`, then we'll try to restore another cache using the key `Linux-pip-` as backup (if any exists).

I hope that helps!
