### DISCUSSION TITLE
Allow updating/overwriting the matching cache

### DISCUSSION THREAD

**Discussion by jjlin** [actions/cache#641] [Ideas]
If I cache something that can be incrementally updated, it would be nice to be able to just overwrite the existing cache with the updated copy. For example, if my build involves cloning a large-ish external Git repo, I would like to do something like

```yaml
- name: Restore repo from cache
  uses: actions/cache@v2
  with:
    path: ext-git-repo
    key: ext-git-repo
    overwrite-cache: true
- name: Update repo
  working-directory: ext-git-repo
  run: git fetch ...
```

This looks much cleaner (and is more space-efficient for GitHub) than the current alternative that generates many redundant copies of the cache: 

```yaml
- name: Restore repo from cache
  uses: actions/cache@v2
  with:
    path: ext-git-repo
    key: ext-git-repo-${{ github.run_number }}
    restore-keys: |
      ext-git-repo-
```
