### DISCUSSION TITLE
Where does restored cache place?

### DISCUSSION THREAD

**Discussion by sogaoh** [actions/cache#686] [Q&A]
My Actions setting is like below: 

```
      - name: Cache vendor Directory
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: ${GITHUB_WORKSPACE}/lara-sample/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Composer Install
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: |
          cd ${GITHUB_WORKSPACE}
          make vendor    # docker-compose -f ./create-project.yml run composer install
```

I think `vendor` directory is restored `${GITHUB_WORKSPACE}/lara-sample/` , but not. 
Where is `vendor` directory restored ? 

( I've checked [restore.ts of actions/cache](https://github.com/actions/cache/blob/main/src/restore.ts) and [cache.ts of actions/toolkit (actions/core)](https://github.com/actions/toolkit/blob/main/packages/cache/src/cache.ts) , but I couldn't understand..) 

refs: https://github.com/sogaoh/laravel-cloud-run
