### DISCUSSION TITLE
Force exit if key is not found

### DISCUSSION THREAD

**Discussion by ddoice** [actions/cache#700] [Ideas]
In many cases, the cache is used to pass data across jobs and that data is mandatory to perform other tasks.

Currently, I have used additional steps to check if the cache has been restored and exit if has failed, but it is cumbersome to add this step on every job that is using the cache:
```yaml
...
- name: Check cache hit
  if: steps.cache.outputs.cache-hit != 'true'
  run: |
   echo ⚠️ cache not restored
   exit 2
...
```
Would be great if this feature is builtin something like:

```yaml
...
- name: Cache multiple paths
  uses: actions/cache@v2
  with:
    path: ~/cache
    key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    throwIfMiss: true
...
```

I'm willing to contribute with code if makes sense for the community.
