### DISCUSSION TITLE
Check for Cache Existence Without Downloading

### DISCUSSION THREAD

**Discussion by boennemann** [actions/cache#704] [Ideas]
I'm using a "dependencies" job at the beginning of my pipeline.

```
jobs:
  dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-deps-${{ hashFiles('**/yarn.lock') }}

      - name: Create node_modules
        if: steps.cache.outputs.cache-hit != 'true'
        env:
          GPR_TOKEN: ${{ secrets.GPR_TOKEN }}

        run: |
          echo "//npm.pkg.github.com/:_authToken=$GPR_TOKEN" >> .npmrc
          # Install Dependencies
          yarn install --frozen-lockfile --check-files
```

I then run a matrix that parallelises the following work. The matrix restores the cache with the same key and then always hits.

What I'm missing is a way to not download the cache at all in the dependencies job if the key is present in the cache.

Am I missing an existing way to do this, or could this be added?
