### DISCUSSION TITLE
Cache created in `ubuntu-latest` cannot be restored in Docker container

### DISCUSSION THREAD

**Discussion by ugultopu** [actions/cache#709] [Q&A]
Here's my workflow file:

```yml
name: Build Pipeline
on: push
env:
  NODE_VERSION: 11

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: node_modules
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/build
          key: build-${{ github.sha }}
          restore-keys: build
      - if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install
      - run: npm run build -- --incremental
  npm-scripts:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: ['lint:pipeline', 'lint:exports', 'i18n:pipeline', 'schema:validate']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}
      - if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          echo 'Expected to have a cache hit for "node_modules", since this job runs after the "build" job, which caches the latest version of "node_modules". Not having a cache hit means probably there is a bug with the workflow file.'
          exit 1
      - id: cache-build-output
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/build
          key: build-${{ github.sha }}
      - if: steps.cache-build-output.outputs.cache-hit != 'true'
        run: |
          echo 'Expected to have a cache hit for the build output folder, since this job runs after the "build" job, which caches the latest version of the "build" folder. Not having a cache hit means probably there is a bug with the workflow file.'
          exit 1
      - run: npm run ${{ matrix.script }}
  jest-tests:
    needs: [build]
    runs-on: ubuntu-latest
    container: node:11
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
      redis:
        image: redis
    steps:
      - uses: actions/checkout@v2
      - id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}
      - if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          echo 'Expected to have a cache hit for "node_modules", since this job runs after the "build" job, which caches the latest version of "node_modules". Not having a cache hit means probably there is a bug with the workflow file.'
          exit 1
      - id: cache-build-output
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/build
          key: build-${{ github.sha }}
      - if: steps.cache-build-output.outputs.cache-hit != 'true'
        run: |
          echo 'Expected to have a cache hit for the build output folder, since this job runs after the "build" job, which caches the latest version of the "build" folder. Not having a cache hit means probably there is a bug with the workflow file.'
          exit 1
      - run: echo
```

`node_modules` and `build` folders are cached in the `build` job. These caches are able to be restored without a problem in the `npm-scripts` job. However, they are not able to be restored in the `jest-tests` job, where it gets a `Cache not found for input keys` error.

I don't know how this is possible, since the exact same cache keys are able to be restored without a problem in all of the `npm-scripts` jobs.

When I remove the:

```yml
container: node:11
services:
  postgres:
    image: postgres
    env:
      POSTGRES_DB: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  redis:
    image: redis
```

part (and hence let the job run on `ubuntu-latest`, instead of a Docker container), the cache is able to be restored again properly. So not sure what's going on here.
