### DISCUSSION TITLE
How to let pip use compiled wheel rather than build from source again and again?

### DISCUSSION THREAD

**Discussion by jianglongye** [actions/cache#864] [Q&A]
My `python` project relies on [pytorch3d](https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md) and I want to cache the compiled wheel for github action.

In my `requirements.txt`, it is

```
git+https://github.com/facebookresearch/pytorch3d.git@2bd65027ca5c3b87b77d4f05b8eacae58d8d106f
```

since pip [doc](https://pip.pypa.io/en/stable/topics/caching/) says

> Changed in version 20.0: pip now caches wheels when building from an immutable Git reference (i.e. a commit hash).

The workflow (cache and pip parts) is

```
      - name: Cache Pip
        uses: actions/cache@v3
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ matrix.torch }}-${{ hashFiles('requirements/build.txt') }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip twine wheel
          pip install torch==${{matrix.torch}}+cpu torchvision==${{matrix.torchvision}}+cpu -f https://download.pytorch.org/whl/torch_stable.html
          pip install -r requirements.txt
```

The workflow log (`pytorch3d` part) is

```
Building wheels for collected packages: pytorch3d
  Building wheel for pytorch3d (setup.py): started
  Building wheel for pytorch3d (setup.py): still running...
  Building wheel for pytorch3d (setup.py): still running...
  Building wheel for pytorch3d (setup.py): still running...
  Building wheel for pytorch3d (setup.py): still running...
  Building wheel for pytorch3d (setup.py): still running...
  Building wheel for pytorch3d (setup.py): still running...
  Building wheel for pytorch3d (setup.py): still running...
  Building wheel for pytorch3d (setup.py): still running...
  Building wheel for pytorch3d (setup.py): still running...
  Building wheel for pytorch3d (setup.py): finished with status 'done'
  Created wheel for pytorch3d: filename=pytorch3d-0.6.2-cp39-cp39-linux_x86_64.whl size=28018470 sha256=7f55f81243440691842486cf990fd17078cb0eb1f4a912f479741d3021e7c1be
  Stored in directory: /home/runner/.cache/pip/wheels/43/06/af/ed96fbe2b0b9dba5c71cb9f0e63a74bc42edbaebf0cc823c83
Successfully built pytorch3d
```

It looks like compiled wheel is stored in `/home/runner/.cache/pip/wheels/`, but I do not know why pip still compiles the wheel at next time.

Note that all other dependencies are cached successfully, here is some log:

```
Collecting pandocfilters>=1.4.1
  Using cached pandocfilters-1.5.0-py2.py3-none-any.whl (8.7 kB)
Collecting jupyterlab-pygments
  Using cached jupyterlab_pygments-0.2.2-py2.py3-none-any.whl (21 kB)
Collecting tinycss2
  Using cached tinycss2-1.1.1-py3-none-any.whl (21 kB)
Collecting mistune<2,>=0.8.1
  Using cached mistune-0.8.4-py2.py3-none-any.whl (16 kB)
Collecting fastjsonschema
  Using cached fastjsonschema-2.16.1-py3-none-any.whl (22 kB)
Collecting ptyprocess>=0.5
  Using cached ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Collecting wcwidth
```

By the way, I have tried `--prefer-binary` option for `pip` , this does not work either.

Thanks in advance for help in any form!
