### DISCUSSION TITLE
Cache actions fails.

### DISCUSSION THREAD

**Discussion by terabytesoftw** [actions/cache#940] [General]
```yaml
      - name: Determine composer cache directory.
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Cache dependencies installed with composer.
        uses: actions/cache@v3.0.9
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php${{ matrix.php }}-composer
```

![image](https://user-images.githubusercontent.com/42547589/193240268-237535b2-5e20-459c-a755-92693081f91a.png)

![image](https://user-images.githubusercontent.com/42547589/193240333-b6820001-c025-49ad-a927-706f1b6b942c.png)

Any idea why it fails?

Thks.
