### ISSUE TITLE
How to use env vars in path on windows

### ISSUE THREAD

**Issue by thisismydesign** [actions/cache#101]
Hey,

I'd need some help understanding what I'm doing wrong.

Expectation: `path: ${{ env.LOCALAPPDATA }}` points to `C:\Users\runneradmin\AppData\Local`.

```
    runs-on: windows-latest
    - name: Test print stuff
      run: |
        echo $env:LOCALAPPDATA
        ls $env:LOCALAPPDATA
```

```
 Test print stuff7s

Run echo $env:LOCALAPPDATA
C:\Users\runneradmin\AppData\Local


    Directory: C:\Users\runneradmin\AppData\Local

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        11/11/2019  2:16 PM                Google
d-----        11/17/2019 11:28 PM                Microsoft
d-----        11/17/2019  9:44 PM                Packages
d-----        11/17/2019 11:29 PM                Temp
```

```
    - name: Cache electron-builder dependencies
      uses: actions/cache@v1
      with:
        path: ${{ env.LOCALAPPDATA }}electron-builder
```

```
Post Cache electron-builder dependencies3s
##[warning]The process 'C:\Program Files\Git\usr\bin\tar.exe' failed with exit code 2
Post job cleanup.
"C:\Program Files\Git\usr\bin\tar.exe" -cz --force-local -f d:/a/_temp/0b413849-9e8e-4665-894e-02bf8c693b6e/cache.tgz -C d:/a/my-project/my-project/electron-builder .
/usr/bin/tar: d\:/a/my-project/my-project/electron-builder: Cannot open: No such file or directory
/usr/bin/tar: Error is not recoverable: exiting now
##[warning]The process 'C:\Program Files\Git\usr\bin\tar.exe' failed with exit code 2
```

Meanwhile, `path: C:\Users\runneradmin\AppData\Local\electron-builder` works as expected.

**Comment by joshmgross** [comment]
The `env` context is limited to environment variables set for jobs, steps, and workflows. See [context docs](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions#contexts)

You have a few options:
1. Set the value for the `env` context
```yaml
   - name: Set env 
      run: echo "::set-env name=appdata::$($env:LOCALAPPDATA)"
    - name: Cache electron-builder dependencies
      uses: actions/cache@v1
      with:
        path: ${{ env.appdata }}\electron-builder
```

2. Set the value as an output
```yaml
    - name: Env output
      id: output-env
      run: echo "::set-output name=appdata::$env:LOCALAPPDATA"

    - name: Cache electron-builder dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.output-env.outputs.appdata }}\electron-builder
```

3. Use `~` to represent the user directory and append Appdata
```yaml
    - name: Cache electron-builder dependencies
      uses: actions/cache@v1
      with:
        path: ~\AppData\Local\electron-builder
```
The action will recognize `~` and replace it with the user directory, see https://github.com/actions/cache/blob/master/src/utils/actionUtils.ts#L80
