### ISSUE TITLE
Feature branch cannot restore cache made in main branch

### ISSUE THREAD

**Issue by axionos** [actions/cache#1011]
Goal
create snapshots cache in main branch -> restore cache in feature branch to compare snapshots

Issue
Cache hit doesn't happen in the feature branch when trying to restore the main branch's cache.
Instead, it creates a new cache with the exactly same cache key(version).

Would this be a bug? 
The feature branch is based off of main branch so the scope shouldn't be an issue here I believe. 
(`git checkout -b cache-test` on main)
The What am I missing here and how can i make this work?

![Screen Shot 2022-12-01 at 12 36 11 PM](https://user-images.githubusercontent.com/47922404/205121820-52e4fbdd-7ed7-47cb-95a1-9969f3c698a7.png)
![Screen Shot 2022-12-01 at 12 16 41 PM](https://user-images.githubusercontent.com/47922404/205120082-0e0e8846-a8cc-4158-9fc5-6ff04a59b47c.png)

Also noticing searching cache for branch "main" is not returning anything, which seems odd.

![Screen Shot 2022-12-01 at 1 17 21 PM](https://user-images.githubusercontent.com/47922404/205129935-4564b27e-2b27-4635-aded-b642cc207843.png)

```
# merge.yml - create cache on merge
- name: Store Snapshots Cache
      id: snapshots-cache
      uses: actions/cache@v3
      with:
          path: packages/**/src/**/*.*.tsx-snapshots
          key: ${{ runner.os }}-snapshots-${{ hashFiles('yarn.lock') }}

# pr-push.yml - restore cache on push
- name: Restore Snapshots Cache
      id: snapshots-cache
      uses: actions/cache@v3
      with:
          path: packages/**/src/**/*.*.tsx-snapshots
          key: ${{ runner.os }}-snapshots-${{ hashFiles('yarn.lock') }}
          restore-keys: |
             ${{ runner.os }}-snapshots-
```

**Comment by Phantsure** [comment]
Cache should have been restored from `main` and created a new cache in feature branch from those files. Can you check the logs if that is the case. Can you also check if the path in both cache steps in `main` and `feature-branch` same, that is given in debug log

**Comment by axionos** [comment]
I resolved this issue with creating the cache on `push` action on the main branch. It was previously triggered on `pr close` action. It would be great and save much time of other developers who wanna use actions/cache if it's mentioned in the documentation that only the cache that's generated by `push` can be accessible to its feature branches as nowhere in the documentation mentions this.

**Comment by kotewar** [comment]
@axionos, can you please share the trigger condition present in your workflow file? Example-

```
name: Close Pull Request

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]
```

**Comment by axionos** [comment]
@kotewar this will trigger the workflow on pull request push.

Before:
```
name: Pull Request Close
on:
  pull_request:
    branches:
      - main
    types: [closed]
```

After:
```
name: Snapshot Update
on:
  push:
    branches:
      - main
```

**Comment by anuragc617** [comment]
Hi @axionos , when the `pull_request` trigger is used and if there is no cache to be restored i.e there is no matching cache in parent branch or default branch, the cache is created against the `refs/pull/<PR_number>/merge`( which is a merge branch created by GitHub by merging the PR target branch and the PR branch, check [this](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request) ). The caches created against ``refs/pull/<PR_number>/merge` can only be used by this PR branch since this is a temp branch created for merging the PR.

In your case, for trigger type: 
```
on:
  pull_request:
    branches:
      - main
    types: [closed]
```
Since there is no cache with key: `Linux-snapshots-350c...` in `main` ref, the cache is created against `refs/pull/<PR_number>/merge'. If there would have been cache for `main` ref, then that cache would have been restored.
