### ISSUE TITLE
Where is `hashFiles` documented/defined?

### ISSUE THREAD

**Issue by jsumners** [actions/cache#102]
When I search this repository for "hashFiles" I only get results matching markdown and yaml files. I don't see any code that defines this function. I also don't see any mention of it in 
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners 

I am trying to figure out how this function actually works.

Reason:

I would like to define a cache per branch by using the `GITHUB_REF` environment variable (https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-environment-variables). But since that variable can contain path separators, I am thinking it would be a good idea to hash that _string_ and use the hash value, e.g.:

```yaml
- uses: actions/cache@v1
  with:
    path: ~/.npm
    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-${{ getStrHash(${{GITHUB_REF}}) }}
```
