### ISSUE TITLE
github action cache for Xcode SPM not working on v3(only v2)

### ISSUE THREAD

**Issue by yudonlee** [actions/cache#1054]
In order to cache the swift package manager, the path was designated as an official document and a yml was created. However, the cache was not saved due to path invalidation. So I changed the cache version to 2 instead of 3, and it was solved. No matter how hard I try to find the cause of the problem, I can't find it.

This is Documentation for Github Action
```yml'
  uses: actions/cache@v3
  with:
    path: .build
    key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
    restore-keys: |
      ${{ runner.os }}-spm-
```
### Cache Version 3(Not working for Caching)
https://github.com/yudonlee/RxNetflix-MVVM/actions/runs/3834553591/workflow

### Cache Version 2(Working)

https://github.com/yudonlee/RxNetflix-MVVM/actions/runs/3834738256/workflow
