### ISSUE TITLE
Add option to restore cache only

### ISSUE THREAD

**Issue by ForsakenHarmony** [actions/cache#1070]
**Description:**
It would be nice to have the option to restore only without using the `actions/cache/restore` action.

**Justification:**
In bigger repos, it's easy to hit the 10gb cache limit. Not caching in PRs can help with this.

The only way to accomplish this with this action is to add a separate step for PRs and make both steps conditional, which is easy to mess up.

**Are you willing to submit a PR?**

**References**
https://github.com/actions/toolkit/issues/1308
https://github.com/Swatinem/rust-cache/issues/95 (has a `save-if` option https://github.com/Swatinem/rust-cache#example-usage)

**Comment by vsvipul** [comment]
@ForsakenHarmony How will providing that help ? `actions/cache/restore` will work same as restore-only action will. If you don't want PRs to create cache you'll have to write that logic yourself in the workflow files. Do you want to automate that in the action?

**Comment by ForsakenHarmony** [comment]
@vsvipul yes, if I want to run the same workflow on main and on PRs but only save cache on main right now I have to add 2 steps

```yml
- name: Cache on main
  uses: actions/cache@v3
  if: ${{ github.ref == 'refs/heads/main' }}
  with: {...}

- name: restore on PRs
  uses: actions/cache/restore@v3
  if: ${{ github.ref != 'refs/heads/main' }}
  with: {...}
```

If there was an option, I could have a single step
```yml
- name: Cache
  uses: actions/cache@v3
  with:
    save: ${{ github.ref == 'refs/heads/main' }}
    {...}
```
