### ISSUE TITLE
feature branches PR unable to access main/default branch cache ?

### ISSUE THREAD

**Issue by gurudatta-carbon** [actions/cache#1080]
Hello we have been using setup-java action for gradle to github cache.
```
    - name: Set up JDK ${{ inputs.JAVA_VERSION }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.JAVA_VERSION }}
        distribution: 'corretto'
        cache: 'gradle'
```
As shared in below image, 
- main branch cache is around 580MB which contains gradle dependencies.
- Where as for pull requests created on top of main branch, hits a different cache key (for second run), which is around 510 MB. It's not sharing cache from main branch.
- So for Pull requests, there is a cache miss in 1st run, downloads dependencies, caches it.
- Shouldn't it share main branch cache ? is this a bug ?
![image](https://user-images.githubusercontent.com/81990237/213282443-113f70a9-b890-4a77-a15b-2a75e32065a4.png)
