### ISSUE TITLE
Post action prevents cache from saving, build still passes

### ISSUE THREAD

**Issue by evancloutier** [actions/cache#111]
Trying to move over my Rails app from CircleCI, and the last step I'm stuck with is caching my dependencies.

It looks like my workflow cannot find `vendor/bundle` causing a warning (but the build itself still passes) and a program exit.

```bash
Post job cleanup.
/bin/tar -cz -f /home/runner/work/_temp/e63e7a43-36d8-40ef-8981-8fcdfedfce0f/cache.tgz -C /home/runner/work/ivy-service/ivy-service/vendor/bundle .
/bin/tar: /home/runner/work/ivy-service/ivy-service/vendor/bundle: Cannot open: No such file or directory
/bin/tar: Error is not recoverable: exiting now
##[warning]The process '/bin/tar' failed with exit code 2
```

If this is failing to save the cache -- shouldn't this build be failing and not passing with a warning? There will always be a cache miss, causing my workflow to re-install gems, and eventual failure.

I'm not sure if I'm looking for bundle in the wrong spot, as I'm using the example from the documentation:

```
- uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
```
