### ISSUE TITLE
Linux -> Mac & enableCrossOsArchive -> Cache not found for input keys

### ISSUE THREAD

**Issue by niall-byrne** [actions/cache#1110]
When creating a simple cache of downloaded content in my Linux steps, and caching it, each Linux machine has no problem mounting the created cache and reusing the content.

When the workflow gets to the OSX machine, it does not register a cache hit, and instead creates a new cache instance with the identical key.  

Config:

Linux Machines (happy to use the cache):
```yaml
   - name: Ansible Lint -- Mount Ansible Cache
      uses: actions/cache@v3
      with:
        enableCrossOsArchive: true
        key: ansible-${{ hashFiles('./template/{{cookiecutter.profile_slug}}/profile/requirements.yml') }}-${{ env.CACHE_TTL }}
        path: ansible_cache
```
OSX Machine (creates it's own cache):

```yaml
    - name: Apply Profile -- Mount Ansible Cache
       uses: actions/cache@v3
       with:
         enableCrossOsArchive: true
         key: "ansible-${{ hashFiles('./template/{{cookiecutter.profile_slug}}/profile/requirements.yml') }}-${{ env.CACHE_TTL }}"
          path: ansible_cache
```
Am I assuming functionality that does not exist?

Example Workflow Run: https://github.com/osx-provisioner/profile-generator/actions/runs/4197900167/jobs/7280858264

**Comment by kleisauke** [comment]
I'm experiencing the same issue. See for example this debug CI run:
https://github.com/kleisauke/wasm-vips/actions/runs/4197093611/jobs/7279827475#step:4:42

Reverse engineering these version keys yields to:
```console
$ node -p "require('crypto').createHash('sha256').update('lib|gzip|1.0').digest('hex')"
2b8f91fb12183714d33b0e7ff6189a3363063c17729d1c6529f02e1fe17e91d8
$ node -p "require('crypto').createHash('sha256').update('lib|zstd-without-long|1.0').digest('hex')"
b8f3c3424597ca704ee437c4e20b46e1ec8212372b530f2cc52240b6d527d6c9
```

So, it looks like it's trying to use restore the cache using [`CompressionMethod.Gzip`](https://github.com/actions/toolkit/blob/b2d865f18051b214475dae41766e9970fd68ca12/packages/cache/src/internal/constants.ts#L7), which is inappropriate since the cache was saved with [`CompressionMethod.ZstdWithoutLong`](https://github.com/actions/toolkit/blob/b2d865f18051b214475dae41766e9970fd68ca12/packages/cache/src/internal/constants.ts#L10).

I suspect this is being caused by the zstd version bump to 1.5.4, which was recently rolled out to GitHub actions. See these commits:
https://github.com/actions/runner-images/commit/bf50e0da6fd3107aabdf950a2fae72a98aaf939b
https://github.com/actions/runner-images/commit/6b424ca736d5a5d9929beba8514b2c3dbaf0bbb6

Probably this is causing `zstd --version` no longer to output `zstd command line interface`, making `CompressionMethod` default to `CompressionMethod.Gzip`, which breaks the `enableCrossOsArchive: true` option.
https://github.com/actions/toolkit/blob/d2b7d85e7cb61467395604aae1b84439c320cb84/packages/cache/src/internal/cacheUtils.ts#L100

**Comment by kleisauke** [comment]
... commit https://github.com/facebook/zstd/commit/9c93dd71cdb301595a8a9e364348967a173c010c seems to be the culprit (released in zstd 1.5.4)

**Comment by parched** [comment]
I've added this step to my workflow as a temporary workaround
```
    # zstd 1.5.4 broke actions/toolkit https://github.com/actions/toolkit/issues/1341
    - if: runner.os == 'Windows'
      run: |
        if zstd --version | grep -q '1.5.[4-9]'; then
          choco install zstandard --version 1.5.0
          echo 'C:\ProgramData\chocolatey\bin'>>"$GITHUB_PATH"
        fi
      shell: bash
```

**Comment by panva** [comment]
`enableCrossOsArchive` is only documented to have an effect on windows runners. What I'm seeing now is that macOS gets cache-misses on linux-created caches.

**Comment by parched** [comment]
@panva yes, it's not related to OS, just the version of Zstandard that is installed. It just happens the Windows and macOS github hosted runners have Zstandard 1.5.4 installed and the Linux ones don't yet.

**Comment by kleisauke** [comment]
Here's a temporary workaround for both Windows and macOS:
```yml
      # https://github.com/actions/toolkit/issues/1341
      - name: Downgrade zstd on Windows
        if: runner.os == 'Windows'
        run: |
          Invoke-WebRequest https://github.com/facebook/zstd/releases/download/v1.5.2/zstd-v1.5.2-win64.zip -OutFile $env:RUNNER_TEMP\zstd.zip
          Expand-Archive $env:RUNNER_TEMP\zstd.zip -DestinationPath $env:RUNNER_TEMP
          Add-Content $env:GITHUB_PATH "$env:RUNNER_TEMP\zstd-v1.5.2-win64"
      - name: Downgrade zstd on macOS
        if: runner.os == 'macOS'
        run: |
          brew uninstall --ignore-dependencies zstd
          git -C "$(brew --repo homebrew/core)" checkout d3f04bd Formula/zstd.rb
          brew install zstd
```

(see e.g. commit https://github.com/kleisauke/wasm-vips/commit/d475fb3b61f5b458fc444943dd035c1b42827f75)
