### ISSUE TITLE
`Cache not found for keys` after Linux runner image update to 20230217.1

### ISSUE THREAD

**Issue by narumi147** [actions/cache#1112]
Yesterday, Linux runner image updated to 20230217.1, and cache could not be found.

workflow:
```yml
      - uses: actions/cache@v3
        with:
          path: ${{ env.cache_dir }}
          key: api-cache-${{ runner.os }}-${{ steps.get-date.outputs.date }}
          restore-keys: |
            api-cache-${{ runner.os }}-
            api-cache-
```

Output: 
```
Cache not found for input keys: api-cache-Linux-202302180150, api-cache-Linux-, api-cache-
```

The cache is there and works fine one hour before runner image updating.

Links:
- [available caches](https://github.com/chaldea-center/chaldea-parser/actions/caches)
- [success on 20230206.1](https://github.com/chaldea-center/chaldea-parser/actions/runs/4204186102/jobs/7294515568)
- [failure on 20230217.1](https://github.com/chaldea-center/chaldea-parser/actions/runs/4209027985/jobs/7305664054)
