### ISSUE TITLE
macOS cache restore is extremely slow

### ISSUE THREAD

**Issue by dexpota** [actions/cache#1115]
The macOS cache restore process is slow. I have created a repository that reproduces this slowness. You can find it [here](https://github.com/dexpota/macos-cache-slowness). Following is the screenshot of a run that took more than 2 hours.

![Screenshot 2023-02-20 at 08 22 47](https://user-images.githubusercontent.com/7031675/220039156-d454e285-9806-4f88-84a0-81053610c871.png)

This is the GitHub workflow.

```
name: Slow cache
on: [workflow_dispatch, push]
jobs:
  generate:
    name: Generate
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Add Specs repository
        run: pod repo add cocoapods https://github.com/CocoaPods/Specs.git
      - uses: actions/cache@v3
        with:
          path: ~/.cocoapods/repos/cocoapods
          key: ${{ runner.os }}-cocoapods-specs
  restore:
    name: Restore
    needs: generate
    runs-on: macos-12
    steps:
      - name: restore cached large file
        uses: actions/cache@v3
        with:
          path: ~/.cocoapods/repos/cocoapods
          key: ${{ runner.os }}-cocoapods-specs
```

Let me know if I can provide more information about it.
