### ISSUE TITLE
Slow cache retrieval speeds on the self-hosted runners

### ISSUE THREAD

**Issue by igorwojda** [actions/cache#1143]
In my setup the cache retrieval step is the longest step for each action:

<img width="774" alt="image" src="https://user-images.githubusercontent.com/530122/228657835-b70b601e-d8da-4c54-ab92-09763dc5c25a.png">

It takes  around 3-4 minutes to download and extract a 515MB cache file:

![image](https://user-images.githubusercontent.com/530122/228658070-806b654c-c553-4dfc-8329-1ddb19b5c632.png)

**Host OS**
Ubuntu 22

**Host Internet connection speed:**
This file `wget http://speedtest.novoserve.com/files/10GB.bin` download speed is 40-55MB/s

**Host CPU:**
Intel(R) Xeon(R) Silver 4310 CPU @ 2.10GHz (12 cores)

**Host I/O**
`hdparm -Tt /dev/sda` 
- Timing cached reads: 9070 MB/s
- Timing buffered disk reads: 1600MB/s

`d if=/dev/zero of=/tmp/test1.img bs=1G count=1 oflag=dsync`
- Write: 937 MB/s

**Config**
```
      - uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('gradle-checksums.txt') }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ hashFiles('gradle-checksums.txt') }}-
```

**Questions**
- Is there any way to speed up the network cache retrieval? 
- Is there a way to configure a local disk cache for the self-hosted runners? (ideally shared between runners)
