### ISSUE TITLE
Update R - renv example to remove usage of deprecated `set-output` command

### ISSUE THREAD

**Issue by jongwooo** [actions/cache#1149]
## Description

The `set-output` command is deprecated and no longer available, but seems to still be used in the [R - renv example](https://github.com/actions/cache/blob/main/examples.md#r---renv):

```yaml
- name: Get R and OS version
  id: get-version
  run: |
    cat("##[set-output name=os-version;]", sessionInfo()$running, "\n", sep = "")
    cat("##[set-output name=r-version;]", R.Version()$version.string, sep = "")
```
