### ISSUE TITLE
Github Actions: Image is pulled even if step is skipped

### ISSUE THREAD

**Issue by matheensyedaslam** [actions/cache#1182]
Github actions workflow as:

```
      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
Above linter image takes ~2 mins to pull the image and when we skip the stage it still pulls the image 
When run, if the "if" doesn't trigger the step gets skipped, but the container image for the action still gets pulled at the start of the workflow. Presumably because we're evaluating the "uses:" statements first. Is there a way to avoid this? Causing efficiency issues pulling images which aren't going to get used.

<img width="1416" alt="Screenshot 2023-06-08 at 1 17 06 PM" src="https://github.com/actions/cache/assets/91113771/62d55a26-3048-4085-ba83-40a6e634aab4">
