### ISSUE TITLE
Cache save failure is silently successful

### ISSUE THREAD

**Issue by pmed** [actions/cache#1189]
I have a job with a cache save action step like:
```
  - name: Cache build directory
    uses: actions/cache@v2
    with:
      path: ./build
      key: ${{ env.CACHE_VERSION }}-build-test
      restore-keys: |
        ${{ env.CACHE_VERSION }}-build-test
```

This step fails with a warning from the cache service with 500 error:

> Post job cleanup.
/usr/bin/docker exec  753ebc673e8c0bc1348b4c7c70cc7e429e7a567cc043866fb5d2a3684a233e5c sh -c "cat /etc/*release | grep ^ID"
/usr/bin/tar --posix -z -cf cache.tgz -P -C /__w/work-dir --files-from manifest.txt
**Warning: uploadChunk (start: 0, end: 33554431) failed: Cache service responded with 500**

That warning handling leads to successful job completion, and other job failing that tries to restore this cache later.

I believe the save cache action should fail on an error returned by the caching service.
