### ISSUE TITLE
The cache is created on but action does not find it next time

### ISSUE THREAD

**Issue by budarin** [actions/cache#1197]
Here is the [repo](https://github.com/budarin/zustand-clean-architecture/blob/master/.github/workflows/playwright.yml)

wf:
```yaml
            - name: Cache Node modules
              id: npm_cache
              uses: actions/cache@v3
              with:
                  key: nm-pw-${{ hashFiles('yarn.lock') }}
                  path: |
                      node_modules
                      ~/.cache/ms-playwright
                      
            - if: ${{ steps.npm_cache.outputs.cache-hit != 'true' }}
              run: yarn install --frozen-lockfile

            - if: ${{ steps.npm_cache.outputs.cache-hit != 'true' }}
              run: npx playwright install --with-deps
```
cache is create in post action

<img width="1091" alt="image" src="https://github.com/actions/cache/assets/8055157/7883dffe-02de-406e-adb0-f5d2572a679b">

But the next time the action is launched, it does not find this cache for some unknown reasons, although it is there!

<img width="1091" alt="image" src="https://github.com/actions/cache/assets/8055157/3d0c2c98-01c0-483b-90e1-884fb5311292">

**Comment by rdhar** [comment]
Appreciate you sharing that snippet, @budarin: exactly what I was looking for use in a GitHub Action workflow. Thanks!

```yml
- name: Set up Node
  uses: actions/setup-node@v4.0.2
  with:
    node-version: "20"

- name: Cache Node modules
  id: cache_node_modules
  uses: actions/cache@v4.0.0
  with:
    path: |
      ~/.cache/ms-playwright
      node_modules
    key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

- name: Install Node dependencies
  if: steps.cache_node_modules.outputs.cache-hit != 'true'
  run: npm ci

- name: Install Playwright dependencies
  if: steps.cache_node_modules.outputs.cache-hit != 'true'
  run: npx playwright install --with-deps

- name: Run Playwright tests
  run: npx playwright test
```
