### ISSUE TITLE
Exclusions do not work

### ISSUE THREAD

**Issue by pauldraper** [actions/cache#1215]
Exclusions do not work.

Example:

```yaml
jobs:
  save:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v3
      with:
        path: |
          cache
          !cache/unwanted
        key: ${{ github.workflow }}/${{ github.run_number }}-${{ github.run_attempt }}
    - run: |
        mkdir -p cache/wanted cache/unwanted
        > cache/wanted/example.txt
        > cache/unwanted/example.txt
  restore:
    needs: [save]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v3
      with:
        fail-on-cache-miss: true
        path: |
          cache
          !cache/unwanted
        key: ${{ github.workflow }}/${{ github.run_number }}-${{ github.run_attempt }}
    - run: find cache > "$GITHUB_STEP_SUMMARY"
on: workflow_dispatch
name: Example
```

Outputs:

```txt
cache
cache/wanted
cache/wanted/example.txt
cache/unwanted
cache/unwanted/example.txt
```

Reference: https://github.com/actions/cache/blob/67b839edb68371cc5014f6cea11c9aa77238de78/examples.md#c---nuget
