### ISSUE TITLE
Sometimes Error: Cannot find module '/var/run/act/actions/actions-cache@v3/dist/restore/index.js'

### ISSUE THREAD

**Issue by seepine** [actions/cache#1223]
```yml
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ steps.get-hash.outputs.hash }}
```

<img width="877" alt="截屏2023-08-23 15 47 36_副本" src="https://github.com/actions/cache/assets/93666053/c51f58ab-9773-4564-a527-e9d3b3dd8c32">

```
node:internal/modules/cjs/loader:936
  throw err;
  ^
Error: Cannot find module '/var/run/act/actions/actions-cache@v3/dist/restore/index.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```
