### ISSUE TITLE
doc: need to document limits on cache keys

### ISSUE THREAD

**Issue by srl295** [actions/cache#1225]
I was trying to use `${{ github.head_ref }}` as part of a cache key, however this ends up with:

```
  with:
    …
    key: git-main-CLDR-17028-Add-test-for-person-names,-and-regenerated-files
    restore-keys: git-main-CLDR-17028-Add-test-for-person-names,-and-regenerated-files
```

causes:

```
Error: Key Validation Error: git-main-CLDR-17028-Add-test-for-person-names,-and-regenerated-files cannot contain commas
```

I see this in the tests and underlying library, but is it documented where the limitations on cache keys are?
