### ISSUE TITLE
Caching Flutter/iOS dependencies

### ISSUE THREAD

**Issue by gmarizy** [actions/cache#1235]
I declared those actions to cache dependencies for a Flutter app targeting iOS: 
```yaml
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.FLUTTER_ROOT }}/.pub-cache
            **/.packages
            **/.flutter-plugins
            **/.flutter-plugin-dependencies
            **/.dart_tool/package_config.json
          key: build-pubspec-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            build-pubspec-

      - name: Cache pods
        uses: actions/cache@v3
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
```
            
Those actions are (seems ?) to be working fine (cache is created, retrieved and restored) but my build action re-download everything every time as if nothing was restored. What I am missing ?
