### ISSUE TITLE
`fail-on-cache-miss` for restore action not failing the workflow

### ISSUE THREAD

**Issue by wagoodman** [actions/cache#1265]
My interpretation of the `fail-on-cache-miss` feature on the `actions/cache` and `actions/cache/restore` actions is that the workflow should stop and be considered a fail if there is no cache found with the given key.

I'm seeing evidence in workflows where using the `actions/cache/restore` action will not fail even if this option is set to `true`.

Snippet from the workflow file:
```yaml
  Acceptance-Linux:
    name: "Acceptance tests (Linux)"
    needs: [Build-Snapshot-Artifacts]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 #v4.1.0

      - name: Bootstrap environment
        uses: ./.github/actions/bootstrap

      - name: Download snapshot build
        uses: actions/cache/restore@704facf57e6136b1bc63b828d79edcd491f0ee84 #v3.3.2
        with:
          path: snapshot
          fail-on-cache-miss: true
          key: snapshot-build-${{ github.run_id }}

      - name: Run comparison tests (Linux)
        run: make compare-linux
```

Evidence that the workflow continues past the failed cache restore (failing on the subsequent step, which it should have never reached.
<img width="926" alt="Screenshot 2023-10-20 at 1 27 58 PM" src="https://github.com/actions/cache/assets/590471/238e8e10-f88e-4a97-8a00-4a490eaafd7e">

**Comment by Rolexminus1** [comment]
> My interpretation of the `fail-on-cache-miss` feature on the `actions/cache` and `actions/cache/restore` actions is that the workflow should stop and be considered a fail if there is no cache found with the given key.
> 
> I'm seeing evidence in workflows where using the `actions/cache/restore` action will not fail even if this option is set to `true`.
> 
> Snippet from the workflow file:
> 
> ```yaml
>   Acceptance-Linux:
>     name: "Acceptance tests (Linux)"
>     needs: [Build-Snapshot-Artifacts]
>     runs-on: ubuntu-20.04
>     steps:
>       - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 #v4.1.0
> 
>       - name: Bootstrap environment
>         uses: ./.github/actions/bootstrap
> 
>       - name: Download snapshot build
>         uses: actions/cache/restore@704facf57e6136b1bc63b828d79edcd491f0ee84 #v3.3.2
>         with:
>           path: snapshot
>           fail-on-cache-miss: true
>           key: snapshot-build-${{ github.run_id }}
> 
>       - name: Run comparison tests (Linux)
>         run: make compare-linux
> ```
> 
> Evidence that the workflow continues past the failed cache restore (failing on the subsequent step, which it should have never reached. <img alt="Screenshot 2023-10-20 at 1 27 58 PM" width="926" src="https://user-images.githubusercontent.com/590471/277008565-238e8e10-f88e-4a97-8a00-4a490eaafd7e.png">

**Comment by wagoodman** [comment]
erg, thanks @Rolexminus1 ? (you might have intended to write something different than echoing my description... or you're a bot, in which case... _**beep beep, boop**_ )

For what it's worth, I think I found the problem that was causing the cache miss, which I'm also a little confused at:
```yaml
      - name: Upload snapshot artifacts
        uses: actions/cache/save@704facf57e6136b1bc63b828d79edcd491f0ee84 #v3.3.2
        with:
          path: |
            snapshot
            .task
          key: snapshot-build-${{ github.run_id }}
```

followed by:
```yaml
      - name: Download snapshot build
        id: snapshot-cache
        uses: actions/cache/restore@704facf57e6136b1bc63b828d79edcd491f0ee84 #v3.3.2
        with:
          path: snapshot
          fail-on-cache-miss: true
          key: snapshot-build-${{ github.run_id }}
```

Note the difference in the `path` provided (`snapshot` vs `[snapshot, .task]` logically).

My understanding is that I'd be able to store multiple paths and restore one of those paths, which does not appear to be working. However, in my case, this was a bug and I should have been restoring both paths anyway.

All that being said, it still doesn't address the original problem (`fail-on-cache-miss` doesn't fail the workflow) so I have the following workaround for now as a subsequent step:

```yaml
      - name: (cache-miss) Snapshot build missing
        if: steps.snapshot-cache.outputs.cache-hit != 'true'
        run: echo "unable to download snapshots from previous job" && false
```
