### ISSUE TITLE
Cache miss on Windows despite a successful cache-write

### ISSUE THREAD

**Issue by coot** [actions/cache#1275]
In this [run](https://github.com/input-output-hk/io-sim/actions/runs/6795507622/job/18473728925) (in the `Cache cabal store` we had a cache miss on Windows 

```
Run actions/cache@v3
  with:
    path: C:\sr
    key: cache-dependencies-pu4Aevoo_v1-Windows-8.10-42dc9d1d9517c36cc29f25d6a45c30c05b6faa6e98e7f7b96cb256858a8d7694
    restore-keys: cache-dependencies-pu4Aevoo_v1-Windows-8.10
    enableCrossOsArchive: false
    fail-on-cache-miss: false
    lookup-only: false
  env:
    CACHE_VERSION: pu4Aevoo_v1
Cache not found for input keys: cache-dependencies-pu4Aevoo_v1-Windows-8.10-42dc9d1d9517c36cc29f25d6a45c30c05b6faa6e98e7f7b96cb256858a8d7694, cache-dependencies-pu4Aevoo_v1-Windows-8.10
```

Despite the fact that the cache was successfully saved in this [run](https://github.com/input-output-hk/io-sim/actions/runs/6789505497/job/18472414440) (in the `Post Cache cabal store` step):
```
Post job cleanup.
"C:\Program Files\Git\usr\bin\tar.exe" --posix -cf cache.tzst --exclude cache.tzst -P -C D:/a/io-sim/io-sim --files-from manifest.txt --force-local --use-compress-program "zstd -T0"
Cache Size: ~19 MB (19879266 B)
Cache saved successfully
Cache saved with key: cache-dependencies-pu4Aevoo_v1-Windows-8.10-42dc9d1d9517c36cc29f25d6a45c30c05b6faa6e98e7f7b96cb256858a8d7694
```

This is Windows specific, on Ubuntu and MacOS cache can be retrieved.
