### ISSUE TITLE
"No scope" warning for pull request closed events

### ISSUE THREAD

**Issue by SatheeshJM** [actions/cache#129]
I get the warning `No scopes with read permission were found on the request.` if I setup my workflow for triggering on pull request: close.  
If I change the trigger to push, it works. 

Is the problem that the head_branch of the Pull Request can't read/write to the master's cache? 

An example config

```
on:
  pull_request:
    types: 
      - closed
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 1
    - name: Cache node modules
      id: cache_node_modules
      uses: actions/cache@v1
      with: 
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package.json') }}
```
for the above config the cache is never used.. I get the below warning
![image](https://user-images.githubusercontent.com/1222562/70833067-d3d39d80-1e1c-11ea-80fa-5eb3f56fce3e.png)

If I tweak the workflow to trigger on branch push, all is well
```
on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 1
    - name: Cache node modules
      id: cache_node_modules
      uses: actions/cache@v1
      with: 
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package.json') }}
```
![image](https://user-images.githubusercontent.com/1222562/70833159-0f6e6780-1e1d-11ea-8def-80c5d6712054.png)
