### ISSUE TITLE
Can not access cache from Linux runner on Mac runner

### ISSUE THREAD

**Issue by arjendevos** [actions/cache#1291]
This is what i run on the `ubuntu-latest` runner:
```
- name: Cache Yarn dependencies
      uses: actions/cache@v3
      with:
        enableCrossOsArchive: true
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: web-build-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          web-build-yarn-
```

And i'm trying to restore it in the next job on a `macos-latest` runner:
```
 - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          enableCrossOsArchive: true
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: web-build-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            web-build-yarn-
```

The Linux runner uploads the cache (i can see it also on github):
```
Cache Size: ~1846 MB (1935458230 B)
Cache saved successfully
Cache saved with key: web-build-yarn-24d4c0cdb90d06bf718fa92e8b763375d4b196e3704dcae754007728b3921bf5
```

But on macOS i get this:
```
Run actions/cache@v3
  with:
    enableCrossOsArchive: true
    path: /Users/runner/Library/Caches/Yarn/v6
    key: web-build-yarn-
    restore-keys: |
       web-build-yarn-
  
    fail-on-cache-miss: false
    lookup-only: false
Cache not found for input keys: web-build-yarn-24d4c0cdb90d06bf718fa92e8b763375d4b196e3704dcae754007728b3921bf5, web-build-yarn-
```
