### ISSUE TITLE
`lookup-only` doesn't with `cache-hit`

### ISSUE THREAD

**Issue by cschuchardt88** [actions/cache#1301]
Make a lot of sense to have an option for `lookup-only` when it set to `true` for `steps.cache-something.outputs.cache-hit` to not work.

So what's the work around?

### Cache Found on `lookup-only`
![image](https://github.com/actions/cache/assets/8141309/0a1e8a7b-163b-47e2-af77-a5d330560492)

### Next Step Code
```yml
    - if: ${{ steps.cache-leveldb.outputs.cache-hit != 'true' }}
      name: Checkout Repository Code (leveldb)
      uses: actions/checkout@v4
      with:
        repository: google/leveldb
        path: leveldb
        submodules: true
        fetch-depth: 0
```
