### ISSUE TITLE
Post Gems cache remains running indefinitely, does not respect timeout-minutes

### ISSUE THREAD

**Issue by ain** [actions/cache#132]
## Steps to reproduce

1. Add deploy step to Ruby project that uses `actions/cache`:

```yaml
      - name: Gem cache
        id: gem-cache
        timeout-minutes: 15
        uses: actions/cache@v1.0.3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore_keys: |
            ${{ runner.os }}-gem-
```

2. Add deploy step that triggers GAE deploy, e.g. using `actions-hub/gcloud@273.0.0`

## What happens

1. _Post Gem cache_ step remains running indefinitely even after all other steps finish successfully, e.g. more than an hour:

![Screenshot 2019-12-17 at 14 04 02](https://user-images.githubusercontent.com/370576/70998077-b92c4d80-20d6-11ea-91f7-072b6cfa00b6.png)

2. `timeout-minutes` of the step is not respected

## What should happen

1. No error should happen
2. If task hangs, `timeout-minutes` should be respected
