### ISSUE TITLE
Updated to actions/cache@v4, but that does not stop the Node16 warning on v3

### ISSUE THREAD

**Issue by bernhardkaindl** [actions/cache#1323]
https://github.com/xenserver/status-report/actions/runs/7802115676

This workflow (you can check the workflow file in the job itself) is upgraded `actions/cache@v4`, but that does not stop the warning about @v3...:

```py
Python3: Pre-Commit Suite
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

**Comment by ThabetAmer** [comment]
+1 same here having `actions/cache@v4`

**Comment by ruigomesbioinf** [comment]
+1 same here

**Comment by joshmgross** [comment]
This warning is coming from a composite action in your workflow

```yaml
      - uses: pre-commit/action@v3.0.0
        name: Run pre-commit checks
        with:
          # Show the output of the commands for the problem matcher, see above.
          extra_args: --all-files --verbose
        env:
          PYTHONDEVMODE: yes  # Enable Python3 checks. See the comment above.
          # Skip the no-commit-to-branch check inside of GitHub CI (for CI on merge to master)
          SKIP: no-commit-to-branch
```

https://github.com/pre-commit/action/issues/189

I'd recommend updating to the latest version of that action - https://github.com/pre-commit/action/releases/tag/v3.0.1

https://github.com/xenserver/status-report/blob/master/.github/workflows/main.yml#L176


If anyone else is experiencing this issue, I'd recommend checking all of the actions your workflow depends on.
