### ISSUE TITLE
Running actions/cache in a composite action and setting the path via input does not save the cache

### ISSUE THREAD

**Issue by dreinhardt-terminus** [actions/cache#1359]
I run my action as a part of a composite.

When I run it however it doesn't seem to pickup the input even though I clearly see the input in the console log.

```yaml
  - name: Helm - Cache Charts
    id: helm_cache_charts
    uses: actions/cache@v4
    with:
      path: ${{ inputs.cache_path }}
      key: helm-chart-cache-${{ steps.chart_lock_file_hash.outputs.chart_lock_file_hash }}
```

![image](https://github.com/actions/cache/assets/85892019/63cf11c7-edab-4ce3-b752-bbcfe8944059)
![image](https://github.com/actions/cache/assets/85892019/a770e806-4f55-4424-a38d-09442bf1f91c)
