### ISSUE TITLE
cache restore on versions 3 and 4 not working

### ISSUE THREAD

**Issue by mark-jordanovic-lewis** [actions/cache#1361]
The functionality of the cache action seems to be completely broken.

Configurations attempted:
- save/restore actions @v4
- save/restore actions @v3
- base cache action @v4
- base cache action @v3

The cache is being accessed on the same branch, in the same workflow (and later, if the first set of jobs pass).

![Screenshot 2024-03-19 at 17 07 18](https://github.com/actions/cache/assets/20165821/e6560239-8bbb-4f25-b5f3-2e34bdb06ad6)
![Screenshot 2024-03-19 at 17 17 01](https://github.com/actions/cache/assets/20165821/6f2e9dc0-9653-4f82-85b7-e2dfe06aecc8)
<img width="800" alt="Screenshot 2024-03-19 at 17 20 47" src="https://github.com/actions/cache/assets/20165821/5bb56d5e-e369-4722-86ad-9b849d318a5d">

These screenshots pertain to the run of base cache action @v3, they are consistent across all configurations.

**Comment by mark-jordanovic-lewis** [comment]
Cause of the above issue is a difference in the actions/checkout version. There must be a difference in the way they reference the branch.

**Comment by matthiasPOE** [comment]
Im currently getting:

`Failed to save: Unable to reserve cache with key db09ccc890352b660ddd94bbcf7ce4b880b254099c5050c6059b00b0b4c5777e, another job may be creating this cache. More details: Cache already exists.`

Not sure if its related but even deleting all caches it wont recreate them...

**Comment by serpro69** [comment]
Any of the maintainers even seen this issue? I wonder how this is still not fixed or at least commented on by someone who maintains github's actions. This is core functionality of this action and has been broken for at least 3 weeks now....

**Comment by yrtimiD** [comment]
@mark-jordanovic-lewis just to ensure, do you have exactly same value in the "path" parameter both in save and restore? I had different and restore failed too.

**Comment by mark-jordanovic-lewis** [comment]
Correct. Same parameters in each use of the action.

**Comment by serpro69** [comment]
```
Cache not found for input keys: Linux-maven-bf2c5b52045abd9ea06d4e8da127d1448524f18695ec1e5f8a451c87f058b43a, Linux-maven-bf2c5b52045abd9ea06d4e8da127d1448524f18695ec1e5f8a451c87f058b43a, Linux-maven-
```

Aren't these supposed to be matched for `Linux-maven-` key?

![image](https://github.com/actions/cache/assets/22973227/8c903e77-62be-4f2f-a61c-92b8829b6a3b)

This is on v2 :/

**Comment by SimonSchick** [comment]
We are seeing similar issues on v4 where the cache is not found despite clearly existing, only 1/5 runs are picked up correctly, is the cache action not reliable-ish?

**Comment by njzjz** [comment]
I encountered the same issue. Save v4 + restore v2 cannot work as well. Using save v2 + restore v2 can resolve the problem. However, it seems that Node.js 16 is going to be deprecated.

**Comment by njzjz** [comment]
> I encountered the same issue. Save v4 + restore v2 cannot work as well. Using save v2 + restore v2 can resolve the problem. However, it seems that Node.js 16 is going to be deprecated.

I just found the reason: in v4, the `path` for `restore` and `save` must be the same. The error message doesn't give such information.

**Comment by wmertens** [comment]
@njzjz I'm encountering this problem too and the paths are the same for me

**Comment by MostefaKamalLala** [comment]
Facing the same issue, any fix anytime soon?

**Comment by hammzj** [comment]
I can also confirm that `v2` works, but `v4` is completely broken. I am running a job with a matrix and am consistently getting failures because it cannot save nor restore the cache correctly.

**Comment by serpro69** [comment]
To be frank I'm surprised how a core action like "cache" is still broken and no (visible) steps are taken to fix it... At times github actions seem completely unreliable for anything beyond small open-source stuff that isn't mission-critical.

**Comment by markfickett** [comment]
I hit this too. I was using `actions/cache@v4.0.2` to save a virtual env and some other things, specifying a literal `path` on that job, and then setting job outputs for the different things in the path (like `outputs: venv-path: my-venv`). Then in another job, I used `actions/cache/restore@v4.0.2` and referenced the same list of paths but via output variables (like `paths: ${{ needs.setup-env.outputs.venv-path }}`). As others have described, I could see the cache being created (and the `setup-env` job could pick up its own cache), but the downstream jobs say they can't find the cache. Changing both lists to be literal instead fixed the issue.

Variations of this issue seem to be reported in a number of other issues:
* https://github.com/actions/cache/issues/1198
* https://github.com/actions/cache/issues/1194
* and possibly https://github.com/actions/cache/issues/1275

**Comment by wmertens** [comment]
@markfickett my paths are static and I'm experiencing this issue.

The problem is that it's intermittent.

**Comment by danielkorte** [comment]
Also confirming v4 is broken. I’m using static paths as well. I downgraded to v2 and everything works now.

**Comment by matthiasPOE** [comment]
@bethanyj28 @robherley @kotewar sorry about the pings but I cant believe this has been sitting here broken for so long

**Comment by mark-jordanovic-lewis** [comment]
I have some workflows in which v3 and v4 work consistently and some that fail consistently. I'm not seeing the intermittant success/fail but I do see inconsistenty across workflows.

**Comment by mark-jordanovic-lewis** [comment]
# Cache Experiment Workflow
```
on:
  push:

jobs:
  # Cache files `cache-file-runner` and `cache-file-container`
  cache-file-runner:
    runs-on: ubuntu-22.04
    steps:
      - name: Create cache-file
        run: |
          touch cache-file-runner
          echo "I am in ubuntu-latest-runner cache" > cache-file-runner
      - uses: actions/cache/save@v4
        with:
          path: cache-file-runner
          key: ${{ github.sha }}-cache-file-runner
          enableCrossOsArchive: true

  cache-file-container:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:22.04
    steps:
      - name: Create cache-file
        run: |
          touch cache-file-container
          echo "I am in ubuntu-latest-container cache" > cache-file-container
      - uses: actions/cache/save@v4
        with:
          path: ./cache-file-container
          key: ${{ github.sha }}-cache-file-container
          enableCrossOsArchive: true

  # Read each of the cache files from the runner
  runner-read-runner-cache:
    runs-on: ubuntu-22.04
    needs: ["cache-file-runner", "cache-file-container"]
    steps:
      - uses: actions/cache/restore@v4
        with:
          path: cache-file-runner
          key: ${{ github.sha }}-cache-file-runner
      - name: Check cache-file
        run: |
          if [ -f "cache-file-runner" ]
          then
            echo "Found cached file"
          else
            echo "Cache not restored"
          fi

  runner-read-container-cache:
    runs-on: ubuntu-22.04
    needs: ["cache-file-runner", "cache-file-container"]
    steps:
      - uses: actions/cache/restore@v4
        with:
          path: cache-file-container
          key: ${{ github.sha }}-cache-file-container
      - name: Check cache-file
        run: |
          if [ -f "cache-file-container" ]
          then
            echo "Found cached file"
          else
            echo "Cache not restored"
          fi

  # Read each of the cache files from the container
  container-read-runner-cache:
    runs-on: ubuntu-22.04
    needs: ["cache-file-runner", "cache-file-container"]
    container:
      image: ubuntu:22.04
    steps:
      - uses: actions/cache/restore@v4
        with:
          path: cache-file-runner
          key: ${{ github.sha }}-cache-file-runner
      - name: Check cache-file
        run: |
          if [ -f "cache-file-runner" ]
          then
            echo "Found cached file"
          else
            echo "Cache not restored"
          fi

  container-read-container-cache:
    runs-on: ubuntu-22.04
    needs: ["cache-file-runner", "cache-file-container"]
    container:
      image: ubuntu:22.04
    steps:
      - uses: actions/cache/restore@v4
        with:
          path: cache-file-container
          key: ${{ github.sha }}-cache-file-container
      - name: Check cache-file
        run: |
          if [ -f "cache-file-container" ]
          then
            echo "Found cached file"
          else
            echo "Cache not restored"
          fi
          
  # CrossOs access
  runner-crossOS-read-container-cache:
    runs-on: ubuntu-22.04
    needs: ["cache-file-runner", "cache-file-container"]
    steps:
      - uses: actions/cache/restore@v4
        with:
          path: cache-file-container
          key: ${{ github.sha }}-cache-file-container
          enableCrossOsArchive: true
      - name: Check cache-file
        run: |
          if [ -f "cache-file-container" ]
          then
            echo "Found cached file"
          else
            echo "Cache not restored"
          fi

  container-crossOS-read-runner-cache:
    runs-on: ubuntu-22.04
    needs: ["cache-file-runner", "cache-file-container"]
    container:
      image: ubuntu:22.04
    steps:
      - uses: actions/cache/restore@v4
        with:
          path: cache-file-runner
          key: ${{ github.sha }}-cache-file-runner
          enableCrossOsArchive: true
      - name: Check cache-file
        run: |
          if [ -f "cache-file-runner" ]
          then
            echo "Found cached file"
          else
            echo "Cache not restored"
         fi
```
# Results
<img width="315" alt="Screenshot 2024-07-05 at 09 02 39" src="https://github.com/actions/cache/assets/20165821/98e30ac7-30bb-47c6-ad92-d7979375a62e">
<img width="315" alt="Screenshot 2024-07-05 at 09 03 03" src="https://github.com/actions/cache/assets/20165821/f2ee8213-c1f1-4bb1-8ffc-a9feaa3b967d">
<img width="315" alt="Screenshot 2024-07-05 at 09 03 33" src="https://github.com/actions/cache/assets/20165821/f48bfcf6-36d0-4ff7-9ef1-695e7d5f85af">
<img width="315" alt="Screenshot 2024-07-05 at 09 03 55" src="https://github.com/actions/cache/assets/20165821/b0e558c0-4090-433b-8aa7-e6e037accfbf">
<img width="315" alt="Screenshot 2024-07-05 at 09 04 12" src="https://github.com/actions/cache/assets/20165821/1f4d1baf-5c82-4e58-9e5f-36436e014c9b">
<img width="315" alt="Screenshot 2024-07-05 at 09 04 29" src="https://github.com/actions/cache/assets/20165821/a62fe72d-719b-469b-a699-1dc14d6dc91b">

**Comment by njzjz** [comment]
@mark-jordanovic-lewis I am not sure about other jobs, but for `container-read-container-cache`, you just need to change `path: cache-file-container` to `path: ./cache-file-container` to match the path in `cache-file-container`.

**Comment by mark-jordanovic-lewis** [comment]
> @mark-jordanovic-lewis I am not sure about other jobs, but for `container-read-container-cache`, you just need to change `path: cache-file-container` to `path: ./cache-file-container` to match the path in `cache-file-container`.

Correct. Thanks @njzjz.

**Comment by wmertens** [comment]
I just realized I had a trailing slash in one of the places and not the others. Now I made sure all the path strings are 100

**Comment by mdeweerd** [comment]
I confirm that caching works after:
- Prefixing each path of the `path:` value with `./`;
- Having the exact same `path:` value for save and restore (I had wildcards in the save action path).

**Comment by coreymcmahon** [comment]
Just want to highlight that we're also having problems with v3 and v4.

Our build (at a high level) does this:

(1) Download dependencies (using Composer as it's a PHP app, but I don't think that detail is important) and cache them using `actions/cache/save@v4`
(2a) Build frontend assets (after restoring Composer dependencies with `actions/cache/restore@v4`)
(2b) Run static analysis (after restoring Composer dependencies with `actions/cache/restore@v4`)
(3) Run tests

Steps (2a) and (2b) `need` step (1) and run concurrently after step (1) is finished. The call to `actions/cache/restore@v4` works in step 2b and fails in step 2a.

After reverting to v2 this works as expected.

Our workflow file looks something like the following:

```yml
name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  composer_install:
    name: Install composer dependencies
    runs-on: ubuntu-latest
    container:
      image: jakzal/phpqa:php8.3-alpine
    steps:
      - uses: actions/checkout@v4
      - name: Cache composer dependencies
        uses: actions/cache/save@v4
        id: cache-composer
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
      - name: Install composer dependencies
        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress

  build_frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    needs: [composer_install]
    container:
      image: node:20.11.0
    steps:
      - uses: actions/checkout@v4
      - name: Cache frontend build
        uses: actions/cache/save@v4
        id: cache-frontend
        with:
          path: public/build
          key: npm-${{ hashFiles('package-lock.json') }}
      - name: Restore composer cache
        uses: actions/cache/restore@v4
        id: restore-composer-cache
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
          fail-on-cache-miss: true
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build

  static_analysis_check:
    name: Check static analysis
    runs-on: ubuntu-latest
    container:
      image: jakzal/phpqa:php8.3-alpine
    needs: [composer_install]
    steps:
      - uses: actions/checkout@v4
      - name: Restore composer cache
        uses: actions/cache/restore@v4
        id: restore-composer-cache
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
          fail-on-cache-miss: true
      - name: Run PHPStan analysis
        run: php -d memory_limit=-1 vendor/bin/phpstan analyze --error-format=github

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    container:
      image: jakzal/phpqa:php8.3-alpine
    needs: [composer_install, build_frontend]
    steps:
      - uses: actions/checkout@v4
      - name: Restore composer cache
        uses: actions/cache/restore@v4
        id: restore-composer-cache
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
          fail-on-cache-miss: true
      - name: Restore frontend cache
        uses: actions/cache/restore@v4
        id: restore-frontend-cache
        with:
          path: public/build
          key: npm-${{ hashFiles('package-lock.json') }}
          fail-on-cache-miss: true
      # snip... not relevant after this line
```
