### ISSUE TITLE
Using cache with git tags

### ISSUE THREAD

**Issue by MrExplode** [actions/cache#1371]
I manage my deployments using git tags. I noticed that none of my cache setups work in my action jobs. I have looked at the actions docs extensively, and I only found [one word](https://github.com/actions/cache/issues/1342) mentioning tags in the [cache restrictions](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache) section.
Apparently git tags act as a separation layer between caches.
![image](https://github.com/actions/cache/assets/25108970/8efb4caa-f966-4fd8-920d-1a828e127ec2)
Is it possible to disable or bypass this cache scoping?
I would really love if my runs could have the benefits of caching.

The above image is the result of the following section (which is the exact one mentioned at the [pnpm docs](https://pnpm.io/continuous-integration#github-actions)):
```yml
- name: Setup pnpm
  uses: pnpm/action-setup@v2
  with:
    version: 8

- name: Setup Node
  uses: actions/setup-node@v4
  with:
    node-version: 20
    cache: pnpm

- name: Install dependencies
  run: pnpm install --frozen-lockfile
```
