### ISSUE TITLE
Signing certificate with thumbprint *** not found in store

### ISSUE THREAD

**Issue by sameignatovich** [actions/cache#1384]
Hello!

I just created new repo and pushed my code with workflow in it. It's using docker for build process and GitHub cache for storing build cache.

I receive next error message on cache sending:
```
#21 exporting to GitHub Actions Cache
#21 preparing build cache for export
#21 preparing build cache for export 9.1s done
#21 ERROR: Signing certificate with thumbprint 943DC3545AEC524FF3E4C1FC45CE22256D24C501 not found in store /etc/certificates. See https://aka.ms/actionsDbBackups for possible mitigation.
```
(link in message not working, btw)

I'm using same config for similar project in another repo and it's working fine. But here it's not working at all.

I'm using self-hosted runner. I was checked twice what similar project was built on same worker. And cache working fine.

my workflow yaml file:

```YAML
name: Docker Image CI/CD

on:
  push:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: [self-hosted, linux, arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: SOMEREPO.COM
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            VITE_BASE_API_URL=${{ vars.VITE_BASE_API_URL }}
          push: true
          tags: SOMEREPO.COM/SOMEIMAGE:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: [self-hosted, linux, arm64]
    needs: build

    steps:
      - name: Make request to webhook
        env:
          DEPLOY_WEBHOOK: ${{ vars.DEPLOY_WEBHOOK }}
        run: curl -X POST $DEPLOY_WEBHOOK
```
