### ISSUE TITLE
Duplicated cache due to concurrency

### ISSUE THREAD

**Issue by pespinel** [actions/cache#1392]
## Misc
When running multiple workflows at the same time, the cache is duplicated due to concurrency, even with the same key and for the same branch:

![Captura de pantalla 2024-05-02 a las 8 47 11](https://github.com/actions/cache/assets/37797002/6b24b81c-9003-41af-b9d8-84355b653c9a)

Version: cache@v4
Step:
```
    - name: Cache
      uses: actions/cache@v4
      id: cache
      with:
        key: venv-${{ runner.os }}-${{ runner.arch }}-pip-${{ hashFiles(format('acceptance/{0}', inputs.file)) }}
        path: ${{ steps.cache-dir.outputs.dir }}
        restore-keys: ${{ runner.os }}-${{ runner.arch }}-pip-
```
