### ISSUE TITLE
ETIMEDOUT in Docker

### ISSUE THREAD

**Issue by sadorowo** [actions/cache#1403]
Hello, I'm using actions/cache with Gitea Actions on my server with Docker. Currently I have gitea & worker containers set up. When I try to cache Gradle, I'm getting this error:

```
::warning::Failed to restore: getCacheEntry failed: connect ETIMEDOUT 192.168.128.2:37161
Cache not found for input keys: gradle-Linux-7eb08380508cca17032f764e4c20dc17747fe243646826e65c07ae60ddb508a7
```

My cache job (ignore indentation):
```yaml
            -   name: Get hash of Gradle files
                uses: https://gitea.com/actions/go-hashfiles@v0.0.1
                id: get-hash
                with: 
                    patterns: |-
                        **/*.gradle*

            -   name: Cache Gradle
                uses: actions/cache@v3
                with:
                    path: |
                        ~/.gradle/caches
                        ~/.gradle/wrapper
                    key: gradle-${{ runner.os }}-${{ steps.get-hash.outputs.hash }}
```

Issue isn't in go-hashfiles action. Without it, I'm still getting ETIMEDOUT.
