### ISSUE TITLE
`enableCrossOsArchive` appears to be broken-- unless I'm misunderstanding something

### ISSUE THREAD

**Issue by donn** [actions/cache#1443]
So first of all, I would like to thank you for the cache action. When it works, it's magic and it saves a ton of time.

However, if you try to restore a Linux cache on Windows or macOS (x86-64 or aarch64) with the `enableCrossOsArchive` input set to `true`, it invariably fails. This workflow acts as a minimal reproducer:

```yml
name: CI
on:
  push:

jobs:
  prepare:
    name: Test Cache
    runs-on: ubuntu-24.04
    steps:
      - id: cache-number
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/path-with-number
          key: number-cache
          enableCrossOsArchive: true
      - run: |
          mkdir -p path-with-number/
          echo "0123456789" > path-with-number/number
  test:
    name: Test Cache Restore
    runs-on: ${{ matrix.os }}
    needs: [prepare]
    strategy:
      matrix:
        os: ["macos-13", "macos-14", "ubuntu-24.04", "windows-2022"]
      fail-fast: false
    steps:
      - id: restore-number
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/path-with-number
          key: number-cache
          enableCrossOsArchive: true
      - if: steps.restore-number.outputs.cache-hit != 'true'
        run: |
          exit -1

```

In my testing, the Mac and Windows jobs always fail.

The documentation doesn't mention macOS consuming a Linux cache at all, but if I'm understanding it correctly, Windows at least *should* work: https://github.com/actions/cache/blob/4a28cbc0544512425977dda4ce81a9b6f0f34ad9/tips-and-workarounds.md#cross-os-cache

Is this a bug? Or am I misunderstanding something?
