### ISSUE TITLE
Cache always not found (yarn + linux)

### ISSUE THREAD

**Issue by Cerberus** [actions/cache#149]
Hello : )

I've tried to apply this action to my workflow but it seems like does not work properly.

On the post action step, it completed with `Cache saved successfully`. But on the next action event. It always displays `Cache not found` with the same key.

Could you please a little bit check on this example [link](https://github.com/Cerberus/script/actions) ?

My workflow config:
```
      - name: Get yarn cache
        id: yarn-cache
        run: |
          echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1.1.0
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: yarn-
```

pkg manager: yarn
env: Linux
