### ISSUE TITLE
takes extremely long to cache on windows

### ISSUE THREAD

**Issue by gucio321** [actions/cache#1490]
It takes extremely long time to run this job (around 18 minutes?!)
example run: https://github.com/AllenDang/giu/actions/runs/11592336860/job/32273983921?pr=898
this is a matrix os and it works normally on mac and ubuntu.
```yaml
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

```
