### ISSUE TITLE
pipenv example

### ISSUE THREAD

**Issue by ConorSheehan1** [actions/cache#152]
Does this work with [pipenv](https://github.com/pypa/pipenv)?
And if so, could you add an example to the readme, similar to the [pip example](https://github.com/actions/cache/blob/master/examples.md#python---pip)?

**Comment by guilhermearaujo** [comment]
Far from ideal, but I managed to get it working using two caches:

```yaml
# This one caches both pip and pipenv downloads
- name: Cache dependencies
  uses: actions/cache@v1
  with:
    path: ~/.cache
    key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}

# This will cache the whole virtualenv with built dependencies (and a lot more, though)
- name: Cache virtualenv
  uses: actions/cache@v1
  with:
    path: ~/.local/share/virtualenvs
    key: ${{ runner.os }}-venv-${{ hashFiles('**/Pipfile.lock') }}
```

I really dislike the virtualenv cache, since it's caching a lots of extra stuff, not only the dependencies. I am not sure what (terrible?) consequences this may cause, but I haven't had any issues with this settings in the past month
