### ISSUE TITLE
Support `working-directory`

### ISSUE THREAD

**Issue by F-WRunTime** [actions/cache#1529]
Per the title it would be great if this supported working-directory to set the folder where you are running code for a step
```yaml
    - name: Save ${{ inputs.target }} 
      if: always()
      working-directory: ${{ inputs.workdir }}
      uses: actions/cache/save@v4.2.0
      with:
        path: "file.tar.gz"
        key: ${{ inputs.target }}-corpus-${{ github.run_id }}
```

The path is so strict that when folder structure is not always static it makes working with save / restore very difficult.
