### ISSUE TITLE
Avoiding duplication of key calculation when using conditional cache restore

### ISSUE THREAD

**Issue by michaelmior** [actions/cache#1532]
I have data cached that I want to refresh periodically with a scheduled run. I tried to do the following. The goal is to not restore the cache when the Action is triggered by a scheduled event.

```
      - name: Restore cached run
        uses: actions/cache/restore@v4
        id: cache-report
        if: ${{ github.event_name != 'schedule' }}
        with:
          path: output.txt
          key: ${{ some-complicated-key-calculation }}
    # Other steps...
      - name: Cache report
        uses: actions/cache/save@v4
        if: ${{ steps.cache-report.outputs.cache-hit != 'true' }}
        with:
          path: output.txt
          key: ${{ steps.cache-report.outputs.cache-primary-key }}
```

This somewhat works, although since the `restore` step is skipped, the cache key is never calculated, so the output `cache-primary-key` is never populated. Of course, I can copy the computation of the key into the save step, but I'm wondering if there's a way to avoid that duplication.
