### ISSUE TITLE
Purge fails

### ISSUE THREAD

**Issue by TheGroundZero** [actions/cache#1538]
Following [this](https://github.com/actions/cache/blob/main/tips-and-workarounds.md#force-deletion-of-caches-overriding-default-cache-eviction-policy) guide, I wrote the following (reusable) GitHub action:

```yaml
name: Purge cache elements
description: Purge cached elements
inputs:
  gh_token:
    required: true
    description: GH_TOKEN
runs:
  using: "composite"
  steps:
    - name: Purge cache
      shell: bash
      run: |
      gh extension install actions/gh-actions-cache
      
      REPO=${{ github.repository }}
      BRANCH=refs/pull/${{ github.event.pull_request.number }}/merge

      echo "Fetching list of cache key"
      cacheKeysForPR=$(gh actions-cache list -R $REPO -B $BRANCH | cut -f 1 )

      ## Setting this to not fail the workflow while deleting cache keys. 
      set +e
      echo "Deleting caches..."
      for cacheKey in $cacheKeysForPR
      do
          gh actions-cache delete $cacheKey -R $REPO -B $BRANCH --confirm
      done
      echo "Done"
    env:
      GH_TOKEN: ${{ inputs.gh_token }}
branding:
  icon: trash
  color: red
```

which I then call in my workflows using

```yaml
---
name: Build and Deploy
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  # ...
jobs:
  # ...

  purge:
    name: Purge cache
    runs-on: ubuntu-latest
    permissions:
      # `actions:write` permission is required to delete caches
      #   See also: https://docs.github.com/en/rest/actions/cache?apiVersion=2022-11-28#delete-a-github-actions-cache-for-a-repository-using-a-cache-id
      actions: write
      contents: read
    needs:
      - build
      - deploy
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Purge cache
        uses: ./.github/actions/cache_purge
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
```

However, this fails with the following error:

```
Error: /home/runner/work/repo/repo/./.github/actions/cache_purge/action.yml: (Line: 15, Col: 7, Idx: 283) - (Line: 15, Col: 7, Idx: 283): While scanning a simple key, could not find expected ':'.
Error: System.ArgumentException: Unexpected type '' encountered while reading 'action manifest root'. The type 'MappingToken' was expected.
   at GitHub.DistributedTask.ObjectTemplating.Tokens.TemplateTokenExtensions.AssertMapping(TemplateToken value, String objectDescription)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Failed to load /home/runner/work/repo/repo/./.github/actions/cache_purge/action.yml
```

![Image](https://github.com/user-attachments/assets/d7589fd3-4fbb-4afd-aa6e-e907251f88b8)

**Comment by joshmgross** [comment]
It looks like your indentation is off in your `run` step -

Does this work?

```yaml
name: Purge cache elements
description: Purge cached elements
inputs:
  gh_token:
    required: true
    description: GH_TOKEN
runs:
  using: "composite"
  steps:
    - name: Purge cache
      shell: bash
      run: |
        gh extension install actions/gh-actions-cache
        
        REPO=${{ github.repository }}
        BRANCH=refs/pull/${{ github.event.pull_request.number }}/merge

        echo "Fetching list of cache key"
        cacheKeysForPR=$(gh actions-cache list -R $REPO -B $BRANCH | cut -f 1 )

        ## Setting this to not fail the workflow while deleting cache keys. 
        set +e
        echo "Deleting caches..."
        for cacheKey in $cacheKeysForPR
        do
            gh actions-cache delete $cacheKey -R $REPO -B $BRANCH --confirm
        done
        echo "Done"
      env:
        GH_TOKEN: ${{ inputs.gh_token }}
branding:
  icon: trash
  color: red
```
