### ISSUE TITLE
Bug: Failed to CreateCacheEntry

### ISSUE THREAD

**Issue by icanhazstring** [actions/cache#1541]
Greetings.

Since today Feb 7th around 1AM CET we got a problem with the `actions/cache`.
We can't use `actions/cache/save` anymore and get the following error

```
Warning: Failed to save: Failed to CreateCacheEntry: Received non-retryable error: Failed request: (404) Not Found: invalid request
```

This is a simple cache step as described in the docs:
```
      - name: Cache vendor
        uses: actions/cache/save@v4
        with:
          key: ${{ env.VENDOR_CACHE_KEY }}
          path: |
            vendor/
            vendor-bin/
```

Current workaround:
Fix the version to `v4.1.2`. This should solve the issue for now.
