### ISSUE TITLE
Incorrect check of version for the deprecation

### ISSUE THREAD

**Issue by BoD** [actions/cache#1548]
Following [this annoucement](https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down), workflows automatically fail for old versions of this action.

In [our workflow](https://github.com/apollographql/apollo-kotlin/blob/578a74bc9335917477508173a2d81e79867fee97/.github/workflows/pr.yml#L153) we reference versions by sha1 rather than by tag:

```yaml
      - name: Setup Plugin Verifier IDEs Cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 #v4.0.2
        with:
          path: ${{ steps.properties.outputs.pluginVerifierHomeDir }}/ides
          key: plugin-verifier-${{ hashFiles('intellij-plugin/build/listProductsReleases.txt') }}
```

This is a good practice that ensures reproducible builds and avoids potential security issues.

In our case `0c45773b623bea8c8e75f6c82b208c3cf94ea4f9` is the sha1 for `v4.0.2` which, if I'm not mistaken, should not fail the build as it is recent enough. But this [failed the build](https://github.com/apollographql/apollo-kotlin/actions/runs/13268785533/job/37042949096?pr=6383#step:1:36).
