### ISSUE TITLE
Cache multiple paths

### ISSUE THREAD

**Issue by hugovk** [actions/cache#16]
It can be useful to cache multiple directories, for example from different tools like pip and pre-commit.

With Travis CI (ignoring their `pip: true` shortcut):

```yml
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
```

The Actions equivalent requires adding a duplicated step for each directory, something like:

```yml
      - name: pip cache
        uses: actions/cache@preview
        with:
          path: ~/.cache/pip
          key: ${{ matrix.python-version }}-pip

      - name: pre-commit cache
        uses: actions/cache@preview
        with:
          path: ~/.cache/pre-commit
          key: ${{ matrix.python-version }}-pre-commit
```

Perhaps also allow multiple directories in a single step, something like this?

```yml
      - name: pip cache
        uses: actions/cache@preview
        with:
          path:
            - ~/.cache/pip
            - ~/.cache/pre-commit
          key: ${{ matrix.python-version }}
```

**Comment by chrispat** [comment]
We made a scoping call for the v1 to not support multiple paths.  This is somethign we do plan to look at  for the future.

**Comment by nathany** [comment]
Same requirement for Elixir where we commonly cache multiple paths:

```
paths:
  - _build
  - deps
```

**Comment by mrmckeb** [comment]
This will definitely be required for many open source projects. We want to trial this on some Storybook projects, but caching for a monorepo (Yarn) would be needed for that - along with #6.

But that's not to discourage this great first-step.

**Comment by Siedlerchr** [comment]
This would be very important, for example if you build a web app for android in node, you will add node_modules and also gradle to the cache.

**Comment by dbrockman** [comment]
Would it be possible to use a glob pattern for path?

The user case that I have in mind is caching the typescript build output in a monorepo.

For example:
```
path: packages/*/{build,tsconfig.tsbuildinfo}
```

**Comment by imbsky** [comment]
Is anyone already working on this?

**Comment by mrmckeb** [comment]
It might also be good if this didn't require config for something like Yarn, where you could just say `workspaces: true`.

**Comment by jcornaz** [comment]
>It might also be good if this didn't require config for something like Yarn

I don't think it is good for this project to have tool-specific behavior. I think it should be agnostic of whatever tools we use.

**Comment by imbsky** [comment]
I agree with @jcornaz.

**Comment by mrmckeb** [comment]
I'm not sure I can agree. That would mean considerable overhead for projects - the bigger they are, the more work someone is going to need to put in to configure their CI.

It would make more sense for the action to do that heavy lifting, as that's exactly what actions exist for.

**Comment by imbsky** [comment]
Is this proposal so far from your goal? https://github.com/actions/cache/issues/16#issuecomment-551202039

**Comment by imbsky** [comment]
Well, I already say that in #70...

**Comment by mrmckeb** [comment]
@imbsky, that's a great start - but something like Yarn workspaces has more complex caching requirements.

**Comment by imbsky** [comment]
@mrmckeb Yes, I understand that, but do we create options for all ecosystems? That's not realistic.

**Comment by jcornaz** [comment]
>Yes, I understand that, but do we create options for all ecosystems? That's not realistic.

I would go farther than saying "it is not realistic". I would say "it is not desirable".

I think, this this project should strive to be flexible and useful for as many different ecosystems as possible. Introducing yarn-specific behavior, would add maintenance overhead that do not bring benefits for other ecosystems.

**Comment by hugovk** [comment]
Certainly not all ecosystems, but for some major ones.

Compare the config for Python's pip with Travis CI:

```yml
cache: pip
```

With GitHub Actions:

```yml
      - name: Ubuntu cache
        uses: actions/cache@v1
        if: startsWith(matrix.os, 'ubuntu')
        with:
          path: ~/.cache/pip
          key:
            ${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('**/setup.py')
            }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.python-version }}-

      - name: macOS cache
        uses: actions/cache@v1
        if: startsWith(matrix.os, 'macOS')
        with:
          path: ~/Library/Caches/pip
          key:
            ${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('**/setup.py')
            }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.python-version }}-

      - name: Windows cache
        uses: actions/cache@v1
        if: startsWith(matrix.os, 'windows')
        with:
          path: ~\AppData\Local\pip\Cache
          key:
            ${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('**/setup.py')
            }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.python-version }}-
```

10 characters vs. 1,000 characters!

I know which I'm be more confident using, and prefer suggesting for projects to add :) 

Travis also has shortcuts like:

```yml
cache: bundler   # Ruby
cache: cocoapods # Objective-C
cache: npm       # npm
cache: yarn      # yarn
cache: ccache    # C or other C/C++ variants 
cache: packages  # R
cache: cargo     # Rust

The flexibility of GHA's caching is good, but it would be even better to have some user-friendly shortcuts. Thanks!
