### ISSUE TITLE
actions/cache@v4 - Error - sometime running into "hashFiles('**/pom.xml') couldn't finish within 120 seconds"

### ISSUE THREAD

**Issue by svaraksin-gd** [actions/cache#1603]
Hello team. Would appreciate if you take a look and provide some insights, suggestions or even a fix for the following:

Context: We have about 130 workflows that can run simultaneously. Each workflow might include several parallel jobs.

Issue: time to time we are running into the following issue during the Post Job step of this action (the error does not occur in all jobs, but only in some and randomly): 
```
Post job cleanup.
Error: The template is not valid. ***/cicd-shared-actions/main/.github/actions/run-maven/action.yml (Line: 60, Col: 14): hashFiles('**/pom.xml') couldn't finish within 120 seconds.
Post job cleanup.
```
main/.github/actions/run-maven/action.yml (Line: 60, Col: 14):
```
    - name: Cache Maven repository
      if: runner.os == 'Linux' && inputs.maven-cache == 'true'
      uses: actions/cache@v4
      with:
        enableCrossOsArchive: true
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
```

What might be a problem here? Thanks in advance
