### ISSUE TITLE
Cache miss for existing cache

### ISSUE THREAD

**Issue by afrazkhan** [actions/cache#1606]
I'm getting constant cache misses for caches I can see in the interface.

My cache save step in workflow (a):

```
      - name: Save Slack thread to cache
        uses: actions/cache/save@v4
        id: slack-thread-id
        with:
          path: /tmp/slack_thread_id
          key: slack-thread-id-${{ github.event.pull_request.number }}
```

My cache restore step in workflow (b):

```
      - name: Restore Slack thread ID
        uses: actions/cache/restore@v4
        id: slack-thread-id
        with:
          fail-on-cache-miss: true
          path: /tmp/slack_thread_id
          key: slack-thread-id-${{ github.event.issue.number }}
```

Both steps report the same key (e.g. `slack-thread-id-16`), and I can see that cache in the GH web interface. However, I still get `Error: Failed to restore cache entry. Exiting as fail-on-cache-miss is set. Input key: slack-thread-id-16`.
