### ISSUE TITLE
Random issue with cache/restore

### ISSUE THREAD

**Issue by cdupuis** [actions/cache#1621]
Starting this morning we are experiencing random failures to restore caches successfully. Nothing has changed in our setup and the cache exists. Other builds in the same matrix can successfully restore the same cache. 

We see the following logs:

```
Run actions/cache/restore@d4323d4df104b026a6aa633fdb11d772146be0bf
Cache hit for: clamav-db
Warning: Failed to restore: 
Cache not found for input keys: clamav-db
```

**Comment by malteschlueter** [comment]
We've been experiencing the same problem since this morning.

**Comment by joni-luhtalampi** [comment]
We are also experiencing `Cache not found for input keys:  xxx` 

```bash
Run actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
Cache not found for input keys: Linux-xxxxx

```

**Comment by chafilin** [comment]
We also have problems with 
```
Run actions/cache@v4
Cache not found for input keys: ***
```

**Comment by ggravlingen** [comment]
In addition to the above, we also see that caches randomly appear and disappear when loading the cache page.

**Comment by kemuridama** [comment]
We've also the same issue. A cache key had been found, but restoring cache failed.

**Comment by cstamas** [comment]
Same here

**Comment by robertragas** [comment]
Same

**Comment by igsilya** [comment]
Same here.  Have this issue randomly appear for a couple days.  A fresh example: https://github.com/igsilya/ovs/actions/runs/15729207871/job/44326130187#step:7:31

**Comment by cometkim** [comment]
`actions/cache/save` is also failing

**Comment by VEBERArnaud** [comment]
We’re also experiencing this issue.

I’ve noticed that on the page listing the caches, refreshing it multiple times sometimes loads an outdated version of the page — this can be seen in the total cache count, which occasionally appears incorrect.

**Comment by afc163** [comment]
We run into same issue: https://github.com/ant-design/ant-design/actions/runs/15728566227/job/44324375004?pr=54106

**Comment by catalingmn** [comment]
similar issue here, cache hit/miss unreliable

**Comment by igsilya** [comment]
Looking at the official readme: https://github.com/actions/cache/blob/main/README.md?plain=1#L348 it suggests to open support tickets for high priority issues.  I opened one for myself, but if anyone here has enterprise support and can report an issue via https://support.github.com/contact/bug-report that might be helpful :) as they normally take a few weeks to respond to personal tickets.

**Comment by tcnijmeijer** [comment]
We're experiencing the same issue at our organization. I followed @igsilya's  suggestion to open a support ticket.

**Comment by czioutas** [comment]
same

**Comment by seanmcguigan** [comment]
Same

**Comment by ArtemGoutsoul** [comment]
Related discussion: https://github.com/orgs/community/discussions/163260

unfortunately no update on https://www.githubstatus.com/

**Comment by v-zamora** [comment]
It's still an issue in our organization

**Comment by threeal** [comment]
It seems the main issue come from the `GetCacheEntryDownloadURL` method, because it always response randomly between the download URL found and not. The other method seems working properly.

**Comment by edmorley** [comment]
At the very least, if there is an underlying cache service issue, this action should show that error (eg some HTTP 500 or whatever) in the build logs to make this easier to diagnose than the current:

```
Run actions/cache/restore@v4
Error: Failed to restore cache entry. Exiting as fail-on-cache-miss is set. Input key: 15733381039-builder-24-amd64
```

**Comment by ArtemGoutsoul** [comment]
It would also be important that github would update https://www.githubstatus.com/ , since so many developers are spending hours on diagnosing the issue :(

> At the very least, if there is an underlying cache service issue, this action should show that error (eg some HTTP 500 or whatever) in the build logs to make this easier to diagnose than the current:
> 
> ```
> Run actions/cache/restore@v4
> Error: Failed to restore cache entry. Exiting as fail-on-cache-miss is set. Input key: 15733381039-builder-24-amd64
> ```

**Comment by crewtaylorfd** [comment]
See it as well

**Comment by bsda** [comment]
same here

**Comment by catalingmn** [comment]
> Looking at the official readme: https://github.com/actions/cache/blob/main/README.md?plain=1#L348 it suggests to open support tickets for high priority issues. I opened one for myself, but if anyone here has enterprise support and can report an issue via https://support.github.com/contact/bug-report that might be helpful :) as they normally take a few weeks to respond to personal tickets.

I've opened a ticket as well. Maybe if more of us contacts them, they will do something about it ... or at least update the status page

**Comment by RuBiCK** [comment]
Same issue here. Some jobs can retrieve the cache while others fail.

**Comment by sobolk** [comment]
Same here.

**Comment by erihanse** [comment]
Using `gh cache list --key=<...>` I sometimes get a response, sometimes get `No caches found in xxx/yyy`. I don't think the issue lies with this action.

**Comment by NickMainAtPI** [comment]
We are also experiencing completely random cache misses on existing cache entries.

**Comment by ahsanrao-hh** [comment]
Has anyone found a fix or temporary solution for this problem yet? Thanks.

**Comment by dkoston** [comment]
> Has anyone found a fix or temporary solution for this problem yet? Thanks.

@ahsanrao-hh it fails randomly so you need to keep re-running failed actions until they pass

**Comment by miningape** [comment]
We're also seeing this issue. It seems to work intermittently, some of our jobs will succeed while others with the same cache key will fail.

Logs:
```
Run actions/cache/restore@v4
  with:
    path: ./node_modules/
    key: Linux-deps-*****
    enableCrossOsArchive: false
    fail-on-cache-miss: false
    lookup-only: false
Cache not found for input keys: Linux-deps-*****
```

CI.yaml
```yaml
jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Save dependencies cache
        uses: actions/cache@v4
        with:
          path: ./node_modules/
          key: ${{ runner.os }}-deps-${{ hashFiles('**/yarn.lock', '**/prisma/schema/*.prisma') }}
      - name: Install modules
        run: yarn --frozen-lockfile

  format-and-lint:
    needs: install
    name: Lint and Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore dependencies cache
        uses: actions/cache/restore@v4
        with:
          path: ./node_modules/
          key: ${{ runner.os }}-deps-${{ hashFiles('**/yarn.lock', '**/prisma/schema/*.prisma') }}
```

**Comment by igsilya** [comment]
```
 Update - The actions cache service is experiencing degradation in a number of regions causing cache misses when attempting to download cache entries. This is not causing workflow failures, but workflow runtime might be elevated for certain runs.
Jun 18, 2025 - 16:46 UTC 
```
"This is not causing workflow failures" :D

**Comment by Link-** [comment]
@VEBERArnaud - the APIs are still impacted and will take longer to mitigate. The priority is for workflow runs right now, validation should be done in actual actions workflow runs.

**Comment by VEBERArnaud** [comment]
Thanks for the info! I’ll try running one of our workflows and let you know how it goes.

**Comment by marcodicro-dp** [comment]
@Link- still impacted here, with `Failed to restore` warning:

![Image](https://github.com/user-attachments/assets/d5ec8e77-eab0-4c53-97d4-f71276c79398)

**Comment by yacaovsnc** [comment]
@marcodicro-dp2 could you please give us the workflow run url so we can take a look?

**Comment by VEBERArnaud** [comment]
Still experiencing the issue here as well.

Unfortunately, I can't share the run URL since it's a private repo.

<img width="1113" alt="Image" src="https://github.com/user-attachments/assets/3d53ee76-fccb-4a20-9c38-9efb4056e4de" />

**Comment by yacaovsnc** [comment]
@VEBERArnaud we don't need access to your repo, we just need some identifier so we can search in our log.

**Comment by kaovilai** [comment]
https://github.com/vmware-tanzu/velero/actions/workflows/e2e-test-kind.yaml are recovering well.

**Comment by NAlexPear** [comment]
Private repo also, but we are continuing to see cache reads succeed in early jobs while failing in subsequent jobs. Example run [here](https://github.com/flexbase-eng/platform/actions/runs/15741086990).

**Comment by yacaovsnc** [comment]
@VEBERArnaud @NAlexPear how are those cache created?  I am seeing a different issue from logs.  Are caches created with `actions/cache@v4`?

**Comment by nrgbistro** [comment]
Still getting this issue as well, this is completely breaking our CI pipeline: https://github.com/Torq-Interface/torq-transport/actions/runs/15742024739/job/44369768719

**Comment by cfeenstra67** [comment]
Wanted to note a couple of things about our experience:
- We first saw this issue around 1PM PST yesterday (example: https://github.com/goanzen/anzen-platform/actions/runs/15716993794/job/44289122117). So ~20 hours before any indication on the status page
- As someone else noted, this message is simply not correct:
> The actions cache service is experiencing degradation in a number of regions causing cache misses when attempting to download cache entries. This is not causing workflow failures, but workflow runtime might be elevated for certain runs.

Any workflow that uses `fail-on-cache-miss: true` will have the potential to fail due to this

**Comment by VEBERArnaud** [comment]
Just to share a possible lead in case it helps:

I wonder if the inconsistent behavior could be due to cache state not being fully synchronized across all backend servers or edge locations. It seems like the API might return different results depending on which server handles the request.

Of course, this is just a hypothesis based on what I’ve observed — I’m sharing it in case it’s useful for further investigation.

Thanks again for looking into this!

**Comment by VEBERArnaud** [comment]
The cache is created in a previous step within the same workflow, so it should be fresh and immediately available for the following steps. There shouldn’t be any delay or propagation issue in that case.

Also, I deleted all existing caches just before re-running the workflow, to make sure no stale data could interfere.

What’s particularly odd is that the cache listing API seems to alternate between two distinct states: one where the data is up-to-date and shows the freshly created cache, and another where the data appears outdated — showing entries that are over 20 hours old. This gives the impression that responses may come from different backend servers that aren’t fully synchronized.

Hope this helps narrow things down!

**Comment by NAlexPear** [comment]
@VEBERArnaud that failing cache was indeed created more than 20 hours ago. But it's intermittently accessible during frequent runs today.

**Comment by yacaovsnc** [comment]
@NAlexPear We have just rollout a mitigation and the APIs should also work now.

**Comment by VEBERArnaud** [comment]
I’m still having the issue.
Here’s a screenshot of the save step, then one of the restore step.
The third one shows that the cache actually exists in the GitHub cache list.

Here is the run: https://github.com/EurosportDigital/infinity-cms-2/actions/runs/15729009324/job/44388763054

<img width="1142" alt="Image" src="https://github.com/user-attachments/assets/9b894ebf-6165-4810-a74f-3d2bd3afb096" />
<img width="1136" alt="Image" src="https://github.com/user-attachments/assets/2d892af7-919f-4ce5-8f98-d966e4b64c83" />
<img width="1137" alt="Image" src="https://github.com/user-attachments/assets/7676ffa2-3f34-4beb-a9a7-910c9456373d" />

**Comment by VEBERArnaud** [comment]
I ran a few more tests, and it seems the save issue might be related to a combination of the cache key and the ref.

When trying to save a cache with the key `pr-node18-deps-backend-b4c28800f28ceff02bbb77626370eeb154cf6a164331c6ebdeeb77d3ca82997b` for the ref `refs/pull/10037/merge`, I consistently get the error:
(run: https://github.com/EurosportDigital/infinity-cms-2/actions/runs/15750041645)
```
Failed to save: Unable to reserve cache with key pr-node18-deps-backend-b4c28800f28ceff02bbb77626370eeb154cf6a164331c6ebdeeb77d3ca82997b, another job may be creating this cache.
```

However, using the exact same cache key on another run, but for a different ref `refs/pull/10107/merge`, it works as expected:
(run: https://github.com/EurosportDigital/infinity-cms-2/actions/runs/15749747116)
```
Cache saved with key: pr-node18-deps-frontend-799a5ae2534aeb67d1ae7d148517c717c0357559752744e34d0b01fcb5271a4c
```

The main difference I can see is that the ref causing the issue was created yesterday, while the working one was created about an hour ago.

I also reproduced a working case with a fresh PR ref created a few minutes ago.

So far, I’ve never been able to get it working on a PR ref older than ~10 hours.

As a workaround, I could recreate all existing PRs to get fresh refs. That would be time-consuming, but doable.
However, I’m also seeing this issue on workflows that are not triggered by PRs, so this wouldn’t cover all cases.

**Comment by mbtools** [comment]
It's working properly again. Thanks everyone! 🙏

**Comment by VEBERArnaud** [comment]
It’s still not working on my end.

I’m giving up on this for now and will update all cache keys to unblock our situation.

**Comment by NAlexPear** [comment]
Removing the offending caches (older than ~20 hrs/pre-incident) appears to have solved the issue of inconsistent reads across jobs for us now that the `gh` CLI is able to remove them!

We're still intermittently facing the same issue as @VEBERArnaud around reserving _new_ cache keys on certain refs (a [link](https://github.com/flexbase-eng/platform/actions/runs/15756478077/job/44412959130#step:17:3) for Microsoft/Github employees looking to see this issue in the logs). We can do more testing later, but for now we have a fallback for when that cache misses, so it's no longer a hard blocker for us.

**Comment by yacaovsnc** [comment]
Thanks for the reports.  If you are experiencing problem with caches that are first created in the last couple days, please use a new key to start fresh.

**Comment by yacaovsnc** [comment]
@NAlexPear for the [linked](https://github.com/flexbase-eng/platform/actions/runs/15756478077/job/44412959130#step:17:3) job, the error log I see is:
```
already_exists: cache entry with the same key, version, and scope already exists
```

and then it proceed to download the cache, but cache doesn't exist.  This is consistent with the what we were seeing in this incident.  Is that job for a PR?  Does the cache exist on the PR branch or `main` branch?  It's best to delete this cache from both branches if it exists, and workflow should work then.

**Comment by NAlexPear** [comment]
@yacaovsnc here's [another example of a cache read succeeding and failing on a brand-new PR](https://github.com/flexbase-eng/platform/actions/runs/15778638530/job/44478733847?pr=3497), even after removing the offending cache from `main` (and that cache does *not* exist for this PR, as checked with `gh cache list --ref refs/pull/3497/merge`).

**Comment by yacaovsnc** [comment]
@NAlexPear would it be possible to use a new cache key instead?  This way we are certain there will be no dangling references around.

**Comment by wakaztahir** [comment]
I am getting cache not found, even though the cache is present, BTW the cache was created in the same branch, same tag and same release, however the workflow did fail, But I manually use cache/save and cache/restore like this

```yml
      # split cache into restore + save
      - name: Restore cache for chemical-bootstrap/out-win
        id: bootstrap-cache-restore
        uses: actions/cache/restore@v4
        with:
          path: ./chemical-bootstrap/out-win/
          key: ${{ runner.os }}-${{ steps.get-sha.outputs.sha }}

      # Build the chemical-bootstrap project (only if not cached)
      - name: Build chemical-bootstrap (Windows)
        working-directory: chemical-bootstrap
        run: .\build.bat native-windows-gnu native
        if: steps.bootstrap-cache-restore.outputs.cache-hit != 'true'

      # Save the out-win folder as cache
      - name: Save cache for chemical-bootstrap/out-win
        if: steps.bootstrap-cache-restore.outputs.cache-hit != 'true' && success()
        id: bootstrap-cache-save
        uses: actions/cache/save@v4
        with:
          path: chemical-bootstrap/out-win/
          key: ${{ runner.os }}-${{ steps.get-sha.outputs.sha }}
```
