### ISSUE TITLE
Calculate a default key

### ISSUE THREAD

**Issue by hugovk** [actions/cache#17]
Care must be taken to figure out a `key:` name, so it doesn't collide with another one and, for example, fetch an incompatible cache for another OS or Python version.

A `key` is not something I've had to worry about with Travis CI:

> There is one cache per branch and language version/ compiler version/ JDK version/ Gemfile location/ etc.

If the `key` is omitted, how about calculating one from the branch, workflow name and matrix values (and anything else relevant)?

For example, given this workflow:

```yml
name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7"]
        os: [ubuntu-latest, ubuntu-16.04, macOS-latest]
```

Perhaps it would generate something like `Test__master__ubuntu-latest__3.6`.

As a user, I don't really care, I'd just like the same cache to be fetched when rebuilding the same sort of thing.
