### ISSUE TITLE
Error installing actions/cache@v1.1.2

### ISSUE THREAD

**Issue by TerensTare** [actions/cache#182]
I am having trouble installing actions/cache@v1.1.2 on windows, linux and macosx.

My workflow file:
``` YAML
name: CI

on: [push]

jobs:
  get-dependencies:
    name: ${{ matrix.os }}-dependencies
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            compiler: cl.exe
            build: /EHsc /std:c++latest /O2 /W4 /Iinclude main.cpp src\*.cpp /FeTnT.exe /Fo.\obj\ /link /subsystem:console /machine:x64
            vcpkg-path: C:\\vcpkg\\installed\\x64-windows
            triplet: x64-windows
            separator: \\
          - os: ubuntu-latest
            compiler: gcc
            vcpkg-path: /usr/local/share/vcpkg/installed/x64-linux
            separator: /
            triplet: x64-linux
          - os: macos-latest
            compiler: clang 
            vcpkg-path: sth
            separator: /
            triplet: x64-osx

            
    steps:
      - name: Run vcpkg
        env:
          VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
        run: vcpkg install fmt sol2 nlohmann-json sdl2 sdl2-image sdl2-mixer sdl2-ttf sdl2-net
      - name: Linux find vcpkg
        run: ${{ matrix.find }}
      - name: Cache packages
        uses: actions/cache@v1.1.2
        with:
         path: ${{ matrix.vcpkg-path }}
      - name: Integrate packages
        run: vcpkg integrate install

    
  tnt:
    runs-on: [windows-latest]
    needs: [get-dependencies]
    name: Build TnT
    steps:
      - uses: actions/checkout@v1
      - name: Build TnT.exe
        run: |
          dir
          mkdir obj
          cl /EHsc /std:c++latest /O2 /W4 /Iinclude main.cpp src\*.cpp /FeTnT.exe /Fo.\obj\ /link /subsystem:console /machine:x64
```

What I am getting when running the workflow (same for the three OS-es):
![image](https://user-images.githubusercontent.com/37905314/74107528-64a2cd00-4b71-11ea-838a-daa8fc3ebe7a.png)
