### ISSUE TITLE
how to cache vcpkg installed?

### ISSUE THREAD

**Issue by shinny-jipeng** [actions/cache#186]
Thank you 🙇‍♀ for wanting to create an issue in this repository. Before you do, please ensure you are filing the issue in the right place. Issues should only be opened on if the issue **relates to code in this repository**.

* If you have found a security issue [please submit it here](https://hackerone.com/github)
* If you have questions about writing workflows or action files, then please [visit the GitHub Community Forum's Actions Board](https://github.community/t5/GitHub-Actions/bd-p/actions)
* If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/articles/about-github-actions#contacting-support)

If your issue is relevant to this repository, please delete this text and continue to create this issue. Thank you in advance.

**Comment by bsergean** [comment]
I would love to get vcpkg installed deps to be cached. It takes forever to build OpenSSL for example, and I'd love to not do this every time I build.

**Comment by aminya** [comment]
Can't we use something like this:
```yaml
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/vcpkg
          ./build/vcpkg_installed
        key: ${{ runner.os }}-${{ env.BUILD_TYPE }}-${{ hashFiles('**/CMakeLists.txt') }}-${{ hashFiles('./vcpkg.json')}}
        restore-keys: |
          ${{ runner.os }}-${{ env.BUILD_TYPE }}
```

Assuming vcpkg is installed in `~/vcpkg`.
