### ISSUE TITLE
cache-hit returns 'true' or '' instead of the 'true' or 'false'

### ISSUE THREAD

**Issue by boumenot** [actions/cache#193]
This action has greatly sped up my CI pipeline - thank you.

I *think* I hit a **minor** issue with this action regarding the variable ```steps.cachr.outputs.cache-hit```.  The documentation says it is a Boolean, but I found that I can only compare the value against ```true```.  The false value is simply the empty string.  Is this expected?

```yaml
      - name: cache-hit output
        run: |
          echo "-->${{ steps.my-cache.outputs.cache-hit }}<--"
```

The true case yields.

```text
-->true<--
```

The false case yields

```text
--><--
```

I was expecting ```-->false<--```.  

Interestingly, I started with the solution from the docs, and everything worked great.  I tried to expand the solution to support multiple paths based on this [comment](https://github.com/actions/cache/issues/143#issuecomment-580419911), and it stopped working as expected.  I had changed the comparison to ```== false``` instead of ```!= true```, and I could not figure out why it did not work.  The fix is easy, but I was expecting false not ''.
