### ISSUE TITLE
Caching problem - unpacking tar

### ISSUE THREAD

**Issue by mikart143** [actions/cache#198]
Hello !
I found error as shown in #133 
I tried to fix this by using windows as system.
Cache was made but the new error occured.

> Run actions/cache@v1
Cache Size: ~102 MB (107455822 B)
C:\windows\System32\tar.exe -xz -f d:\a\_temp\5bff5da6-b2e7-439a-9f1e-b8eb52fb391e\cache.tgz -C C:\Users\runneradmin\.cargo\registry
./index/github.com-1ecc6299db9ec823/.git/objects/pack/pack-a1b8e2d02676504008fea86ca360367fcee5bd43.idx: Can't unlink already-existing object
./index/github.com-1ecc6299db9ec823/.git/objects/pack/pack-a1b8e2d02676504008fea86ca360367fcee5bd43.pack: Can't unlink already-existing object
tar.exe: Error exit delayed from previous errors.
[warning]Tar failed with error: The process 'C:\windows\System32\tar.exe' failed with exit code 1. Ensure BSD tar is installed and on the PATH.

I am trying to cache cargo. I am using code from Action examples

**Comment by dhadka** [comment]
Hi @mikart143, could you please provide your full workflow file?  The error `Can't unlink already-existing object` seems to indicate those files in the cargo `registry` already exist and the action does not have permission to delete them.  Is cargo creating / populating the `registry` before the cache restore step is performed?

**Comment by mikart143** [comment]
It occure on security_audit job

```
name: Rust

on: 
  push:
   branches:
       - master

jobs:
  security_audit:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      # - uses: EmbarkStudios/cargo-deny-action@v0
      
  test:
    needs: [security_audit]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable]

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Run tests
      run: cargo test --lib --verbose 
  docs:
    needs: [security_audit, test]
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2
    - name: Generating Docs
      run: |
        cargo doc --no-deps
        mv target/doc docs
        echo '<meta http-equiv="refresh" content="0; url=syncer/index.html">' > docs/index.html
  build:
    needs: [security_audit, test]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
```
