### ISSUE TITLE
Cache service responded with 503 during chunk upload

### ISSUE THREAD

**Issue by samkit-jain** [actions/cache#200]
Getting
```
Post job cleanup.
/bin/tar -cz -f /home/runner/work/_temp/7a3639e6-8bde-4320-b0e3-28editedc25e/cache.tgz -C /home/runner/.cache/pip .
[warning]Cache service responded with 503 during chunk upload.
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: EBADF: bad file descriptor, read
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:167:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5) {
  errno: -9,
  code: 'EBADF',
  syscall: 'read'
}
```

The GitHub action looks like
```
      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
```

Dependencies include PyTorch.
