### ISSUE TITLE
Cache is hit but "bundle install" still try to install all dependency instead of just using them

### ISSUE THREAD

**Issue by onevcat** [actions/cache#201]
I followed the example here to use `cache` in my action: https://github.com/actions/cache/blob/master/examples.md#ruby---bundler

```yaml
- uses: actions/cache@v1
with:
    path: vendor/bundle
    key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
    restore-keys: |
    ${{ runner.os }}-gems-
- name: Bundle install
run: |
    bundle config path vendor/bundle
    bundle install --job
```

However, although the cache is hit and restored to `vendor/bundle`, it seems that the required gems are still being installed. It slows down the CI and wastes a lot of resource. Here is the screenshot of the result, you can see `bundle install` installs the gems instead of just using them. 

<img width="934" alt="截屏2020-02-2722 29 40" src="https://user-images.githubusercontent.com/1019875/75449960-4c281480-59b1-11ea-8d87-9d4e55606ded.png">

The final `Post actions/cache@v1` reports the "Cache hit occurred".

Here is an example job result: https://github.com/onevcat/Kingfisher/pull/1396/checks?check_run_id=472401799

Any suggestions would be helpful! Thank you.

**Comment by mattt** [comment]
@onevcat Have you tried conditionalizing the bundle install step?

```yaml
- uses: actions/cache@v1
  id: bundler-cache
  with:
    path: vendor/bundle
    key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
    restore-keys: |
      ${{ runner.os }}-gems-
- name: Bundle install
  if: steps.bundler-cache.outputs.cache-hit != 'true'
  run: |
    bundle config path vendor/bundle
    bundle install --job
```

**Comment by onevcat** [comment]
@mattt Thank you. Good idea! I will try it.

In fact, the `cache` action works sometimes, even for the same cache key:

Success case: https://github.com/onevcat/Kingfisher/runs/488869840?check_suite_focus=true
Failure case: https://github.com/onevcat/Kingfisher/runs/472663143?check_suite_focus=true

Both were restored from the same key, but have different behavior on `bundle install`. It confuses me a bit.

Anyway, I will add the condition checking to the install step and watch the result.

**Comment by onevcat** [comment]
Umm, setting a condition does not work. It gives a "Bundler::GemNotFound: Could not find minitest-5.14.0 in any of the sources" error now. It seems that the restored gems are not recognized at all. (Here is a [sample error build](https://github.com/onevcat/Kingfisher/pull/1403/checks?check_run_id=493290668) for this case.) 

Maybe it is related to the ruby (and gem) version? I am using `rbenv` on my local machine to manage ruby versions, and have a `.ruby-version` in the project root. I will try to dig it deeper to see how it affects.

**Comment by onevcat** [comment]
Oh, it turned out to be my fault. I also skipped the bundle path setting. I have to split `bundle config` and `bundle install` to two steps to make it work. (Of course!)

The following steps work fine for now. I will keep an eye on it to see whether any unexpected behavior happens again. 

```
steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        id: bundler-cache
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle setup
        run: bundle config path vendor/bundle
      - name: Bundle install
        if: steps.bundler-cache.outputs.cache-hit != 'true'
        run: bundle install --jobs 4 --retry 3
      # More steps
```
