### ISSUE TITLE
Fix performance issues when caching maven repository

### ISSUE THREAD

**Issue by jactor-rises** [actions/cache#204]
There are huge performance issues with the caching mechanism of maven repositories

In the middle of the day, when building a maven artefact, to fetch the cache when my actions run can take from 2-3 minutes (!)

Then my maven build is done in 20-30 seconds...

After my build, then It takes approx one and a half minute before the cache is saved... 

When the performance of the caching of the repository is so bad, it is better to run without caching (!). This is a serious setback in performance when developing and it is difficult to deliver code to our production environments in a quick manner.

I am sorry not to provide any examples, but my repositories are private belonging to https://github.com/navikt. A typical cache configuration looks like this:
```
      - uses: actions/cache@v1.1.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
```
