### ISSUE TITLE
Github action is stuck when trying to restore the cache

### ISSUE THREAD

**Issue by berkos** [actions/cache#207]
👋 
It seems I have encountered an issue while trying to restore the cache on Github actions. (Sorry I cannot post the repo as is a private one).

Here is some of the cache setup and a screenshot of the action stuck on cache restore.

```yml
with:
  path: ./vendor/bundle
  key: v1-bundle-${{ runner.OS }}-${{ hashFiles('.github/workflows/main.yml') }}-gemfile-${{ hashFiles('Gemfile.lock') }}
  restore-keys: |
    v1-bundle-${{ runner.OS }}-${{ hashFiles('.github/workflows/main.yml') }}-gemfile-${{ hashFiles('Gemfile.lock') }}
    v1-bundle-${{ runner.OS }}-${{ hashFiles('.github/workflows/main.yml') }}-
    v1-bundle-${{ runner.OS }}-
```

<img width="2663" alt="Screenshot 2020-03-05 at 15 42 29" src="https://user-images.githubusercontent.com/1176797/76086367-dec94480-5fab-11ea-9097-15209737529f.png">

As it appears in the screenshot I had to stop the action after 15mins.
I can see from some data points that the cache restore usually fluctuates between  **5sec - 1min** and the cache size:  is around  **150 MB** .

I hope the above are helpful. 🙏
