### ISSUE TITLE
Cache fails for Pull Request re-runs with "No scopes with read permission were found on the request."

### ISSUE THREAD

**Issue by jcornaz** [actions/cache#208]
In pull requests we often get:

```
[warning]No scopes with read permission were found on the request.
```

And the build runs without cache.

Please note that I'm talking about *pull request* build triggered when *pushing* a commit (or opening the PR). So this issue is *not* explained by #129.

**Comment by joshmgross** [comment]
Can you provide an example of when this occurs?
Do you see it on the first PR run, or when re-running a PR?

**Comment by jcornaz** [comment]
> Can you provide an example of when this occurs?

Not really sorry. I am not allowed to share that sources. I'll do my best to create a simple reproducer.

> Do you see it on the first PR run, or when re-running a PR?

If I look at the latest occurrence of the problem, it was when pushing a new commit to a PR already built.

**Comment by jcornaz** [comment]
In the hope it helps, here is more information:

*We configured `action/checkout` to build the `HEAD` of the PR branch (not the merge commit).
```yaml
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
```

* Here is how we configure the workflow to run on build requests:
```
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
```

* The workflow is composed of multiple jobs, all using the same cache key.
  * One *initial* job. runs alone
  * The next jobs run all in parallel and use `matrix` strategies. That causes ~ 20 concurrent fetches of the same cache.

**Comment by bxq2011hust** [comment]
I have the same problem.
Sometimes a pr runs without cache and GitHub Action output.

```bash
[warning]No scopes with read permission were found on the request.
```

Today I meet the problem after I cancel and rerun. Here is the link
https://github.com/FISCO-BCOS/FISCO-BCOS/pull/1402/checks?check_run_id=493039648

```bash
 Run actions/cache@v1 0s
[warning]No scopes with read permission were found on the request.
Run actions/cache@v1
[warning]No scopes with read permission were found on the request.
  Run actions/cache@v1 1s
[warning]No scopes with read permission were found on the request.
Run actions/cache@v1
[warning]No scopes with read permission were found on the request.
```

**Comment by joshmgross** [comment]
@bxq2011hust Thanks! I believe there's a bug that re-running a PR will use a different ref (https://github.community/t5/GitHub-Actions/GITHUB-REF-is-inconsistent/td-p/48129). This fails our validation as we currently only allow caching on PRs that use `refs/pulls/*` type refs.

@jcornaz can you confirm if all of these cache failures were from re-running a failed PR?

**Comment by Raul6469** [comment]
Hi! I do have the same error message, however it also happens sometimes when I run a workflow for the first time, not necessarily after a re-run. Unfortunately, it looks like this issue happens quite randomly...

**Comment by joshmgross** [comment]
@Raul6469 could you provide a workflow file or an example run where this occurs?

**Comment by Raul6469** [comment]
I cannot give a link to a run since it's from a private repo, but here is one of the four jobs of the workflow. When the cache issue happens, it happens for all jobs of the workflow. Workflow is triggered on `pull_request` events. 

And after some thought, I'm not 100% sure that the issue happened without a rerun 🤔 I'll let you know if it happens again

```yml
  lint:
    name: 'Lint'

    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 8
      uses: actions/setup-node@v1
      with:
        node-version: 8

    - name: Cache npm
      id: node_modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          node-

    - name: Install dependencies
      run: npm i

    - name: Run linter
      run: npm run lint -- --quiet
```
