### ISSUE TITLE
Make Cache Key Optional?

### ISSUE THREAD

**Issue by danrbailey** [actions/cache#210]
Is it possible to make the key optional and hence make the cache action read-only? This is in the case that you know that you only want to read from one of the "restore" keys and to fail if you can't find one. 

For clarity, look for restore key patterns only: 

On cache hit - read the cache, don't attempt to write a new one.
On cache miss - job fail.

An alternative could be to recognize a specific string as the key which means _skip_ the write on job completion:

```
      uses: actions/cache@v1
      with:
        path: cache
        key: donotwrite
        restore-keys: myexpectedcache-
```

**Comment by luigi311** [comment]
This would be nice. I have a use case where on job 1 I download a file off a server and then create a cache of said file with the key file-${{ hashFile(file) }}, on job 2 I need to do a restore on that exact key but the file does not exist in job 2 and I don't want to download the file every single time so I want to call a cache restore with the restore key of file- so it does a partial match and restores the lastest key. The problem with the current implementation is I need to generate a bogus unique key for every single run so I don't get a cache hit and restore a version that might not be valid but then I'm storing the same file over and over with all the bogus keys.

**Comment by luigi311** [comment]
Preferred syntax would be 
```yml
- name: Restore file
  uses: actions/cache@v2
  with:
    path: file
    restore_keys: file-
```

**Comment by MartijnHols** [comment]
You can achieve this using my fork https://github.com/MartijnHols/actions-cache:

```yaml
name: Build app

on: push

jobs:
  build:
    needs: [install]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Restore "node_modules" from cache
      uses: martijnhols/actions-cache/restore@main
      with:
        path: node_modules
        # key is a required field, by providing a dummy value we pass validation while it won't match a cache entry and therefore be ignored
        key: dummykey
        restore-keys: myexpectedcache-
        # Fail when the cache could not be found
        required: true

    - name: Build app
      run: yarn build
```
