### ISSUE TITLE
Cache missing on a different PR and post-cache doesn't execute on failure

### ISSUE THREAD

**Issue by lx223** [actions/cache#217]
Hi there, I am using GH cache actions to cache maven dependencies. Currently, I am getting two issues.

1. post-cache action doesn't execute when job fails. I think a `if: always()` would be useful here. When maven fetch or the build times out, I would like the already downloaded maven dependencies to be cached so that re-run the job would eventually succeed. Otherwise, it will always fail on re-runs.

2. I found that cache is always missing when executing on a different PR. Is that by design?

Here is my job config.

```
name: Premerge

on:
  pull_request:
    branches: 
      - master

jobs:
  build:
    name: Verify changes

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v2

    - name: Cache maven dependencies
      uses: actions/cache@v1.1.2
      with:
        path: ~/.m2/repository
        key: maven-cache
``` 

Thanks.
