### ISSUE TITLE
Tar fails on windows-latest regardless of version

### ISSUE THREAD

**Issue by dmmusil** [actions/cache#222]
I haven't had any success so far getting tar to actually create an asset to cache when using

`runs-on: windows-latest`

I've tried v1, v1.0.3, and v1.1.2 (latest at this time)

Tried v1 first

```
Post job cleanup.
C:\windows\System32\tar.exe -cz -f d:\a\_temp\303eb5bc-09b4-48c8-bd58-b6cfc46885df\cache.tgz -C C:\Users\runneradmin\AppData\Roaming\npm-cache .
tar.exe: could not chdir to 'C:\Users\runneradmin\AppData\Roaming\npm-cache'

[warning]Tar failed with error: The process 'C:\windows\System32\tar.exe' failed with exit code 1. Ensure BSD tar is installed and on the PATH.
```
 next v1.1.2 with the same error as above.

Finally, v1.0.3

```
Post job cleanup.
C:\windows\system32\tar.exe -cz --force-local -f d:/a/_temp/1a5f1f02-2e5d-4a88-aee8-964023aa24fb/cache.tgz -C C:/Users/runneradmin/AppData/Roaming/npm-cache .
tar.exe: Option --force-local is not supported
Usage:
  List:    tar.exe -tf <archive-filename>
  Extract: tar.exe -xf <archive-filename>
  Create:  tar.exe -cf <archive-filename> [filenames...]
  Help:    tar.exe --help
[warning]The process 'C:\windows\system32\tar.exe' failed with exit code 1
```

Any workaround for this?

Here's the relevant part of the action
```
  build:
    runs-on: windows-latest
    if: github.event.pull_request.draft == false
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Cache npm assets
      uses: actions/cache@v1.0.3
      with:
        path: ~\AppData\Roaming\npm-cache
        key: win-npm-${{ hashFiles('**\package-lock.json') }}
        restore-keys: |
          win-npm-
```

**Comment by dhadka** [comment]
Hi, sorry you are hitting this issue.  Try using `npm config get cache` to see the cache location.  I tried this now and it says `C:\npm\cache` is the location.  I would recommend using the following snippet for caching, as it queries the correct location:

```
- name: Get npm cache directory
  id: npm-cache
  run: |
    echo "::set-output name=dir::$(npm config get cache)"
- uses: actions/cache@v1
  with:
    path: ${{ steps.npm-cache.outputs.dir }}
    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    restore-keys: |
      ${{ runner.os }}-node-
```

I suspect the default cache location changed at some point and the example was never updated.
