### ISSUE TITLE
Avoiding frequent evictions.

### ISSUE THREAD

**Issue by Kesanov** [actions/cache#224]
Our project folder with built artifact is pretty large (1-3GB), so using a hash of dependencies as cache key results in very frequent evictions (2 branches with different dependencies are already a problem).

Solution to this problem would be not including such hash in the key at all, but then the cached files won't change, until someone manually changes the key itself.

Could it be for example possible to use the id of latest commit to master as a part of cache key? Or disable the _post cache_ action based on some condition?

I have read the official documentation, but it seems there isn't any recommended way to deal with such situation.

**Comment by joshmgross** [comment]
👋 Hey @Josef-Vonasek,

How frequently would you want to evict your cache? You could include the date in the cache key to have a scheduled refresh of the cache.

>Could it be for example possible to use the id of latest commit to master as a part of cache key?

Yeah, that would be feasible, you'd likely need to make a REST API call to get that latest commit since it's not currently in the environment.

https://github.com/actions/github-script might be useful for setting that up, let me know if you need any help.

**Comment by vlsi** [comment]
@Josef-Vonasekm, what build system are you using by the way?

I'm building a cache action that implements `layered` cache download: https://github.com/burrunan/gradle-cache-action

The idea is PR or branch-based builds take the recent cache from the default branch, and they store only the new/changed files in the cache.
At the same time, the builds of the default branch can reuse "previous" cache files as well, and they can upload new/modified files.

So far it is integrated for Gradle, however, I believe the layered approach can be adapted to other systems.

**Comment by Saviq** [comment]
Hey @Josef-Vonasek I _think_ I [have ours set up](https://github.com/canonical/multipass/actions/runs/227114149/workflow#L81L98) like you want it:

```yaml
    - name: Set up CCache
      id: setup-ccache
      run: |
        sudo apt-get install ccache
        ccache --max-size=2G
        sg lxd -c '/snap/bin/lxc profile device add default ccache disk source=${HOME}/.ccache/ path=/root/.ccache'

        # Find common base between master and HEAD to use as cache key.
        git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules origin master
        echo "::set-output name=key::$( git merge-base origin/master ${{ github.sha }} )"

    - name: CCache
      uses: actions/cache@v2
      with:
        key: ccache-${{ runner.os }}-${{ matrix.build-type }}-${{ steps.setup-ccache.outputs.key }}
        restore-keys: |
          ccache-${{ runner.os }}-${{ matrix.build-type }}-
        path: ~/.ccache/**
```

Only problem being that you need the whole history (so `fetch-depth: 0`) to be able to find the merge base.
