### ISSUE TITLE
multiple jobs: Cache not found for input keys

### ISSUE THREAD

**Issue by boredland** [actions/cache#225]
I have two jobs in the same workflow.

the first job contains this cache:
```
      - name: node_cache
        uses: actions/cache@master
        with:
          key: node_cache-${{ env.BRANCH_CLEAN }}-${{ hashFiles('**/yarn.lock') }}
          path: |
            global_node_cache
            node_modules
          restore-keys: |
            node_cache-${{ env.BRANCH_CLEAN }}-
            node_cache-dev-${{ hashFiles('**/yarn.lock') }}
            node_cache-dev-
```
the second job contains:
```
      - name: node_cache
        uses: actions/cache@master
        with:
          key: node_cache-${{ env.BRANCH_CLEAN }}-${{ hashFiles('**/yarn.lock') }}
          path: .
```

the first job logs:
```
Cache not found for input keys: node_cache-feature_parallelize_ci-cba052965100bacced0fd8f5392ce86963553d249d23ba96eb6ff4604a74b4a6, node_cache-feature_parallelize_ci-, node_cache-dev-cba052965100bacced0fd8f5392ce86963553d249d23ba96eb6ff4604a74b4a6, node_cache-dev-

...

Post job cleanup.
/bin/tar -cz -f cache.tgz -C /home/runner/work/***/*** --files-from manifest.txt
Cache saved successfully
```

the second job logs:
```
Cache not found for input keys: node_cache-feature_parallelize_ci-cba052965100bacced0fd8f5392ce86963553d249d23ba96eb6ff4604a74b4a6
```

I think its noteworthy, that the second job is run as part of a matrix strategy.
