### ISSUE TITLE
Cache files outside github workspace (bazel)

### ISSUE THREAD

**Issue by acecilia** [actions/cache#239]
Hello:

I tried to create a cache step for [bazel](https://bazel.build). Bazel keeps its cache in the path `/private/var/tmp/_bazel_<user>` (in macos) and does not have any `*.lock` file for it. I got the following:

```
    - uses: actions/cache@v1
      with:
        path: /private/var/tmp/_bazel_runner
        key: ${{ runner.os }}-${{ env.DEVELOPER_DIR }}-bazel-${{ hashFiles('/private/var/tmp/_bazel_runner/**') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.DEVELOPER_DIR }}-bazel-
```

I can see in the cache post action the following:

```
Post job cleanup.
Cache hit occurred on the primary key macOS-/Applications/Xcode_11.4.app/Contents/Developer-bazel-, not saving cache.
```

Seems to me that `${{ hashFiles('/private/var/tmp/_bazel_runner/**') }}` is not working. After investigating, it says [here](https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#hashfiles) that `The path is relative to the GITHUB_WORKSPACE directory and can only include files inside of the GITHUB_WORKSPACE`.

- Why is that?
- How can I implement this step then? Any ideas?

Thanks!
