### ISSUE TITLE
Gradle wrapper

### ISSUE THREAD

**Issue by adian** [actions/cache#244]
I think an example for Gradle: 
```yaml
- uses: actions/cache@v1
  with:
    path: ~/.gradle/caches
    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
    restore-keys: |
      ${{ runner.os }}-gradle-
```

should also have path for Gradle wrapper `~/.gradle/wrapper`:
```yaml
- uses: actions/cache@v1
  with:
    path: |
      ~/.gradle/caches
      ~/.gradle/wrapper
    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
    restore-keys: |
      ${{ runner.os }}-gradle-
```

Is there any reason to not cache wrapper? :D
