### ISSUE TITLE
Extracting multipath tar needs to respect relative paths

### ISSUE THREAD

**Issue by dhadka** [actions/cache#249]
Using for example:

```
    - uses: actions/cache@master
      with:
        path: ~/cache-folder
        key: ${{ runner.os }}-cache
```

`~` points to `/home/runner`, so the cache is creating a tar of `/home/runner/cache-folder`.

However, we are extracting relative to the `pwd` or `GITHUB_WORKSPACE` (see https://github.com/actions/cache/blob/master/src/tar.ts#L35), which is `/home/runner/work/<repo-name>/<repo-name>`.  The cache contents is extracted to `/home/runner/work/<repo-name>/<repo-name>/cache-folder`.

**Expected:** The cache folder is extracted to `~/cache-folder` or `/home/runner/cache-folder`.
