### ISSUE TITLE
Yarn missing cache issue

### ISSUE THREAD

**Issue by bartlomiejzuber** [actions/cache#253]
Hey, I've made a setup for my workflow using this guide:
https://github.com/actions/cache/blob/master/examples.md#node---yarn

Here's my workflow code: 
```
name: CI

on: [push]

jobs:
  deps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # https://classic.yarnpkg.com/en/docs/cli/cache/ yarn's cache dir depends on yarn version & os
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}

      - name: Install all deps
        run: yarn --frozen-lockfile

      - shell: bash
        run: |
          tar -czvf deps.tar.gz node_modules

      - name: Upload all dependencies
        uses: actions/upload-artifact@v1
        with:
          name: deps
          path: deps.tar.gz
  build:
    runs-on: ubuntu-latest
    needs: [deps]

    steps:
      - name: Download deps
        uses: actions/download-artifact@v1
        with:
          name: deps

      - shell: bash
        run: |
          sudo mkdir -p /node_modules && tar -czvf /node_modules deps/deps.tar.gz

      - name: Build
        run: yarn build
  test:
    runs-on: ubuntu-latest
    needs: [deps]

    steps:
      - name: Download deps
        uses: actions/download-artifact@v1
        with:
          name: deps

      - shell: bash
        run: |
          sudo mkdir -p /node_modules && tar -czvf /node_modules deps/deps.tar.gz

      - name: Test
        run: yarn test:noWatch
```

For some reason cache isn't despite the fact that on `post` step, actions warns that cache for given key already exist.

Here's how it looks like:
![image](https://user-images.githubusercontent.com/9931428/78981401-25b4d780-7b20-11ea-9588-5e9770949c13.png)

I am not sure if that's an issue or there's something wrong with my workflow yaml file.
