### ISSUE TITLE
Docker build cache mount

### ISSUE THREAD

**Issue by bhack** [actions/cache#260]
Is there a way to cache in action [`RUN --mount=type=cache`](https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/experimental.md#run---mounttypecache) when building a Dockerfile?

**Comment by chrispat** [comment]
The cache is stored ultimately in an Azure blob and then restored to a location on disk.  It seems possible that you could bind mount the cache location in your container.

**Comment by bhack** [comment]
Mhh.. How to map the cache location?
See https://stackoverflow.com/questions/60448114/how-do-i-reuse-the-cache-from-a-run-mount-type-cache-docker-build

**Comment by bhack** [comment]
The cache mount volume is https://github.com/docker/buildx/issues/255

**Comment by crazy-max** [comment]
@bhack @bhack I used the buildx cache successfully using this workflow and [ghaction-docker-buildx](https://github.com/crazy-max/ghaction-docker-buildx) action:

```yaml
name: buildx

on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v2
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Docker Buildx (build)
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x \
            --output "type=image,push=false" \
            --tag crazymax/diun:latest \
            --file ./Dockerfile-diun ./
      -
        name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
      -
        name: Docker Buildx (push)
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x \
            --output "type=image,push=true" \
            --tag crazymax/diun:latest \
            --file ./Dockerfile-diun ./
      -
        name: Docker Check Manifest
        run: |
          docker run --rm mplatform/mquery crazymax/diun:latest
      -
        name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json
```

![image](https://user-images.githubusercontent.com/1951866/83690460-507f5180-a5e0-11ea-9cd4-97232bb3704a.png)

___

![image](https://user-images.githubusercontent.com/1951866/83690527-6f7de380-a5e0-11ea-92e1-e1bbb94e5a06.png)
