### ISSUE TITLE
Post script fails when using working-directory

### ISSUE THREAD

**Issue by christeredvartsen** [actions/cache#262]
I'm currently using `working-directory` in my workflow, and it seems that the post script for `actions/cache` does not use this directory.

Given the following workflow:

```
name: Test cache from working directory
on:
  push:
    paths:
      - sub/**
defaults:
  run:
    working-directory: ./sub
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.os }}-node-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest --no-ansi
```

the post script fails with:

```
/bin/tar: /home/runner/work/testing-actions/testing-actions/vendor: Cannot open: No such file or directory
```

As you can see the `sub`-directory is not used in the post script.

Is this a bug in `actions/cache` or am I missing some configuration parameter in the workflow?
