### ISSUE TITLE
feature request: local cache store for self-hosted runners

### ISSUE THREAD

**Issue by jonathanong** [actions/cache#279]
because i, as well as many others, are having issues with the caching service, a nice feature for self-hosted runners would be to have a cache local to the self-hosted runner, perhaps configurable by the self-hosted runner.

currently for me, it's faster to not cache and just run `npm ci` than to load/save cache on self-hosted runners.

**Comment by simophin** [comment]
This will be very useful! We don't have the best connection to the backend store, it is usually faster to just download all the things again.

**Comment by joshmgross** [comment]
👋  Hey @jonathanong, could you describe your feature request a bit more?

Most tool ecosystems already have a local cache, this action's purpose is to save that local cache in a central location to share between runners. For a self-hosted runner, running workflows will naturally populate those local caches.

**Comment by patrickhulce** [comment]
I am also interested in this feature and can explain my use case @joshmgross.

I use the cache action not just for node_modules or toolchain installed deps but for expensive compilation tasks internal to our app as well. It'd be nice to not have to build out a bespoke cache system to run on the self-hosted runner and instead leverage the existing caching logic of this action to store it locally instead of having to redownload these large binaries over and over.  

example action steps we use

```yaml
     - name: Get Image CLI version
        id: image-cli-version
        run: node ./log-image-cli-version.js
      - name: Cache Image CLI
        id: cache-image-cli
        uses: actions/cache@v1.1.0
        with:
          path: built-dependencies/image-cli
          key: ${{ runner.os }}-image-cli-${{ steps.image-cli-version.outputs.version }}
      - run: bash ./compile-expensive-image-cli.sh
         if: steps.cache-image-cli.outputs.cache-hit != 'true'
```
