### ISSUE TITLE
Cache never hits

### ISSUE THREAD

**Issue by rgarrigue** [actions/cache#296]
Hi there

I'm running a molecule based Ansible role test via Tox, itself installed by pip. Hence trying to cache pip, tox and molecule. The cache never hit. To be sure I ran the job twice in a row with just a space added in the README.

First one

![image](https://user-images.githubusercontent.com/1872031/81177769-7a286700-8fa7-11ea-8c2c-ccb2720e1751.png)

Second one

![image](https://user-images.githubusercontent.com/1872031/81177886-a5ab5180-8fa7-11ea-8acc-559cf9d07dfe.png)

Here's the workflow definition 

```yaml
name: Tests

on:
  push:
    tags:
      - "*"

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7]

    steps:
      - uses: actions/checkout@v2

      - name: Setup git credentials
        uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials: ${{secrets.GIT_CREDENTIALS}}

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Cache pip
        uses: actions/cache@v1
        id: cache-pip
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Tox
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: pip install tox

      - name: Cache Tox
        uses: actions/cache@v1
        with:
          path: .tox
          key: ${{ runner.os }}-tox-${{ hashFiles('**/tox.ini') }}
          restore-keys: |
            ${{ runner.os }}-tox-

      - name: Cache Molecule
        uses: actions/cache@v1
        with:
          path: ~/.cache/molecule
          key: ${{ runner.os }}-molecule-${{ hashFiles('**/requirements.yml') }}
          restore-keys: |
            ${{ runner.os }}-molecule-

      - name: Run Tox
        run: tox
```

And the `tox.ini` which should be enough to reproduce

```
[tox]
envlist = molecule
skipsdist = true

[testenv:molecule]
deps =
  ansible-lint
  flake8
  molecule[docker]~=3.0
  netaddr
  requests
  testinfra
  yamllint
passenv =
  HOME
  SSH_AUTH_SOCK
  TERM
  TTY
commands = echo molecule {posargs:test}
```

**Comment by KZABORSKI** [comment]
Hi,

Got the very same [problem](https://github.community/t5/GitHub-Actions/Trouble-caching-python-dependencies/m-p/58888#M10696).

**Comment by crane-hiromu** [comment]
I have same problem.
can save cache but can not find it.

FIrst:
<img width="1176" alt="スクリーンショット 2020-05-21 11 56 43" src="https://user-images.githubusercontent.com/24838521/82518376-395d5000-9b5a-11ea-957e-829ae266932b.png">

Second:
<img width="1169" alt="スクリーンショット 2020-05-21 11 57 09" src="https://user-images.githubusercontent.com/24838521/82518380-3bbfaa00-9b5a-11ea-97e6-997e77d5ef67.png">

Here's the workflow definition
Minimal code for testing the cache on iOS Project.
```
name: Test CI

on:
  push:
    branches:
      - develop
    tags:
      - test.*

env:
    cache-version: v1

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1

    - name: Xcode Select version
      run: |
        sudo xcode-select -s '/Applications/Xcode.app/Contents/Developer'
        xcodebuild -version

    - uses: actions/cache@master
      with:
        path: vendor/bundle
        key: ${{env.cache-version}}-${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-

    - name: Bundle Install
      if: steps.cache-bundle.outputs.cache-hit != 'true'
      run: |
        make gem_install
        make bundle_install

```

Some projects succeed, but some projects fail.

**Comment by crane-hiromu** [comment]
Solve it by https://github.com/actions/cache/releases/tag/v2.0.0.

**Comment by nvivobume** [comment]
Any updates on this? I may be doing something very wrong, but I'm copying exactly what is on the example, and the cache never hits.

**Comment by dhadka** [comment]
👋 @nvivobume This type of behavior is typically caused by the cache scope.  Details can be found in issue https://github.com/actions/cache/issues/79 and in the [docs](https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache).  If the docs aren't clear or you still see the issue, please let me know.

@crane-hiromu Are the two screenshots from different tags?  Is the `develop` branch the default branch for your repo?  Two workflows triggered from tags won't be able to share caches (same scoping issue I mention above), but can read from caches created by your default branch.  I would suggest making sure the changes are in the default branch and a workflow is triggered from the default branch to create the cache.

**Comment by crane-hiromu** [comment]
@dhadka 
Solve it. Thanks!

**Comment by felixmosh** [comment]
> @dhadka
> Solve it. Thanks!

How?

**Comment by crane-hiromu** [comment]
> Is the develop branch the default branch for your repo? 
> can read from caches created by your default branch

#### First
exec actions your default branch (develop or master ?)
and save cache.

#### Second
exec your target branch
can restore cache.

that is all.

**Comment by rgarrigue** [comment]
Indeed, I c/ced my "tests.yml" to make a "make_cache.yml" workflow

```yaml
on:
  push:
    branches:
      - master

# same stuff as my tests.yml workflow, only the "tox" command change a bit to only install the deps
```
