### ISSUE TITLE
Python example

### ISSUE THREAD

**Issue by Sytten** [actions/cache#3]
Could you add an example for a python workspace

**Comment by hugovk** [comment]
# pip + pre-commit

Here's an example for caching two directories. Both on a single OS/Python:

```yml
name: Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v1

      - name: pip cache
        uses: actions/cache@preview
        with:
          path: ~/.cache/pip
          key: lint-${{ matrix.python-version }}-pip

      - name: pre-commit cache
        uses: actions/cache@preview
        with:
          path: ~/.cache/pre-commit
          key: lint-${{ matrix.python-version }}-pre-commit
```

You have to be careful the keys are unique between different workflows to avoid collisions!
(See also https://github.com/actions/cache/issues/17.)
