### ISSUE TITLE
Docker caching

### ISSUE THREAD

**Issue by tuler** [actions/cache#31]
Should we try to use this cache action to cache docker layers, doing trickery with `docker save` and `docker load`, or are you working on a different path for Docker caching?

**Comment by joshmgross** [comment]
You're welcome to use this for caching docker layers! If you get something figured out we can add it as an example usage of this action.

> are you working on a different path for Docker caching?

Nothing is in scope right now for `v1` of this action that's specific to the Docker scenario, but it might already work.

Related: https://github.com/actions/toolkit/issues/197

**Comment by crazy-max** [comment]
I think I can do something with [ghaction-docker-buildx](https://github.com/crazy-max/ghaction-docker-buildx) action and use the [local](https://github.com/docker/buildx#local) `--output`.

**Comment by tuler** [comment]
I tried but I hit the file limit, discussed at https://github.com/actions/cache/issues/6

**Comment by steebchen** [comment]
Since docker is now natively integrated in  Github actions, I think it would be nice if there were an option to enable docker caching globally, like CircleCI does.

**Comment by peaceiris** [comment]
@tuler tried to cache with tarball on https://github.com/actions/cache/issues/33. It seems to be a good solution.

**Comment by peter-evans** [comment]
Opened PR https://github.com/actions/cache/pull/37 with an example for Docker layer caching.

**Comment by tuler** [comment]
@steebchen I agree. Docker caching should be natively supported, not through this action.

**Comment by hamelsmu** [comment]
cc: @neovintage

**Comment by joshmgross** [comment]
The cache file limit has been increased from 400 MB to 2 GB, so this may be more viable than previously due to docker layers being larger than the previous limit.

**Comment by DannyBen** [comment]
> @steebchen I agree. Docker caching should be natively supported, not through this action.

Seems like a lot of people agree to that statement. Where is the proper place to post such a request? In the [runner repo](https://github.com/actions/runner)? Perhaps someone in the inner circle should post it as a feature request in the appropriate place and post a link here?

**Comment by joshmgross** [comment]
@DannyBen See https://github.com/actions/cache/issues/81 where we're tracking Docker caching of actions

**Comment by Sytten** [comment]
Any update of the progress?

**Comment by jimgreer** [comment]
+1

**Comment by joshmgross** [comment]
👋 Hi all, right now we are focusing on other priorities and there are no updates for docker caching. We appreciate your feedback and revisit priorities based on user feedback, so please continue sending us your input.

**Comment by steebchen** [comment]
What's bothering me most is that all Github Actions (which are based on Docker) are always rebuild from scratch, in every single action. I've never worked in projects as big as GitHub, but I can't imagine how caching is not the solution here – already for the reason that it costs bandwidth to fetch the images each time. I'd also be happy to upgrade to a more expensive plan or pay for the cache storage costs.

**Comment by crazy-max** [comment]
Working example for me using buildx here: https://github.com/actions/cache/issues/260#issuecomment-638469605

**Comment by jeacott1** [comment]
My ci processes use several pre-built docker images, some of them are very large - 3.5GB!
github actions pulls these images again and again on every run burning a lot of time and cpu.
A built in cache thats got a reasonable expiry behind each repo is really required here. Sooo much dealing with github actions seems to be spent working around paradigm/api failures or missing features.
This is a big one, please give us some better options.

**Comment by mikelax** [comment]
Hello, I am wondering if this issue has bubbled back up on the action/cache's priority list? I am wondering if there is a difficult technical challenge blocking this feature, as on its surface it seems like it would be a huge benefit to both users running actions and reduce load on GH infrastructure.

**Comment by dhadka** [comment]
@mikelax Would https://github.com/satackey/action-docker-layer-caching work for you?  It's built on top of this action.

**Comment by piotrkubisa** [comment]
> @mikelax Would https://github.com/satackey/action-docker-layer-caching work for your case? It's built on top of this action.

This linked action says it will use following method to take care of caching:

> This GitHub Action uses the docker save / docker load command and the @actions/cache library.

While ago, @dtinth published an article with titled _Caching Docker builds in GitHub Actions: Which approach is the fastest? 🤔 A research._ (https://dev.to/dtinth/caching-docker-builds-in-github-actions-which-approach-is-the-fastest-a-research-18ei). He found the docker save/load method is far from the best solution. Worth taking a look whether you are trying to cut some seconds.

**Comment by kaka-ruto** [comment]
Hoping this bubbles up the priority list soon!

**Comment by potatoqualitee** [comment]
Would love to see this built-in as well.

**Comment by ErikSchierboom** [comment]
While the setup-buildx suggestion works when you're building your own docker images, AFAICT it doesn't work when you're using docker images as container services. It would be great if this was supported.

**Comment by basicdays** [comment]
It is also a beast to try to use if you have your test services and container under test setup through docker-compose. There is no obvious way to get the docker provided actions to work with the cache.

**Comment by rahulbirari-cpi** [comment]
Would love to see this feature as well in 2022 .

**Comment by roj1512** [comment]
Need this.

**Comment by evencheng-invitae** [comment]
Upvote

**Comment by thisismydesign** [comment]
The cache option on `docker/build-push-action` works great for building images.

```
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-upload-docker-image:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
    outputs:
      docker-tag: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile.prod
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=registry,ref=${{ steps.meta.outputs.tags }}
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:master
          cache-to: type=inline
```

However, I have a use case for running tests in a dockerized setup.

```
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [build-and-upload-docker-image]

    steps:
    - uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.PACKAGE_ACCESS_TOKEN }}

    - name: Run tests
      run: docker-compose run web yarn test
```

Here every run pulls dependencies (e.g. postgres, redis, etc). Could caching of those be supported natively or by an action?

**Comment by DannyBen** [comment]
> The cache option on `docker/build-push-action` works great for building images.

Well, that is not that great in the minimalist's opinion. The syntax is very convoluted, and as you noticed, works partially. I hope some day, `$ docker build` would work on the GitHub action runners in the same way it works on any other long-running machine, with docker layer cache built in and mounted automatically, with a simple or no config.

**Comment by thisismydesign** [comment]
@DannyBen Yeah it's verbose but if it bothers you, create an action to wrap these into a one-liner.

**Comment by Kurt-von-Laven** [comment]
> Should we try to use this cache action to cache docker layers, doing trickery with `docker save` and `docker load`, or are you working on a different path for Docker caching?

My company, ScribeMD, faced a similar issue and just released a dirt simple [docker-cache](https://github.com/marketplace/actions/docker-cache) action, which caches all Docker images whether built or pulled using said `docker save`/`docker load` trickery. Please file an issue if you have any feedback!

**Comment by l1553k** [comment]
Just leaving an idea, haven't seen it discussed yet:
```
      - uses: actions/cache@v3
        with:
          path: ~/.cache/docker
          key: ${{ runner.os }}-docker
          restore-keys: |
            ${{ runner.os }}-docker
      - name: Mount docker inside ~/.cache/docker
        run: |
          sudo systemctl stop docker.service
          sudo systemctl stop docker.socket
          sudo sed -i "s!ExecStart=/usr/bin/dockerd!ExecStart=/usr/bin/dockerd -g $(echo $HOME)/.cache/docker!" /lib/systemd/system/docker.service
          sudo systemctl daemon-reload
          sudo systemctl start docker

...

      - name: Make cache accessible to caching action (put this at the end of yml)
        run: |
          sudo chown $(whoami):$(whoami) -R ~/.cache
```
It has some problems which I hope someone smarter will know how to solve and share that knowledge:

```
Post job cleanup.
/usr/bin/tar --posix --use-compress-program zstd -T0 -cf cache.tzst -P -C /home/runner/work/my-repo/my-repo --files-from manifest.txt
/usr/bin/tar: ../../../.cache/docker/overlay2/7aca327c7588ed39f3f42dee1459c9ca3e42d699db7f03c0152212c9b8d347be/work/work: Cannot open: Permission denied
...
/usr/bin/tar: ../../../.cache/docker/overlay2/9873a6171ad3ecbd9d5541d49b8ca221e1d6e39871e356ff07f5ff22715f8959/work/work: Cannot open: Permission denied
/usr/bin/tar: Exiting with failure status due to previous errors
Warning: Tar failed with error: The process '/usr/bin/tar' failed with exit code 2
```
Soooo... it does not work (as I said, this is an idea, not a solution :) ).

**Comment by Kurt-von-Laven** [comment]
Myself and others have run into a similar issue. I am not aware of another way around the permission errors currently besides using `docker save` and `docker load`. [Running Docker in rootless mode](https://github.com/marketplace/actions/rootless-docker) addresses some Docker permission issues, but not these. If someone knows of a better approach, please feel free to send a PR to [ScribeMD/docker-cache](https://github.com/ScribeMD/docker-cache).

**Comment by Kurt-von-Laven** [comment]
I have since learned of a much faster approach provided you have control over where the Docker image is pulled from. You can simply upload the Docker images you are pulling to the GitHub Container Registry, which spares you the cost of `docker save` + cache upload on cache miss. For those, like us, who don't have such control, [docker-cache](https://github.com/marketplace/actions/docker-cache) is probably your best bet for now.

**Comment by EpsilonAlpha** [comment]
I run into the same issue: tried to cache /var/lib/docker with the result after cleanup (which means saving the cache I guess):

```
Post job cleanup.
Warning: EACCES: permission denied, scandir '/var/lib/docker'
```

Donno if I made a mistake on the workflow file in the Cache Step:

```
    - name: Cache Docker Layer
      id: cache-docker
      uses: actions/cache@v3
      env:
        cache-name: cache-docker-layer
      with:
        path: /var/lib/docker
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/image/overlay2/repositories.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
```
