### ISSUE TITLE
Allow caching for deployment events or other events without GITHUB_REF

### ISSUE THREAD

**Issue by localheinz** [actions/cache#319]
As suggested in #317 and #318, I would like to be able to use `actions/cache` for events where the `GITHUB_REF` environment variable is not necessarily defined.

For example, I currently have decoupled the creation and the processing of deployments.

- one ore more workflows create deployment (with differing payloads) using the [Deployments API](https://developer.github.com/v3/repos/deployments/)
- a workflow is triggered by a deployment event and process the actual deployment to different environments

Currently, even with #263, it is not possible to use caching for the `deployment` event (see @joshmgross' comments in #317). Consequently, deployments using a workflow setup describes as above either take a lot longer, or are not feasible.

It would be really nice to be able to use `actions/cache` with a setup as described!

Let me know if there is anything I can do to help push this feature through the door.

🌱

**Comment by RichiCoder1** [comment]
Would love this for the exact reason of `deployment` events.

**Comment by BrendanSChang** [comment]
Any news on this? I have the same use case/workflow and would love to see this enhancement as well.

**Comment by RichiCoder1** [comment]
Leaving a comment to avoid closing this issue in 5 days.

**Comment by Fedeorlandau** [comment]
This would be massive for us. We're running cypress after Vercel's deployment.

```yaml
name: Run E2E Tests
on: [deployment_status]
jobs:
  e2e:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn
      - run: yarn cypress:headless --env host=${{ github.event.deployment_status.target_url }}
```
