### ISSUE TITLE
Feature framework-specific @actions/cache implementations on the examples page

### ISSUE THREAD

**Issue by thisismydesign** [actions/cache#322]
I took the recently released `@actions/cache` package and used it to implement some framework-specific examples as listed in [examples.md](https://github.com/actions/cache/blob/9ab95382c899bf0953a0c6c1374373fc40456ffe/examples.md), namely: [NPM cache](https://github.com/c-hive/gha-npm-cache), [Yarn cache](https://github.com/c-hive/gha-yarn-cache).

It's great to have the examples here but they are quite complex and take up a lot of space in the workflows. For example, for NPM:

```yml
- name: Get npm cache directory
  id: npm-cache
  run: |
    echo "::set-output name=dir::$(npm config get cache)"
- uses: actions/cache@v1
  with:
    path: ${{ steps.npm-cache.outputs.dir }}
    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    restore-keys: |
      ${{ runner.os }}-node-
```
vs.

```yml
- uses: c-hive/gha-npm-cache@v1
```

Would it make sense to feature some of these framework-specific implementations on the examples page? Happy to provide a PR.
