### ISSUE TITLE
Preserve exact timestamps

### ISSUE THREAD

**Issue by OlegYch** [actions/cache#326]
Some tools (like https://www.scala-sbt.org/) rely on files timestamps with millisecond precision.
Currently cache preserves timestamps only down to second precision.
The fix would be to simply use posix format when tarring files.
https://github.com/actions/cache/pull/233 was my attempt at fixing it but it no longer works with current master

**Comment by jcayzac** [comment]
I really need this too!
@OlegYch meanwhile, please do not delete your `posix` branch as my workflow depends on it :)

**Comment by jcayzac** [comment]
Actually, after spending two days trying to get incremental builds to work, I just remembered git doesn't support timestamps and I gave up.

**Comment by jcayzac** [comment]
I guess I need an action that takes the timestamp of the base ref, applies it to all files, then takes the timestamp of the head ref and applies it to all modified/added files.

**Comment by jcayzac** [comment]
> I guess I need an action that takes the timestamp of the base ref, applies it to all files, then takes the timestamp of the head ref and applies it to all modified/added files.

I ended up using [chetan/git-restore-mtime-action](https://github.com/chetan/git-restore-mtime-action) for that.

### Example steps:

```yaml
- name: 'Restore timestamps'
  uses: chetan/git-restore-mtime-action@v1.0

- name: 'Cache: Derived data'
  uses: OlegYch/cache@posix
  id: cache-derived-data
  with:
    path: .build/derived-data
    key: ${{ runner.os }}-deriveddata-${{ github.base_ref }}@${{ github.event.pull_request.base.sha }}-${{ github.head_ref }}@${{ github.sha }}
    restore-keys: |
      ${{ runner.os }}-deriveddata-${{ github.base_ref }}@${{ github.event.pull_request.base.sha }}-${{ github.head_ref }}@
      ${{ runner.os }}-deriveddata-${{ github.base_ref }}@${{ github.event.pull_request.base.sha }}-
      ${{ runner.os }}-deriveddata-${{ github.base_ref }}@
```
