### ISSUE TITLE
Unexpected behaviour: historiacal cache hit from commits in history

### ISSUE THREAD

**Issue by hgezim** [actions/cache#328]
I have a step defined like this:

```
      - name: Cache migrations
        id: cache-migrations
        uses: actions/cache@v1
        with:
          path: migrations
          key: ${{ runner.os }}-migrations-${{ hashFiles('./migrations/*') }}
      - name: Run migrations
        if: steps.cache-migrations.outputs.cache-hit != 'true'
        run: |
          aws ecs...
```

I had added a file under `./migrations/` to test the cache and it picked up the change which was great.

I then removed the test file in a new commit and was terrified to find that there was a cache hit even though I just changed the `migrations` dir.

Upon further investigation, I discovered that there was a previous hash store in cache for `migrations` where that file didn't exist.

This was definitely not expected behaviour. How do I limit cache history to 1 item?

Should default change? I'm using caching to determine if there's something different enough in this commit which I need to do extra build work for.

**Update**: The previous hash was generated from a commit in the same branch.
