### ISSUE TITLE
There are some problems when caching vcpkg on windows-2016

### ISSUE THREAD

**Issue by wangsongc** [actions/cache#333]
I want to cache vcpkg, it is successful on windows-2019, but there are some problems on windows-2016.

```
 - name: Cache Depends
        id: cache-depends
        uses: actions/cache@v2
        with:
          path: C:\vcpkg\installed\x64-windows
          key: ${{ matrix.os }}-vcpkg
```
Run action for the first time
https://github.com/wangsongc/action-test/runs/715286404?check_suite_focus=true
```
Post job cleanup.
"C:\Program Files\Git\usr\bin\tar.exe" --use-compress-program "zstd -T0" -cf cache.tzst -P -C D:/a/action-test/action-test --files-from manifest.txt --force-local
/usr/bin/tar: C\:\vcpkg\\installed\\x64-windows: Cannot stat: No such file or directory
/usr/bin/tar: Exiting with failure status due to previous errors
[warning]Tar failed with error: The process 'C:\Program Files\Git\usr\bin\tar.exe' failed with exit code 2
```
Run action for the second time
https://github.com/wangsongc/action-test/runs/715319270?check_suite_focus=true
```
Post job cleanup.
[warning]reserveCache failed: Cache already exists. Scope: refs/heads/master, Key: windows-2016-vcpkg, Version: f43601b869e409297d844610c90c97a34e4dcf31116c5b1ab37d82956a75fda4
```
