### ISSUE TITLE
Bundler not picking up cache

### ISSUE THREAD

**Issue by avimoondra** [actions/cache#348]
Seems to be an issue with following the example provided from this repo, https://github.com/actions/cache/blob/master/examples.md#ruby---bundler

> Ruby - Bundler
```yaml
- uses: actions/cache@v2
  with:
    path: vendor/bundle
    key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
    restore-keys: |
      ${{ runner.os }}-gems-
```
> When dependencies are installed later in the workflow, we must specify the same path for the bundler.
```yaml
- name: Bundle install
  run: |
    bundle config path vendor/bundle
    bundle install --jobs 4 --retry 3
```

With the following configuration:

https://github.com/defund12/defund12.org/pull/1369/files#diff-e9f950f17198d3d5e3122a44230a09b9R23-R35

```yaml
  test-jekyll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - run: ls -l vendor/bundle/ruby/
      - run: gem install bundler -v 2.1.4
      - run: bundle config path vendor/bundle
      - run: bundle install --jobs 4 --retry 3 --path vendor/bundle
```

On re-runs of this build, `bundler` does not seem to pick up `vendor/bundle` cached gems, despite finding the cache key. `bundler` always re-installs the gems. See screenshot below:

![image](https://user-images.githubusercontent.com/2534903/84447445-dad93e00-abfc-11ea-8322-22063d1d0be6.png)

I've also posted this issue on the community forums: https://github.community/t/bundler-bundle-not-using-cache-in-github-actions/117686

---- 

Not sure how to debug further, or if there is a configuration error. Thanks!
