### ISSUE TITLE
How should I configure the path for maven dependencies

### ISSUE THREAD

**Issue by zhanyeye** [actions/cache#349]
```yml
- uses: actions/cache@v2
  with:
    path: ~/.m2/repository
    key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
```
I introduced it into the workflow file, but it didn't cache successfully. would it be that the path for `~/.m2/ Repository`  is not correct?
Where is the Maven repository path in GitHub actions ? 
thank you.
