### ISSUE TITLE
Read only cache?

### ISSUE THREAD

**Issue by milanaleksic** [actions/cache#350]
I am interested in creating cache in action X of the workflow, and then reusing it in action Y, but I don't want to waste time to _recreate_ cache at the cleanup stage of the `cache` action in action Y  - I know I only used it in read-only fashion in action Y (whereas action X might have written to it), so waiting for the new cache creation is wasteful.

Is there a way in current implementation to get this behavior and if not would you consider this as a new feature?

**Comment by milanaleksic** [comment]
Clarification: I am aware of cache hit/miss analysis in the cleanup stage, and that in case no files that participate in file cache ID creation are changed there would be no need to push the new cache version, _but_ I am asking could we still ignore changed files and proceed in not even trying to analyze if they have changed, just ignoring the creation of the new cache instance altogether?

**Comment by MartijnHols** [comment]
Seeing as my PRs to the GitHub repos have been ignored for almost a year, I closed all of them. To clean up my workflows I have decided to work on a fork instead with an (in my eyes) cleaner solution. See the repository for documentation: https://github.com/MartijnHols/actions-cache Here is what sharing cache across jobs would look like:

```yaml
name: Build app

on: push

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Restore "node_modules" from cache
      id: cache
      uses: martijnhols/actions-cache/restore@main
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock', 'patches') }}
        restore-keys: ${{ runner.os }}-node_modules

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install

    - name: Save "node_modules" to cache
      if: steps.cache.outputs.cache-hit != 'true'
      uses: martijnhols/actions-cache/save@main
      with:
        path: node_modules
        key: ${{ steps.cache.outputs.primary-key }}

  build:
    needs: [install]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Restore "node_modules" from cache
      uses: martijnhols/actions-cache/restore@main
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock', 'patches') }}
        # Fail when the cache could not be found (this should never happen unless you have a misconfiguration)
        required: true

    - name: Build app
      run: yarn build
```
