### ISSUE TITLE
Add an example for Anaconda or Miniconda

### ISSUE THREAD

**Issue by epassaro** [actions/cache#355]
It would be really useful to have an example to show how to cache `conda` environments.

**Comment by kengz** [comment]
Sharing what I managed to do:
```yaml
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache Conda
      uses: actions/cache@v1
      with:
        path: /home/ga/miniconda3/envs/MYPROJECT
        key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
        restore-keys: |
          ${{ runner.os }}-conda-
    - name: Setup Conda dependencies
      uses: goanpeca/setup-miniconda@v1
      env:
        CONDA: /home/ga/miniconda3
      with:
         activate-environment: MYPROJECT
         environment-file: environment.yml
         python-version: 3.8
         auto-activate-base: false
    - name: Conda info
      shell: bash -l {0}
      run: |
        conda info
        conda list

    - name: Setup flake8 annotations
      uses: rbialon/flake8-annotations@v1
    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        pip install flake8
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --statistics

    - name: Run tests
      shell: bash -l {0}
      run: |
        python setup.py test
```
