### ISSUE TITLE
Using cache for C#

### ISSUE THREAD

**Issue by eddynaka** [actions/cache#357]
Hi,

I was looking at the cache action and i got some issues. So based on the example above from the home page:
```yml
- uses: actions/cache@v2
  with:
    path: ~/.nuget/packages
    key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
    restore-keys: |
      ${{ runner.os }}-nuget-
```

The idea would be that all the packags would get in cache. When i added that to the repository, it's caching the entire folder of the application instead of the nuget/packages only. So the folder is getting 700MB.

It's happening on win and linux environment.
