### ISSUE TITLE
Caching outside of GITHUB_WORKSPACE problematic

### ISSUE THREAD

**Issue by mcg1969** [actions/cache#361]
Here's an example form of the command that `actions/cache@v2` uses on a mac to create a cache:
```
/usr/bin/tar --use-compress-program zstd -T0 -cf cache.tzst -P -C /Users/runner/runners/2.169.1/work/conda-pack/conda-pack --files-from manifest.txt
```
In this case, the name of the repository is `conda-pack`, and `.../work/conda-pack/conda-pack` is the root directory of the checked-out git repository.

When I first began building an action for this repository, I wanted to cache something in the `$HOME` directory. This seemed to work fine on Linux, but on Mac, I was getting these errors:
```
/usr/bin/tar --use-compress-program zstd -d -xf /Users/runner/work/_temp/a2e257c1-bc6e-422a-a46f-5f0b9f8b21e7/cache.tzst -P -C /Users/runner/work/conda-pack/conda-pack
../../../../../conda/: Can't create '../../../../../conda'
../../../../../conda/man/: Failed to create dir '../../../../../conda'
../../../../../conda/conda-meta/: Failed to create dir '../../../../../conda'
../../../../../conda/condabin/: Failed to create dir '../../../../../conda'
../../../../../conda/ssl/: Failed to create dir '../../../../../conda'
../../../../../conda/bin/: Failed to create dir '../../../../../conda'
```
It makes sense that a tar file cannot unpack to relative paths that fall outside of the root directory of the extraction. And to be clear, I've determined that for technical reasons I don't want to be in `$HOME` in Windows.

However, your instructions include numerous examples of caching paths outside of the `GITHUB_WORKSPACE` directory. It's unclear to me why my approach did not work. I would definitely like to be able to cache things outside of `GITHUB_WORKSPACE`—even if it is just one directory up. I don't want to have to "corrupt" my git repository clone.

Below are the relevant logs and workflow spec, which might have bugs for other reasons, mind you.

https://github.com/conda/conda-pack/runs/837672740?check_suite_focus=true
https://github.com/conda/conda-pack/actions/runs/157856418/workflow

**Comment by mcg1969** [comment]
Actually I think the real problem may that the location of `GITHUB_WORKSPACE` is inconsistent! It's at different depths, which throws off any attempt to use these relative paths outside of the root, even if `tar` were to support them.

For example, [here](https://github.com/conda/conda-pack/runs/838939199?check_suite_focus=true) the cache is unpacked into `/Users/runner/runners/2.169.1/work/conda-pack/conda-pack`.
But [here](https://github.com/conda/conda-pack/runs/838943780?check_suite_focus=true) the cache is unpacked into `/Users/runner/work/conda-pack/conda-pack`.

**Comment by mrbenshef** [comment]
I have a simular issue on windows, I want to cache `C:\gtk-build\gtk\x64\release\lib\**`. Saving works find, but upon restoring I get:

```
C:/gtk-build/gtk/x64/release/lib/: Can't create '\\\\?\\C:\\gtk-build\\gtk\\x64\\release\\lib'
C:/gtk-build/gtk/x64/release/lib/asprintf.lib: Can't create '\\\\?\\C:\\gtk-build\\gtk\\x64\\release\\lib\\asprintf.lib'
C:/gtk-build/gtk/x64/release/lib/atk-1.0.lib: Can't create '\\\\?\\C:\\gtk-build\\gtk\\x64\\release\\lib\\atk-1.0.lib'
C:/gtk-build/gtk/x64/release/lib/cairo-gobject.lib: Can't create '\\\\?\\C:\\gtk-build\\gtk\\x64\\release\\lib\\cairo-gobject.lib'
C:/gtk-build/gtk/x64/release/lib/cairo.lib: Can't create '\\\\?\\C:\\gtk-build\\gtk\\x64\\release\\lib\\cairo.lib'
...
```

[Workflow file](https://github.com/mrbenshef/Boop-GTK/blob/91e6e647325804f838279b77de004f84df55390f/.github/workflows/ci.yml)

**Comment by mcg1969** [comment]
@mrbenshef for that one I suspect the issue is the attempt to archive across disks (C vs. D).

The magic moving GITHUB_WORKSPACE issue seems to be addressed here:
https://github.community/t/why-does-the-location-of-github-workspace-change-from-job-to-job/121404

This should allow relative paths to be reliable on macOS.

**Comment by mcg1969** [comment]
Ah, unfortunately, I now run into this if I try to put things in, say, `..`:
```
Post job cleanup.
[warning]Invalid pattern '../conda'. Relative pathing '.' and '..' is not allowed.
```
So relative paths within GITHUB_WORKSPACE are fine, and absolute paths outside of it.

**Comment by RevoluPowered** [comment]
> I have a simular issue on windows, I want to cache `C:\gtk-build\gtk\x64\release\lib\**`. Saving works fine, but upon restoring I get:
> 
> ```
> C:/gtk-build/gtk/x64/release/lib/: Can't create '\\\\?\\C:\\gtk-build\\gtk\\x64\\release\\lib'
> C:/gtk-build/gtk/x64/release/lib/asprintf.lib: Can't create '\\\\?\\C:\\gtk-build\\gtk\\x64\\release\\lib\\asprintf.lib'
> C:/gtk-build/gtk/x64/release/lib/atk-1.0.lib: Can't create '\\\\?\\C:\\gtk-build\\gtk\\x64\\release\\lib\\atk-1.0.lib'
> C:/gtk-build/gtk/x64/release/lib/cairo-gobject.lib: Can't create '\\\\?\\C:\\gtk-build\\gtk\\x64\\release\\lib\\cairo-gobject.lib'
> C:/gtk-build/gtk/x64/release/lib/cairo.lib: Can't create '\\\\?\\C:\\gtk-build\\gtk\\x64\\release\\lib\\cairo.lib'
> ...
> ```
> 
> [Workflow file](https://github.com/mrbenshef/Boop-GTK/blob/91e6e647325804f838279b77de004f84df55390f/.github/workflows/ci.yml)

https://github.com/actions/cache/issues/366 Getting this too.. it's frustrating because it won't happen on self hosted runners

**Comment by mcg1969** [comment]
Yes I believe the issue in your case is that the root of the archive is on the D drive, so the archive is being asked to span filesystems. So what I have done now, which works on all OSs, is to choose my paths relative to GITHUB_WORKSPACE but convert them to absolute paths before feeding them to actions/cache. Obviously it would be nice if the action did that for me but beggars can't be choosers! And combining that technique with the recent fixes to the mac runner has solved my problem completely.

**Comment by RevoluPowered** [comment]
I fixed the issue with an edit to the cache plugin, I just removed the args and added a new tag

https://github.com/RevoluPowered/cache

windows-latest works for our use case and tar is included by default with windows now apparently

```
# Engine build CI
name: Godot CI

on:
    # will build EVERY pull request
    pull_request:

    # will only build explicit branches
    push:
      branches: [ master, 3.2, 3.1, 3.0 ]

# Global Cache Settings
# SCONS_CACHE for windows must be set in the build environment
env:
  SCONS_CACHE_MSVC_CONFIG: true
  SCONS_CACHE_LIMIT: 1024

jobs:
  windows-editor:
    # Windows 10 with latest image
    runs-on: "windows-latest"

    # Windows Editor - checkout with the plugin
    name: Windows Editor (target=release_debug, tools=yes)
    steps:
    - uses: actions/checkout@v2 

    # Cache must be put in the github workspace directory on windows to be persisted correctly
    - name: "Force scons cache to the correct value for this builder"
      run: echo "::set-env name=SCONS_CACHE::${{env.HOME}}/.scons_cache/"

    # Upload cache on completion and check it out now
    # Editing this is pretty dangerous for windows since it can break and needs properly tested with a fresh cache.
    # Linux with this will work reliably, so not as bad to edit for Linux.
    - name: Configure .scons_cache and download cache
      id: scons-cache
      uses: RevoluPowered/cache@v2.1
      with:
        path: ${{env.SCONS_CACHE}}
        key: ${{ runner.os }}-godot-release_debug_editor
        restore-keys: ${{ runner.os }}-godot-release_debug_editor
    
    # Use python 3.x release (works cross platform; best to keep self contained in it's own step)
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x' 
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64' 

    # Setup scons, print python version and scons version info, so if anything is broken it won't run the build.
    - name: Configuring python packages
      run: |
        python -c "import sys; print(sys.version)"
        python -m pip install scons pywin32
        python --version
        scons --version
    # We should always be explicit with our flags usage here since it's gonna be sure to always set those flags
    - name: Compilation
      run: |
        scons -j2 verbose=yes warnings=all werror=yes platform=windows tools=yes target=release_debug
# Build Product Upload (tested and working)
# sorry this is disabled until github can give us some more space as we would hit our limit very quickly
# tested this code and it works fine so just enable it to get them back
#    - name: publishing godot windows-editor
#      uses: actions/upload-artifact@v1
#      with:
#        name: windows-editor (x64)
#        path: bin/godot.windows.opt.tools.64.exe


  windows-template:
    runs-on: "windows-latest"
    name: Windows Template (target=release, tools=no)
    steps:
    - uses: actions/checkout@v2 
    
    # Cache must be put in the github workspace directory on windows to be persisted correctly
    - name: "Force scons cache to the correct value for this builder"
      run: echo "::set-env name=SCONS_CACHE::${{env.HOME}}/.scons_cache/"

    # Upload cache on completion and check it out now
    - name: Configure .scons_cache and download cache
      id: scons-cache
      uses: RevoluPowered/cache@v2.1
      with:
        path: ${{env.SCONS_CACHE}}
        key: ${{ runner.os }}-godot-release_runtime
        restore-keys: ${{ runner.os }}-godot-release_runtime
    
    # Use python 3.x release (works cross platform)
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x' 
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64' 

    # You can test your matrix by printing the current Python version
    - name: Configuring Python packages
      run: |
        python -c "import sys; print(sys.version)"
        python -m pip install scons pywin32
        python --version
        scons --version
    - name: Compilation
      run: |
        scons -j2 verbose=yes warnings=all werror=yes platform=windows target=release tools=no
# Build Product Upload (tested and working)
# sorry this is disabled until github can give us some more space as we would hit our limit very quickly
# tested this code and it works fine so just enable it to get them back
#    - name: publishing godot windows-template
#      uses: actions/upload-artifact@v1
#      with:
#        name: windows-template (x64)
#        path: bin/godot.windows.opt.64.exe
```

I didn't care here about legacy windows
