### ISSUE TITLE
Feature request: allow a cache to be checked without retrieving/unpacking

### ISSUE THREAD

**Issue by mcg1969** [actions/cache#363]
In [this run](https://github.com/conda/conda-pack/actions/runs/158855067) I have a `testbed` task that takes awhile to run, but also takes awhile to download and upload. I'd like to exit this task quickly _if the cache is already populated_, without even downloading the cache contents. So just check and see if the key is there, nothing else.

This could be facilitated with, say, a flag called `download` that is `true` by default; but if set to `false`, skips the download portion of the cache process.

**Comment by mcg1969** [comment]
Alternatively, a flag `stop_on_hit` or similar could be developed that terminates the job immediately with a successful hit.

**Comment by mcg1969** [comment]
Check out [this workflow] for a way I've implemented this with existing tooling.

Basically, I create _two_ caches: the first is a very small cache that loads quickly. Then I can use its `cache-hit` state to determine whether or not I need to even try to fetch the "real" cache.

```
    # Use a smaller cache entry to enable a quicker exit if we
    # have already built the testbed. Any small file will do
    - id: cache-key
      name: Retrieve cache key
      uses: actions/cache@v2
      with:
        path: LICENSE.txt
        key: key-${{ matrix.os }}-${{ hashFiles('testing') }}-5
    - name: Retrieve or create the testbed cache
      if: steps.cache-key.outputs.cache-hit != 'true'
      uses: actions/cache@v2
      with:
        path: ${{ steps.conda-root.outputs.value }}
        key: testbed-${{ matrix.os }}-${{ hashFiles('testing') }}-5
```
