### ISSUE TITLE
Github Actions / Service has permissions issues with cache files on windows

### ISSUE THREAD

**Issue by RevoluPowered** [actions/cache#366]
**On non self hosted runners I'm getting:**

```
../../../../../../.scons_cache/08/088da2b137de218e3019b1cb196248ee: Can't create '\\\\?\\.scons_cache\\08\\088da2b137de218e3019b1cb196248ee'
../../../../../../.scons_cache/07/0711ff940b39b6e4d8a6d9093fdfbefa: Can't create '\\\\?\\.scons_cache\\07\\0711ff940b39b6e4d8a6d9093fdfbefa'
../../../../../../.scons_cache/07/074bf38f0ada07b13e2afa79146ada1c: Can't create '\\\\?\\.scons_cache\\07\\074bf38f0ada07b13e2afa79146ada1c'
../../../../../../.scons_cache/06/06e0868992c3187a7d95a3fc9bf288a0: Can't create '\\\\?\\.scons_cache\\06\\06e0868992c3187a7d95a3fc9bf288a0'
../../../../../../.scons_cache/05/05ce05c3b99bcddcc6c5a96ac0700a55: Can't create '\\\\?\\.scons_cache\\05\\05ce05c3b99bcddcc6c5a96ac0700a55'
../../../../../../.scons_cache/05/05f17c7fb7ad134042bc8293eee959c0: Can't create '\\\\?\\.scons_cache\\05\\05f17c7fb7ad134042bc8293eee959c0'
../../../../../../.scons_cache/04/0409c7d9c5987d35edcd10581a34daab: Can't create '\\\\?\\.scons_cache\\04\\0409c7d9c5987d35edcd10581a34daab'
../../../../../../.scons_cache/03/034ef1fcd439b0cc6f14aaca365c0a03: Can't create '\\\\?\\.scons_cache\\03\\034ef1fcd439b0cc6f14aaca365c0a03'
../../../../../../.scons_cache/02/02a30a25ca6b73691e4759c2c93433d3: Can't create '\\\\?\\.scons_cache\\02\\02a30a25ca6b73691e4759c2c93433d3'
../../../../../../.scons_cache/02/02ffc7c73449955dd78ed7d9ec738557: Can't create '\\\\?\\.scons_cache\\02\\02ffc7c73449955dd78ed7d9ec738557'
../../../../../../.scons_cache/01/0145b7b384fe12e6c7d8058bd812968a: Can't create '\\\\?\\.scons_cache\\01\\0145b7b384fe12e6c7d8058bd812968a'
../../../../../../.scons_cache/01/0159aea9b7378ec51219a6908fb3e9bb: Can't create '\\\\?\\.scons_cache\\01\\0159aea9b7378ec51219a6908fb3e9bb'
../../../../../../.scons_cache/01/01f886bc931f7958d16d9d88658ab887: Can't create '\\\\?\\.scons_cache\\01\\01f886bc931f7958d16d9d88658ab887'
../../../../../../.scons_cache/00/00cf78a778553e4abaac9f217ee7d7d5: Can't create '\\\\?\\.scons_cache\\00\\00cf78a778553e4abaac9f217ee7d7d5'
tar.exe: Error exit delayed from previous errors.
[warning]Tar failed with error: The process 'C:\windows\System32\tar.exe' failed with exit code 1
  Set up Python 3.x1s
  Display Python version1s
  Installing scons and pywin3234s
  Check versioning1s
```

**On self hosted runners I'm getting** 
```
Run actions/cache@v2
  with:
    path: /.scons_cache/
    key: Windows-release_debug-editor
    restore-keys: Windows-release_debug-editor
  env:
    SCONS_CACHE: /.scons_cache/
Cache Size: ~217 MB (227906417 B)
C:\Windows\System32\tar.exe -z -xf C:/Users/Gordon/actions-runner/_work/_temp/9ea9ec4f-32e6-485a-9d68-6178c74b7f1a/cache.tgz -P -C C:/Users/Gordon/actions-runner/_work/godot/godot
Cache restored from key: Windows-release_debug-editor
```

I am expecting this to resolve correctly but it's not working on the GitHub actions servers.

**Example CI config**
```yaml
name: Godot CI

on:
    pull_request:
    push:
      branches: [ master, 3.2, 3.1, 3.0 ]
jobs:
  windows-editor:
    runs-on: "windows-latest"
    name: Windows Editor (release_debug)
    steps:
    - uses: actions/checkout@v2 
    # cache must be put in the github workspace directory on windows to be persisted correctly
    - name: "force cache path to be correct"
      run: echo "::set-env name=SCONS_CACHE::${{env.GITHUB_WORKSPACE}}/.scons_cache/"
    # upload cache on completion and check it out now
    - name: configure .scons_cache and download cache
      id: scons-cache
      uses: actions/cache@v2
      with:
        path: ${{env.SCONS_CACHE}}
        key: ${{ runner.os }}-release_debug-editor
        restore-keys: ${{ runner.os }}-release_debug-editor
    # use python 3.x release (works cross platform)
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x' 
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64' 
    # You can test your matrix by printing the current Python version
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Installing scons and pywin32
      run: |
        python -m pip install scons pywin32
    - name: Check versioning
      run: |
        python --version
        scons --version
    - name: Compilation
      run: |
        scons -j2 warnings=all werror=yes platform=windows target=release_debug
    - name: publishing godot windows-editor
      uses: actions/upload-artifact@v1
      with:
        name: windows-editor (x64)
        path: bin/godot.windows.opt.tools.64.exe
```
