### ISSUE TITLE
v2 never works, always says "Cache not found"

### ISSUE THREAD

**Issue by jcayzac** [actions/cache#369]
In a very simple pnpm project, `actions/cache` always gives me `Cache not found`. The step is configured as follow:

```yaml
- name: 'Cache node modules'
  uses: actions/cache@v2
  with:
    path: '**/node_modules'
    key: ${{ runner.os }}-node-modules
```

…whereas the log for the _post_ action says the cache is saved successfully:

```txt
Post job cleanup.
/bin/tar --use-compress-program zstd -T0 -cf cache.tzst -P -C /home/runner/work/foo/foo --files-from manifest.txt
Cache saved successfully
Post job cleanup.
/bin/tar --use-compress-program zstd -T0 -cf cache.tzst -P -C /home/runner/work/foo/foo --files-from manifest.txt
Cache saved successfully
```
