### ISSUE TITLE
Cache for poetry install

### ISSUE THREAD

**Issue by northtree** [actions/cache#374]
I tried to use this `actions/cache@v2` to cache poetry venv. There are only two libraries `pylint` and `pytest` installed. It seems that installation was cached (cache size ~ 26MB). However, they couldn't be retrieved after cache hit.

The cache installed libraries are not found while run 
> poetry run pip list
```
Package    Version
---------- -------
pip        20.1.1
setuptools 41.2.0 
```
https://github.com/northtree/poetry-github-actions/runs/875926237?check_suite_focus=true#step:9:1

The YAML is [here](https://github.com/northtree/poetry-github-actions/actions/runs/170795796/workflow).

Could I know how to use `actions/cache@v2` to cache poetry installation / virturalenv to avoid reinstalling dependencies.

**Comment by northtree** [comment]
The cached issue was resolved by this. https://stackoverflow.com/questions/62977821/how-to-cache-poetry-install-for-github-actions

The updated config is [here](https://github.com/northtree/poetry-github-actions/actions/runs/192781303/workflow).

```yaml
name: python

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WORKON_HOME: ~/.poetry/venv

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install poetry
      uses: dschep/install-poetry-action@v1.3

    - name: Configure poetry
      run: |
        poetry config virtualenvs.create true
        poetry config virtualenvs.in-project false
        poetry config cache-dir ~/.poetry
        poetry config virtualenvs.path ~/.poetry/venv
    - name: Cache poetry venv
      uses: actions/cache@v2
      id: poetry-cache
      with:
        path: ~/.poetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-
    - name: Install Dependencies
      if: steps.poetry-cache.outputs.cache-hit != 'true'
      run: poetry install -vv

    - name: Show poetry env info
      run: |
        poetry env info
        poetry config --list
    - name: Test poetry run
      run: |
        poetry run pip list
```
