### ISSUE TITLE
caching php dependencies in a github action 

### ISSUE THREAD

**Issue by staabm** [actions/cache#376]
not sure the underlying problem is related to GitHub Actions or composer itself.

when using dependency caching like described in https://github.com/actions/cache/blob/main/examples.md#php---composer:

```
- name: Get Composer Cache Directory
  id: composer-cache
  run: |
    echo "::set-output name=dir::$(composer config cache-files-dir)"
- uses: actions/cache@v2
  with:
    path: ${{ steps.composer-cache.outputs.dir }}
    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
    restore-keys: |
      ${{ runner.os }}-composer-
```

we get a ugly error condition in case the composer.json is not valid.
this happend today in our case because of a merge conflict, which was not resolved properly.

we get into a situation as follows:

![grafik](https://user-images.githubusercontent.com/120441/87669841-f3de8d00-c76e-11ea-8489-8be5bbe6049b.png)

so because of a invalid composer.json the variable which is later on used for the actions/cache@v2 `path` parameter is not properly filled and it runs into an error.

I expected the 'Get Composer Cache Directory' step should fail immediately - not the follow up step which makes it harder to reason about the cause of the error.
is there anything which could be improved here?

_Cross-posting issue https://github.com/composer/composer/issues/9055_
