### ISSUE TITLE
hashFiles() does not work for valid patterns

### ISSUE THREAD

**Issue by poiru** [actions/cache#39]
The expected behavior is that all three of the following steps pass on all platforms:

```yml
- name: Cache **/README.md
  uses: actions/cache@preview
  with:
    path: .
    key: test-${{ runner.os }}-${{ hashFiles('**/README.md') }}
  continue-on-error: true

- name: Cache README.md
  uses: actions/cache@preview
  with:
    path: .
    key: test-${{ runner.os }}-${{ hashFiles('README.md') }}
  continue-on-error: true

- name: Cache *README.md
  uses: actions/cache@preview
  with:
    path: .
    key: test-${{ runner.os }}-${{ hashFiles('*README.md') }}
  continue-on-error: true
```

But right now `hashFiles(README.md)` and `hashFiles(*README.md)` fails macOS:

```
2019-11-02T18:08:19.8057240Z ##[error]The template is not valid. 'hashFiles(README.md)' failed. Search pattern 'README.md' doesn't match any file under '/Users/runner/runners/2.160.0/work/github-actions-hashfiles-test/github-actions-hashfiles-test'
2019-11-02T18:08:19.8346580Z ##[error]The template is not valid. 'hashFiles(*README.md)' failed. Search pattern '*README.md' doesn't match any file under '/Users/runner/runners/2.160.0/work/github-actions-hashfiles-test/github-actions-hashfiles-test'
```

And `hashFiles(README.md)` and `hashFiles(**/README.md)` fails Windows:

```
2019-11-02T18:09:01.2005576Z ##[error]The template is not valid. 'hashFiles(**/README.md)' failed. Search pattern '**/README.md' doesn't match any file under 'd:\a\github-actions-hashfiles-test\github-actions-hashfiles-test'
2019-11-02T18:09:01.2212553Z ##[error]The template is not valid. 'hashFiles(README.md)' failed. Search pattern 'README.md' doesn't match any file under 'd:\a\github-actions-hashfiles-test\github-actions-hashfiles-test'
```

See example repo: https://github.com/poiru/github-actions-hashfiles-test
And run: https://github.com/poiru/github-actions-hashfiles-test/commit/23dcdc7705d1660ba845291f744dd9b4a9157458/checks?check_suite_id=293065410

**Comment by poiru** [comment]
cc @joshmgross

**Comment by willnorris** [comment]
I've discovered that they need OS-specific path separators.  For Windows, try `hashFiles(**\README.md)`.

**Comment by willnorris** [comment]
I ended up setting up a completely separate job for my repo for other reasons (https://github.com/willnorris/imageproxy/pull/202/files).

But having separate caching steps that checked the OS worked as well.  Of course, this is almost certainly a bug that should be fixed upstream, but this will work in the meantime:

```yml
steps:

 - uses: actions/cache@preview
   if: runner.os != 'Windows'
   with:
      key: ${{ runner.os }}-${{ hashFiles('**/README.md') }}

 - uses: actions/cache@preview
   if: runner.os == 'Windows'
   with:
      key: ${{ runner.os }}-${{ hashFiles('**\README.md') }}
```

**Comment by shivammathur** [comment]
If path separator is exposed in the runner context, then it will be easy to setup on all OS with the same interface.

For example
```yml
- name: Cache *README.md
  uses: actions/cache@preview
  with:
    path: .
    key: test-${{ runner.os }}-${{ hashFiles(format('{0}{1}{2}', github.workspace, runner.separator ,'README.md')) }}
```

**Comment by joshmgross** [comment]
`hashFiles` will be updated soon so that relative paths are rooted at `github.workspace`, which will allow `hashFiles('README.md')`.

`/` not working on Windows is definitely a bug, ideally `/` would work on all platforms so that you wouldn't need a `runner.separator` variable.

**Comment by filipesilva** [comment]
Also seeing this on https://github.com/filipesilva/create-cljs-app. I have to setup a dual cache setup as well:

```
    - name: Cache yarn on unix
      if: matrix.os != 'windows-latest'
      uses: actions/cache@v1
      with:
        path: ~/.yarn-cache
        key: unix-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          unix-yarn-
    - name: Cache maven on unix
      uses: actions/cache@v1
      if: matrix.os != 'windows-latest'
      with:
        path: ~/.m2
        key: unix-m2-${{ hashFiles('**/shadow-cljs.edn') }}
        restore-keys: |
          unix-m2-
    - name: Cache yarn on windows
      if: matrix.os == 'windows-latest'
      uses: actions/cache@v1
      with:
        path: ~/.yarn-cache
        key: windows-yarn-${{ hashFiles('**\yarn.lock') }}
        restore-keys: |
          windows-yarn-
    - name: Cache maven on windows
      uses: actions/cache@v1
      if: matrix.os == 'windows-latest'
      with:
        path: ~/.m2
        key: windows-m2-${{ hashFiles('**\shadow-cljs.edn') }}
        restore-keys: |
          windows-m2-
```
