### ISSUE TITLE
Readme: PureScript spago example

### ISSUE THREAD

**Issue by andys8** [actions/cache#391]
It would be neat to have an example for PureScript with `spago` in the documentation.

### Example

```
- uses: actions/cache@v2
  with:
    path: .spago
    key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
    restore-keys: |
      ${{ runner.os }}-spago-
- uses: actions/cache@v2
  with:
    path: output
    key: ${{ runner.os }}-output-${{ hashFiles('**/*.dhall') }}
    restore-keys: |
      ${{ runner.os }}-output-
```
