### ISSUE TITLE
Multi-Path Caching Not working

### ISSUE THREAD

**Issue by Mordil** [actions/cache#392]
I am using the multi-path caching capabilities with v2 to cache multiple build directories in an iOS monorepo.

After loading the cache, I print the output of each path that should be cached, and after running the job that generates the files in the path, I output the contents of the path again.

Only the first path is getting cached.

Project Structure:
```
root/
  FrameworkA/
    Carthage/
  FrameworkB/
    Carthage/
  App/
    Carthage/
```
Workflow:
```yml
jobs:
  frameworkA:
    steps:
    # omitted for brevity ...
    - name: Load Dependency Cache
      uses: actions/cache@v2
      if: ${{ steps.changes_check.outputs.project_files_changed > 0 }}
      with:
        path: |
          ./FrameworkA/Carthage/
          ./FrameworkB/Carthage/
          ./App/Carthage/
        key: carthage-${{ hashFiles('./FrameworkA/Cartfile.resolved', './FrameworkB/Cartfile.resolved', './App/Cartfile.resolved') }}
    - name: Run Tests
      if: ${{ steps.changes_check.outputs.project_files_changed > 0 }}
      run: ./scripts/run_unit_tests.sh frameworkA

  frameworkB:
    needs: 'frameworkA'
    steps:
    # omitted for brevity ...
    - name: Load Dependency Cache
      uses: actions/cache@v2
      if: ${{ steps.changes_check.outputs.project_files_changed > 0 }}
      with:
        path: |
          ./FrameworkA/Carthage/
          ./FrameworkB/Carthage/
          ./App/Carthage/
        key: carthage-${{ hashFiles('./FrameworkA/Cartfile.resolved', './FrameworkB/Cartfile.resolved', './App/Cartfile.resolved') }}
    - name: Run Tests
      if: ${{ steps.changes_check.outputs.project_files_changed > 0 }}
      run: ./scripts/run_unit_tests.sh frameworkB
```

Both `frameworkA` and `frameworkB` are properly finding and restoring a cache for `FrameworkA/Carthage` but it is consistently not restoring the cache for `FrameworkB/Carthage` even though I can validate through simple `ls <path>` that the content is there

Example output from FrameworkB job:
```
Running 'ls ./FrameworkA/Carthage'
// ... output of content in the folder
Running 'ls ./FrameworkB/Carthage'
ls: ./FrameworkA/Carthage/Build/iOS: No such file or directory

// ... build that generates files in the cache path

Running 'ls ./FrameworkA/Carthage'
// ... output of content in the folder
Running 'ls ./FrameworkB/Carthage'
// ... output of content in the folder
```
