### ISSUE TITLE
Does not work with cocoapods in xcode project

### ISSUE THREAD

**Issue by Macmee** [actions/cache#401]
I have copied verbatim the example in this project's readme:

```
  - uses: actions/cache@v2
    with:
      path: Pods
      key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
      restore-keys: |
        ${{ runner.os }}-pods- 
   - name: Install Cocoapods
      run: |
        sudo gem install cocoapods
    - name: Install Dependencies
      run: |
        pod install
```

This seems to create the tar and restore it in builds:

(cache creation step output)

```
Post job cleanup.
/usr/bin/tar --use-compress-program zstd -T0 -cf cache.tzst -P -C /Users/runner/work/XX-Client/XX-Client --files-from manifest.txt
Cache saved successfully
```

(cache restore step output)

```
Run actions/cache@v2
Received 96468992 of 243563163 (39.6%), 88.2 MBs/sec
Received 243563163 of 243563163 (100.0%), 97.8 MBs/sec
Cache Size: ~232 MB (243563163 B)
/usr/bin/tar --use-compress-program zstd -d -xf /Users/runner/work/_temp/ddb2f514-fe97-4984-9cfa-63742142743a/cache.tzst -P -C /Users/runner/work/XX-Client/XX-Client
Cache restored from key: macOS-pod-2564531cf4c292cb6db7bba59c3911d250d2698b519c5683ce351624f89f4421
```

However `pod install` proceeds to install pods as if the Pods folder does not exist. I added a `ls` call afterwards and can confirm the Pods folder exists and has many subfolders which resemble pods. It would be nice if there was a way to explore the working directory from a shell after the build completes to collect more information, however that doesn't seem possible.

My best guesses around what's happening is:

1. perhaps the cache step is not caching all files for some reason (although the output does not suggest a failure occurred)
2. maybe the cache step is mangling file permissions somewhere and fastlane silently discards modules in that case
3. maybe caching just the Pods folder is insufficient, and there is another manifest file we need to cache too

**Comment by retyui** [comment]
```yml
   - name: Install Cocoapods
      run: |
        sudo gem install cocoapods
```
Actually macos-* runner already have cocoapods gem, just run `npx envinfo` to check a version

**Comment by Macmee** [comment]
true, but I am using a custom worker, my own mac mini. You can add your own workers in github actions settings for a project. They are significantly cheaper than github.

**Comment by jhonny-me** [comment]
I have the same situation here, the cocopoads cache doesn't seems to work as expectec, the cache hit is OK, but pod install still tooks that much time comparing to non-cached.

Hope someone can give an answer.

**Comment by retyui** [comment]
Did you cache all folders:
- `~/.cocoapods`
- `~/Library/Caches/CocoaPods`

```yml
    - uses: actions/cache@master
      with:
        path: ~/Library/Caches/CocoaPods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}

    - uses: actions/cache@master
      with:
        path: ~/.cocoapods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
```
