### ISSUE TITLE
Cache always hits even when the files change

### ISSUE THREAD

**Issue by e-minguez** [actions/cache#407]
I'm using GH actions to publish a static site that reflects the current OpenShift versions. The code generates a json file every time it is executed and then it renders an html file.
I use the cache action to cache the pip dependencies successfully and I want to use the cache to do the same but for the json file that is generated like so:

```
    - name: versions.json cache
      uses: actions/cache@v2.1.1
      env:
        cache-name: versions-json
      with:
        path: versions.json
        key: ${{ env.cache-name }}-${{ hashFiles('versions.json') }}
```

But it turns out that the cache always hits even if the file changes...

I've tried different combinations of the key such as `${{ env.cache-name }}-${{ hashFiles('**/versions.json') }}` but the cache is never 'refreshed'.

The repo is https://github.com/openshifttips/openshift-versions/ just in case.

Thanks!

**Comment by dhadka** [comment]
:wave: Hi @e-minguez Looking at the logs from one of your runs, the cache key is `versions-json-`.  Essentially, it's not matching the file `versions.json` when the restore step is run, probably because it doesn't yet exist.  The key is calculated only once during the restore step and is not reevaluated in the post cache (save) step.

Is there a different file, such as `requirements.txt`, that you could use in the key that would tell you when `versions.json` changes?

**Comment by e-minguez** [comment]
> wave Hi @e-minguez Looking at the logs from one of your runs, the cache key is `versions-json-`. Essentially, it's not matching the file `versions.json` when the restore step is run, probably because it doesn't yet exist. The key is calculated only once during the restore step and is not reevaluated in the post cache (save) step.
> 
Thanks for the quick answer! :)

> Is there a different file, such as `requirements.txt`, that you could use in the key that would tell you when `versions.json` changes?

No in the `master` branch... I can use the `index.html` in the `gh-pages` branch but IDK if actions/cache supports that?

**Comment by iranzo** [comment]
Will an empty version.json inside the repo work as an existing file to get cache working?

The version.json is updated by the python program when a new version exists, so the 'newer' version.json should be always stored

**Comment by dhadka** [comment]
@iranzo I don't think so.  The key would then be based off of the empty `versions.json` and it would just be restoring the same copy of `versions.json` each time.  Whereas, if I understand @e-minguez correctly, they want to update the cache with the new `versions.json` whenever it changes.  The following might work:

```
- name: versions.json ache
  uses: actions/cache@v2
  with:
    path: versions.json
    key: versions-json-${{ github.run_id }}
    restore-keys: version-json-
```

Since the key includes the run id, the key will change every time the action runs and also saves a new cache each time the action runs.  This way, you will always be saving the latest copy of `versions.json`.  The `restore-keys` then lets it restore this copy the next time the action runs.

But please note that this creates a new cache every run, which has its downsides... More time spent writing to the cache, filling up the cache storage quota faster, more frequent evictions, etc.

**Comment by iranzo** [comment]
Thing is that version.json will only be changing 'several times', should this then cover that case? not saving new versions.json if there has been no changes? 

(what we currently see with actual approach is that the file is not correctly restored so a new one is generated (and not saved) and a push to the github pages branch is done, where it should just 'skip it' if the proper versions.json from last run was used)

**Comment by dhadka** [comment]
@iranzo The example above with the `run_id` in the key should work for that scenario, but it will be saving to the cache each run even if `versions.json` doesn't change.

This is really a limitation of how (or more correctly: when) cache keys are calculated.  There is a feature request to address this (https://github.com/actions/cache/issues/135), but this hasn't been worked on yet as far as I know.

**Comment by e-minguez** [comment]
https://github.com/openshifttips/openshift-versions/commit/accdfb1fcb52118b900287ea4e35aa41ee7334e3

Let's see if that fixes it :) Thanks @dhadka and @iranzo !

**Comment by e-minguez** [comment]
It looks like the `github.run_id` variable did the trick :)
Final result looks like this:

```
    - name: versions.json cache
      uses: actions/cache@v2.1.1
      env:
        cache-name: cache-versions-json
      with:
        path: versions.json
        key: ${{ env.cache-name }}-${{ github.run_id }}
        restore-keys: ${{ env.cache-name }}-
```

Thanks!!!
