### ISSUE TITLE
Simplified configuration / templates

### ISSUE THREAD

**Issue by szepeviktor** [actions/cache#410]
Hello!

Currently it takes a lot of lines to configure `actions/cache`.

1. It takes some effort to understand
1. Easy to make a mistake
1. Looks ugly

Please consider introducing configuration templates.

e.g.

```yaml
- uses: actions/cache@v2
  with:
    config: npm-lock
```

or

```yaml
- uses: actions/cache@v2
  with:
    config: composer-json
```

`config` meaning the name of the template, not a file.

Thanks.
