### ISSUE TITLE
CACHE_UPLOAD_CHUNK_SIZE ignored?

### ISSUE THREAD

**Issue by johannesstricker** [actions/cache#415]
The post cache task continues to fail for my local runner because it seems to be hitting the 60secs upload timeout. I've tried to reduce the `CACHE_UPLOAD_CHUNK_SIZE` as mentioned in https://github.com/actions/cache/issues/259#issuecomment-627448818, but from the `start` and `end` of the uploaded chunk that you can see in the screenshot below, it appears to me that the chunk size is still the default 32mb.

![image](https://user-images.githubusercontent.com/12081471/93022195-2a5a4c00-f5e8-11ea-899c-05007ad74d17.png)

Here's the code of my cache step:
```
      - name: Cache vcpkg dependencies
        uses: actions/cache@v2
        env:
          CACHE_UPLOAD_CHUNK_SIZE: 4194304
        with:
          path: ${{ env.VCPKG_ARCHIVE_DIR }}
          key: ${{ matrix.generator }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ matrix.generator }}-
```

**Comment by dhadka** [comment]
Looks like that env var was removed when splitting the cache action into the cache module - https://github.com/actions/toolkit/commit/1413cd0e32562e29ebe9aa04d4b7176120890791#diff-f121c5607011c504c6934838327d2b8cR332

Created a PR to add this back as an input instead of an environment variable - https://github.com/actions/cache/pull/424

**Comment by dhadka** [comment]
@johannesstricker `v2.1.2` of this action (which also include the `v2` tag) includes this fix.  Should work with:

```
- name: Limit upload chunk size
  uses: actions/cache@v2
  with:
    path: **/node_modules
    key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    upload-chunk-size: 4000000
```
