### ISSUE TITLE
Does not work with nested paths

### ISSUE THREAD

**Issue by warent** [actions/cache#416]
Not sure if my config is wrong or if this breaks on nested paths. I'm using the action like so:

```yaml
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ~/.config/yarn/global/node_modules
          key: project-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            project-${{ runner.os }}-
```

It seems to have no problems building the cache, but it breaks when restoring it.

```
/bin/tar: app/node_modules/expo/node_modules: Cannot mkdir: No such file or directory
/bin/tar: app/node_modules/expo/node_modules: Cannot mkdir: No such file or directory
/bin/tar: app/node_modules/expo/node_modules/jsonfile: Cannot mkdir: No such file or directory
/bin/tar: app/node_modules/expo/node_modules: Cannot mkdir: No such file or directory
/bin/tar: app/node_modules/expo/node_modules/jsonfile/package.json: Cannot open: No such file or directory
/bin/tar: app/node_modules/expo/node_modules: Cannot mkdir: No such file or directory
/bin/tar: app/node_modules/expo/node_modules/jsonfile/utils.js: Cannot open: No such file or directory
/bin/tar: app/node_modules/expo/node_modules: Cannot mkdir: No such file or directory
/bin/tar: app/node_modules/expo/node_modules/jsonfile/LICENSE: Cannot open: No such file or directory
/bin/tar: app/node_modules/expo/node_modules: Cannot mkdir: No such file or directory
/bin/tar: app/node_modules/expo/node_modules/jsonfile/CHANGELOG.md: Cannot open: No such file or directory
/bin/tar: app/node_modules/expo/node_modules: Cannot mkdir: No such file or directory
/bin/tar: app/node_modules/expo/node_modules/jsonfile/README.md: Cannot open: No such file or directory
```

I get a spam like this for many many lines. It appears only to happen for nested directories, i.e `app/node_modules/{package}/node_modules` so I'm guessing that the cache is trying to unpack nested directories before creating the higher level ones.

Is there something I'm doing wrong or is this a bug with a workaround?
