### ISSUE TITLE
Cache decompression slow on Windows

### ISSUE THREAD

**Issue by craffael** [actions/cache#442]
For me decompression of a cache on Windows is much slower than on linux. A [360Mb cache](https://github.com/craffael/lehrfempp/runs/1288591548) takes
- only 10sec to download
- but 5 minutes to decompress!

The cache consists of many small files (e.g. the [boost library](https://www.boost.org/)) which probably affects performance negatively.

It seems that [appveyor switched to 7zip](https://www.appveyor.com/docs/build-cache/#cache-speed-vs-size-beta) to compress/decompress the cache exactly for performance reasons. Maybe this would also be on option for github actions that run on windows?

Also note that there was already a similar issue (#336) but it was fixed by improving network performance. Here the bottleneck is not the network but the decompression itself...

**Comment by Leseratte10** [comment]
I noticed that issue as well. I thought I could use the cache so I don't have to download the needed compilers and libraries for every run, but loading and extracting them from the cache takes way longer than just redownloading them. That makes the cache pretty useless for my use case.

**Comment by quanglam2807** [comment]
I also have this problem. I run the same job on Linux, macOS & Windows. And while macOS & Linux take less than 1 minutes, Windows takes almost 4 minutes.

**Comment by arvinxx** [comment]
Yes, I meet this problem too, the Windows cost almost 5mins every cache. It really a time waste !!!

**Comment by airglow923** [comment]
Experienced the same issue on Windows. Here's the config I used:

```yaml
- name: Get yarn cache directory
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

- name: Query yarn cache
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
```

On `ubuntu-lastest`:

![image](https://user-images.githubusercontent.com/37762634/107545536-5fee7a00-6c06-11eb-9d5c-153fd3badbd8.png)

On `windows-latest`:

![image](https://user-images.githubusercontent.com/37762634/107545596-71378680-6c06-11eb-83b8-68c631ac539a.png)

As you can see, that margin is extreme.
