### ISSUE TITLE
Cached executables are not executable

### ISSUE THREAD

**Issue by apaszke** [actions/cache#445]
Thanks a lot for the action, it's been a pleasure to use!

We're using the cache to store some precompiled Haskell artifacts, which include executable files. On Linux everything seems to be running smoothly, but from time to time the macOS build cache seems to get corrupted. Here's an example:
1. A new PR [triggers a CI run](https://github.com/google-research/dex-lang/runs/1259752439?check_suite_focus=true). For some reason the cache didn't work out (not a big deal), so the artifacts get recompiled. The executables get used in the later stages of the run, so they had to be built correctly.
2. An update to PR is pushed, [triggering another run](https://github.com/google-research/dex-lang/runs/1260270900?check_suite_focus=true). This one no longer rebuilds from scratch, but it almost immediately fails with the following error (`~/.stack` is part of the cache):
```
/Users/runner/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5: /Users/runner/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5: cannot execute binary file
```

I've been trying to debug this issue, but I'm running out of ideas for what might be going wrong. Is it possible that the macOS runners are using different CPU architectures? Is executable caching supported?

**Comment by BrightRan** [comment]
Here is a similar issue: https://github.community/t/caching-fails-when-bootstrapping-a-compiler-but-only-on-macos/140463

**Comment by Martinsos** [comment]
We are experiencing exactly the same problem! https://github.com/wasp-lang/wasp/runs/1399690381?check_suite_focus=true

**Comment by Martinsos** [comment]
Temporary fix I used is to add the following step right after the actions/step cache:

```yaml
# TODO: Remove this step once https://github.com/actions/cache/issues/445 is resolved.
- name: Fix MacOS problem with corrupt cached executable
  run: rm -r ~/.stack/setup-exe-cache
  if: runner.os == 'macOS'
```

My run where this worked: https://github.com/wasp-lang/wasp/runs/1399709311?check_suite_focus=true .
