### ISSUE TITLE
Use case: (PHP) composer cache

### ISSUE THREAD

**Issue by teohhanhui** [actions/cache#45]
In a PHP project using composer for managing project dependencies, we need the ability to cache the `$COMPOSER_HOME/cache/files` directory, and overwrite its contents by reusing the same cache key.

In other words, we need a way to save and update a globally shared cache, regardless of the contents of `composer.json` (`composer.lock` is not committed for a library), because that would result in stale cache that never gets updated after the first time it's written (not great for perfomance).

See https://github.com/travis-ci/travis-ci/issues/4579#issuecomment-127972205  for why caching the `vendor` directory is dangerous and not recommended.

**Comment by teohhanhui** [comment]
If we're able to use something like this, it'd work nicely:

```yaml
    - name: Cache composer packages
      uses: actions/cache@preview
      with:
        path: $COMPOSER_HOME/cache/files
        key: composer-${{ date('yyyy') }}-${{ date('mm') }}-${{ date('dd') }}-${{ hashFiles('composer.json') }}
        restore-keys: |
          composer-${{ date('yyyy') }}-${{ date('mm') }}-${{ date('dd') }}-
          composer-${{ date('yyyy') }}-${{ date('mm') }}-
          composer-${{ date('yyyy') }}-
          composer-
```

**Comment by teohhanhui** [comment]
Or does the fallback order already use the most recent key first?

**Comment by joshmgross** [comment]
Hey @teohhanhui, I see you closed this issue, did you get this figured out?

**Comment by teohhanhui** [comment]
I think it works just fine assuming that the fallback always uses the most recent cache key (so there's no need for a `date` function, though that might still be useful for other use cases).

But indeed it'd be great to have an additive cache (updating an existing cache key). In the case of composer, it means we could share the same cache in different jobs with different stability level for the dependencies (e.g. normal, lowest deps, and unstable).

**Comment by dhadka** [comment]
@teohhanhui You are correct, the fallback selects the most recently created cache that matches the restore key prefix.

**Comment by joshmgross** [comment]
We should have docs coming soon with more details. If you want the date, you do something with action outputs like:

```yaml
    - name: Set an output
      id: get-date
      run: |
        echo ::set-output name=date::$(/bin/date -u "+%Y%m%d")
    - name: Use the output
      run: |
        echo 'The output date is ${{ steps.get-date.outputs.date }}'
```
see the [docs on outputs](https://help.github.com/en/github/automating-your-workflow-with-github-actions/metadata-syntax-for-github-actions#outputs).

But as @dhadka said, you should be fine the fallback as is
