### ISSUE TITLE
After modifying `key`, `Cache not found for input keys: xxx` will not be thrown

### ISSUE THREAD

**Issue by liby** [actions/cache#453]
### Current Behavior

![image](https://user-images.githubusercontent.com/38807139/98445848-f10c0b80-2154-11eb-9937-6dce28627be0.png)

I modified `key`, but when I [run the workflow,](https://github.com/liby/auto-check-in/runs/1368001700?check_suite_focus=true) it still prompts me for `Cache restored from key: Linux-jd-node-modules-xxxx`.

According to the log, this is very similar to the behavior after the `restore-keys` has been set.
But what is confusing is that I do not configure `restore-keys`.

### Expected behavior

Isn’t it supposed to prompt me `Cache not found for input keys: Linux-jd-node-modules-`?

### Suggested solution(s)

After modifying `Key`, the cache should not be restored from the previous `key` when the workflow is run for the first time.

### Additional context

<details>
<summary>Before modification</summary>

```yml

    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
```
</details>

<details>
<summary>After modification</summary>

```yml

    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-
```
</details>
