### ISSUE TITLE
Access to .gradle/caches on windows-latest 

### ISSUE THREAD

**Issue by JakubMosakowski** [actions/cache#454]
Hi!

Cache actions seem not to be working with Gradle on the windows machine. Tar doesn't have an access to some files.

```
Post job cleanup.
C:\windows\System32\tar.exe --posix -z -cf cache.tgz -P -C D:/a/ItemistEvolved/ItemistEvolved --files-from manifest.txt
tar.exe: Couldn't open C:/Users/runneradmin/.gradle/caches/transforms-2/transforms-2.lock: Permission denied
tar.exe: Error exit delayed from previous errors.
Warning: Tar failed with error: The process 'C:\windows\System32\tar.exe' failed with exit code 1
```

```
name: Pull Request Workflow

on:
  pull_request:
    branches: [ develop ]

jobs:  
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Get gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

...
```
