### ISSUE TITLE
Split this action into save-cache and restore-cache actions

### ISSUE THREAD

**Issue by teohhanhui** [actions/cache#46]
Proposal: Split this action into two, similar to `actions/upload-artifact` / `actions/download-artifact` (also similar to what CircleCI does):

- actions/save-cache
- actions/restore-cache

Rationale: This will give the user a lot more control (e.g. I might want to save the cache even before running the test steps).

**Comment by wipe2238** [comment]
Why not add argument instead?

```yaml
- uses: actions/cache
  with:
    mode: load

# ...

- uses: actions/cache
  with:
   mode: save
```

**Comment by teohhanhui** [comment]
Not sure what that accomplishes. Also, AFAICT the official actions all start with verbs, because they're, well, actions.

**Comment by wipe2238** [comment]
If you fork this repo, you have just one upstream.
If you're writing complex pull request, you do it in one place.
If you find bug which requires both loading and saving in specific order to reproduce, you report it in one place instead of guessing which one fits best or writing in both.
If you want to use older version for any reason, you set one sha instead of two. And if you want to move to newer, but still not-so-fresh version, you just update that sha instead of tracking which changes in repository A will work with repository B.

That's what we have now, with one repo.

I like the idea of controlling when _exactly_ cache should be loaded/saved. But splitting repo for this is overkill. If that's what's needed to have more control (no idea honestly - not an actions writer yet, i stick to workflows for now), split load and save into two actions in separate **folders** which sounds like best of two worlds to me.
```yaml
- uses: actions/cache/load

# ...

- uses: actions/cache/save
```
