### ISSUE TITLE
Create action or command to explicitly write to cache part-way through the workflow

### ISSUE THREAD

**Issue by ben-spiller** [actions/cache#462]
Currently the cache action writes to the cache right at the end of the workflow in cleanup. This is a good default to help newbies, but it also really limits the usefulness and efficiency of the cache because:
- if a later step (e.g. test execution) fails the cache will not be populated, so until you get your workflow fully working, you have to endure many cycles of slow execution each time you push changes to the workflow (not benefitting from the cache), which slows down use of GitHub Actions considerably
- subsequent steps (e.g. test setup or execution) may contaminate the contents of the cache (requiring you to go through the extra complication of stashing a copy of your files mid-way through your workflow them and then caching that archive rather than just using the action in the natural way)

Both problems could be delightfully solved by adding a new action (as part of this project) that allows you to explicitly save to the cache e.g. 

```
      - uses: actions/cache@v2.1.3
        id: xxx
        with:
           path: xxx
           key: mykey
      - shell: bash
        if: steps.xxx.outputs.cache-hit != 'true'
        run: # shell command to populate ~/mycache go here

     # This would be the new bit
     # (an equally good option would be to expose this as a shell command you could invoke from bash/PS/cmd)
      - uses: actions/cache-write@v1.0.0
        if: steps.xxx.outputs.cache-hit != 'true'
        with:
           key: mykey

     # Now if the remaining workflow steps fail, I still have my cached data, so can benefit from fast and efficient dev cycles while I get my workflow working
    # Also if subsequent steps contaiminate the ~/mycache directory with other artifacts, my cache isn't affected
     - name: run tests
        
```
