### ISSUE TITLE
Saving cache can fail, breaking build (response 429/503)

### ISSUE THREAD

**Issue by vadi2** [actions/cache#467]
```
Post job cleanup.
/usr/bin/tar --posix --use-compress-program zstd -T0 -cf cache.tzst -P -C /Users/runner/work/Mudlet/Mudlet --files-from manifest.txt
Warning: Cache service responded with 429 during upload chunk.
/Users/runner/work/_actions/actions/cache/v2/dist/save/index.js:3305
                        throw new Error(`Cache upload failed because file read failed with ${error.message}`);
                        ^

Error: Cache upload failed because file read failed with EBADF: bad file descriptor, read
    at ReadStream.<anonymous> (/Users/runner/work/_actions/actions/cache/v2/dist/save/index.js:3305:31)
    at ReadStream.emit (events.js:210:5)
    at internal/fs/streams.js:167:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5)
```

See https://github.com/Mudlet/Mudlet/runs/1435372417?check_suite_focus=true

Cache itself is rather simple,

```
    - name: (Linux/macOS) restore ccache
      uses: actions/cache@v2
      with:
        path: ${{runner.workspace}}/ccache
        key: ccache-${{matrix.os}}-${{matrix.compiler}}-${{matrix.qt}}-${{github.sha}}
        restore-keys: ccache-${{matrix.os}}-${{matrix.compiler}}-${{matrix.qt}}-
      if: runner.os != 'Windows'
```
