### ISSUE TITLE
Cache when running job in container

### ISSUE THREAD

**Issue by JonasVautherin** [actions/cache#479]
I have been using the cache for different jobs (and I love it, thanks a lot :rocket:).

However, I have this one job that always gets `Cache not found for input keys: ...`, and that's the only one running in a container:

```
 alpine-linux:
    name: alpine 3.11.6 (musl)
    runs-on: ubuntu-18.04
    container: alpine:3.11.6
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: ./build/release/third_party/install
          key: ${{ github.job }}-${{ hashFiles('./third_party/**') }}
```

Could it be that the cache does not work in the `container:` configuration? And is it expected?
