### ISSUE TITLE
Add a parameter to ignore the existing cache but still store the cache at the end

### ISSUE THREAD

**Issue by cecton** [actions/cache#481]
# Feature Request

## Description

Add a parameter "no-restore" that will ignore the existing cache but still store the cache at the end of the job.

## Use Case

I'm building a Rust project and I try to keep a cache "main" that is used in fallback of PR if there is no pre-existing cache for that PR. In other words, newly created PR use this cache as "base".

Unfortunately the dependencies can change, the version of the compiler too, and the target (build) directory gets bigger over time.

I don't need a cache on the main branch, I only use it to accelerate the first build of the PR. So it would be nice to have a flag "no-restore" that would ignore the existing cache but still save and replace the cache at the end.

## Workaround

In the workflow that builds the main branch:

```yaml
      - name: Get main commit hash
        id: main_commit
        run: echo "::set-output name=hash::$(git rev-parse origin/main)"

      - name: Cache target, rustup and cargo registry
        id: cache-target
        uses: actions/cache@v2
        with:
          path: |
            ~/.rustup
            ~/.cargo/registry
            ~/.cargo/bin
            target
          key: main-${{ steps.main_commit.outputs.hash }}
```

In the workflow that builds the PR:

```yaml
      - name: Get main commit hash
        id: main_commit
        run: echo "::set-output name=hash::$(git rev-parse origin/main)"

      - name: Cache target, rustup and cargo registry
        id: cache-target
        uses: actions/cache@v2
        with:
          path: |
            ~/.rustup
            ~/.cargo/registry
            ~/.cargo/bin
            target
          key: ${{ github.event.issue.number }}-${{ runner.os }}-pr
          restore-keys: main-${{ steps.main_commit.outputs.hash }}
```
