### ISSUE TITLE
Cache receive fails at some point

### ISSUE THREAD

**Issue by ElGreetly** [actions/cache#482]
The cache continue to fail at some point 
![image](https://user-images.githubusercontent.com/38695215/101597209-72caaf80-3a07-11eb-9444-25d6dc986c15.png)

Code
```
- name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
```
