### ISSUE TITLE
"Unable to reserve cache with key"

### ISSUE THREAD

**Issue by fugkco** [actions/cache#485]
Hi, I've got a workflow where I'm using this action, however, it doesn't seem to be caching anything. I get the error:

```
Unable to reserve cache with key Linux-xmltv-cache, another job may be creating this cache.
```

Obviously, because of it, subsequent jobs do not find any caches.

Cache usage ([full workflow](https://github.com/fugkco/xmltv/blob/main/.github/workflows/download-xmltv-uk-tvguide.yml)):
```
      - name: XMLTV cache
        id: cache-xmltv
        uses: actions/cache@v2
        with:
          path: /config/.xmltv/cache
          key: ${{ runner.os }}-xmltv-cache
```

Link to [workflow](https://github.com/fugkco/xmltv/runs/1540287418?check_suite_focus=true)
