### ISSUE TITLE
"Can't unlink already-existing object" problem

### ISSUE THREAD

**Issue by sakirma** [actions/cache#492]
Hello,

I am trying to use this awesome tool, but there is one problem, which is "can't unlink already-existing object" and it takes forever before getting all the cache together.
This is interesting because I have never installed the msys2 before getting the cache back.

Here is an example of the error
![Screenshot 2020-12-22 232128](https://user-images.githubusercontent.com/14217365/102938358-756be100-44ac-11eb-8e53-da8808024fc3.png)

And here is the code I have used.

```
jobs:
  build-win:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true

      - uses: actions/checkout@v2
      - name: Check build folder cache
        uses: actions/cache@v2
        with:
          path: build/
          key: ${{ runner.os }}-cmake-${{ github.sha }}
          restore-keys: |
            ${{ runner.OS }}-cmake-

      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v2
        with:
          path: "C:/msys64/"
          key: ${{ runner.os }}-primes


      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Install msys2 dependencies
        if: steps.cache-primes.outputs.cache-hit != 'true'
        shell: msys2 {0}
        run: |
          pacman -S mingw-w64-x86_64-xerces-c --noconfirm
          pacman -S mingw-w64-x86_64-box2d --noconfirm
          pacman -S mingw-w64-x86_64-glfw --noconfirm
          pacman -S mingw-w64-x86_64-cmake --noconfirm
          pacman -S mingw-w64-x86_64-make --noconfirm
          pacman -S mingw-w64-x86_64-freetype --noconfirm
          pacman -S mingw-w64-x86_64-gcc --noconfirm


      - name: Build Project
        shell: msys2 {0}
        run: |
          cmake -S . -B ./build -G "MinGW Makefiles"

      - name: Build Executable
        run: |
          cd ./build
          C:/msys64/mingw64/bin/mingw32-make.exe

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: NightByte-Windows
          path: |
            build/bin
```
