### ISSUE TITLE
Cache not found for input keys

### ISSUE THREAD

**Issue by dschinkel** [actions/cache#493]
Not sure what I'm missing here:

```js
jobs:
  tests:
    name: Run all tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)yarn cache dir
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
```

![Screen Shot 2020-12-23 at 2 42 01 AM](https://user-images.githubusercontent.com/338798/102977399-8c203100-44c8-11eb-9f13-d927df015b2b.jpg)

**Comment by jsakas** [comment]
Same. Whats really weird is that I use the same config for multiple projects and in some it works, some it doesn't. 

```
    - name: Restore Cache
      id: cache-deps
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Install Dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        yarn install
```

```
Cache not found for input keys: Linux-yarn-1b6a7f6e83927fcd83e5a89ce8029cb02cc9d0a410abfdbfb7b48f78565a36fe, Linux-yarn-
```

**Comment by rhyek** [comment]
I just hit this issue during a pull request workflow. I am caching two things for my pnpm-based project: the pnpm store (sort of like npm cache) and node_modules. node_modules is only meant to be cached for the current GITHUB_SHA so that it doesn't transcend commits, but is used in all jobs within the workflow. However the pnpm store is supposed to be used between PRs and i consistently get the cache not found for input keys error:

```yaml
steps:
  - name: Cache pnpm store
    uses: actions/cache@v2
    with:
      path: ~/.pnpm-store
      key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
      restore-keys: |
        ${{ runner.os }}-pnpm-store-
  - name: Cache node_modules
    uses: actions/cache@v2
    with:
      path: '**/node_modules'
      key: ${{ runner.os }}-tests-node-modules-${{ github.sha }}
```
I thought that maybe the node_modules cache was getting so big it was pushing out the pnpm store one, but they are both around 50MB when they get saved according to the logs, so that's not it.

Output:
```
Run actions/cache@v2
  with:
    path: ~/.pnpm-store
    key: Linux-pnpm-store-daa48f5a4ec773032ddae1d149beb21f15bef5f424c45df10a2669205d4cae30
    restore-keys: Linux-pnpm-store-
  
  env:
    DOCKER_BUILDKIT: 1
Cache not found for input keys: Linux-pnpm-store-daa48f5a4ec773032ddae1d149beb21f15bef5f424c45df10a2669205d4cae30, Linux-pnpm-store-
```

*However*, if i disable the node_modules cache i can see that the pnpm store one is found every time. This is confusing.
