### ISSUE TITLE
Excluded sub directory not working

### ISSUE THREAD

**Issue by mustaphazorgati** [actions/cache#494]
Hey there!
The README.md provides an example where an excluded sub-path is provided. Unfortunately that sub-path still ends up in the cache.
Here is a modified example using the local maven repository.
```
- name: Cache multiple paths
  uses: actions/cache@v2
  with:
    path: |
      ~/.m2
      !~/.m2/pro/taskana
    key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
```

Reading out on the next (cached) build the files in `~/.m2/pro/taskana` are contained in the cache. The following adjustment didn't work either: 
```
- name: Cache multiple paths
  uses: actions/cache@v2
  with:
    path: |
      ~/.m2
      !~/.m2/pro/taskana/**
    key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
```

Is this a bug or am I having the wrong expectations? Our current workaround is to delete that subfolder in a dedicated step. It works, but is kinda annoying.
