### ISSUE TITLE
[Windows] tar: Refusing to overwrite archive

### ISSUE THREAD

**Issue by teqdruid** [actions/cache#504]
![image](https://user-images.githubusercontent.com/1498080/104111774-2fc85a00-529b-11eb-80ee-6520729728ff.png)

We're hitting an issue when [untar'ing a cached LLVM build](https://github.com/teqdruid/circt/runs/1675020492?check_suite_focus=true) on Windows:

```
llvm/lld/test/ELF/Inputs/aarch64-copy2.s: Refusing to overwrite archive
tar.exe: Error exit delayed from previous errors.
```
I'm reporting two bugs:

1) The above error. I don't know what's special about this file. This part of the workflow works when we don't hit in the cache. (This is a new workflow which I'm still debugging.)

2) As a result of this warning, the `cache-hit` output variable isn't being set but the cache has been at least partially restored, resulting in an error in the rebuild step. The intuitive behavior in case of this error is to fail in the cache step. Alternatively, don't fail, don't set cache-hit, but clean up the (partially) restored files. This second option would be tricky since in this case it's overwriting the source files and adding the build outputs.

Here's the relevant excerpt of the workflow:

```
      # Try to fetch LLVM from the cache.
      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: llvm
          key: ${{ runner.os }}-llvm-rel-${{ steps.get-llvm-hash.outputs.hash }}

      # Build LLVM if we didn't hit in the cache. Even though we build it in
      # the previous job, there is a low chance that it'll have been evicted by
      # the time we get here.
      - name: Rebuild and Install LLVM
        if: steps.cache-llvm.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          mkdir llvm/build
          ...
```
