### ISSUE TITLE
Restored cache does not have all composer dependencies

### ISSUE THREAD

**Issue by oranges13** [actions/cache#511]
I had several successful builds with my composer dependencies cached between runs, but now it is pulling a bad cache file and the build will not complete.

![Screen Shot 2021-01-21 at 11 20 55 PM](https://user-images.githubusercontent.com/755110/105446049-53968300-5c3f-11eb-87c1-06e12c0ea0f3.png)

For reference, here is my action file:

```yml
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: composer run-script test

```

**Comment by dhadka** [comment]
:wave: From the screenshot, it shows it only received 22 bytes, which is essentially an empty `.tar.zstd` file.  As such, the likely culprit is that the path being cached, `vendor`, is not correct.  Our example shows how to lookup the composer cache directory:

https://github.com/actions/cache/blob/main/examples.md#php---composer

```
- name: Get Composer Cache Directory
  id: composer-cache
  run: |
    echo "::set-output name=dir::$(composer config cache-files-dir)"
- uses: actions/cache@v2
  with:
    path: ${{ steps.composer-cache.outputs.dir }}
    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
    restore-keys: |
      ${{ runner.os }}-composer-
```

I would recommend updating your workflow to follow this example.  You will also want to change the `key` and `restore-key` to force it to create a new cache (otherwise it will continue trying to restore the empty cache).
