### ISSUE TITLE
v2 not working for Elixir, v1 does

### ISSUE THREAD

**Issue by Hermanverschooten** [actions/cache#515]
I created a workflow to test my elixir code using a cache for the folders `deps` and `_build` in 2 steps.
After the first successful run, I can see the cache getting hit, but my compile step still runs all the way.
I spent more than hour trying different variations of my `mix` commands, but every time the compilation of the deps ran.
I looked at another project erlef/website, and saw they did not have this issue and were using v1.
So I changed my workflow to v1, and lo and behold, the second run, ran as it supposed to.
So something in the v2 cache file is missing/corrupt?
I ran a test with `ls -lR` before and after `mix compile` the output/timestamps all looked the same.
I did however want to notify you of this.

This works, but if you change to actions/cache@v2, `mix compile` jumps from 17s to 1m40s.
```yaml
      - name: Cache mix deps
        uses: actions/cache@v1
        env:
          cache-name: mix-deps
        with:
          path: deps
          key: ${{ runner.os }}-${{ env.otp-version }}-${{ env.elixir-version }}-${{ env.cache-name }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock'))}}
      - name: Cache build
        uses: actions/cache@v1
        env:
          cache-name: mix-build
        with:
          path: _build
          key: ${{ runner.os }}-${{ env.otp-version }}-${{ env.elixir-version }}-${{ env.cache-name }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock'))}}
```
