### ISSUE TITLE
use cache of non container job in container job

### ISSUE THREAD

**Issue by monotek** [actions/cache#520]
I cant use the created cache inside a container job, if the cache was created in an non container job.

The error is see in the container job "js-jest" is:

``` 
/usr/bin/docker exec  d681d1c1d1bcf898d5a7572538c549201c3d35aa22e366f14085ed1681753d31 sh -c "cat /etc/*release | grep ^ID"
Cache not found for input keys: Linux-node--d427a8aabcc0acf518e5cf6e5e4f3541ac6d9d8b4d3d10b1e26d8704b65748f7, Linux-node-
```

The non container "prettier" job uses the cache and works. Even if its not realy used here i've added an "ls -al" to the run part so i could see, that the cache was there.

This is the whole workflow config:

```
name: ci

on:
  pull_request:

jobs:
  install-npm:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10.19'
      - uses: actions/cache@v2
        id: cache-npm
        with:
          path: |
            .env
            .npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: run npm
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: |
          make
          npm ci --no-progress


  js-jest:
    container:
      image: specialpurposecontainer:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
    needs: install-npm
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10.19'
      - uses: actions/cache@v2
        id: cache-npm
        with:
          path: |
            .env
            .npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: run npm
        run: npm run test:ci


  prettier:
    needs: install-npm
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10.19'
      - uses: actions/cache@v2
        id: cache-npm
        with:
          path: |
            .env
            .npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: run npm
        run: npm run prettier
```

If there is some special config needed to use the cache inside the container, i would be glad if somebody could share it.

What seems to be a workaround is to run all jobs in containers but that makes ci slower.
