### ISSUE TITLE
"Cache already exists" despite "Cache not found"

### ISSUE THREAD

**Issue by aherrmann** [actions/cache#524]
I've observed the "Post Mount" step [state](https://github.com/tweag/rules_haskell/runs/1813986363?check_suite_focus=true#step:13:2)
```
Warning: Cache already exists. Scope: refs/heads/bump-cache, Key: repo-cache-macOS-nixpkgs-1, Version: (null)
```
while the "Mount" step [states](https://github.com/tweag/rules_haskell/runs/1813986363?check_suite_focus=true#step:3:7)
```
Cache not found for input keys: repo-cache-macOS-nixpkgs-1.
```

The cache is [configured as follows](https://github.com/tweag/rules_haskell/actions/runs/530328788/workflow#L17-L21)
```
      - name: Mount Bazel cache
        uses: actions/cache@v1
        with:
          path: ~/repo-cache
          key: repo-cache-${{ runner.os }}-nixpkgs-${{ env.cache-version }}
```
with
```
env:
  # Bump this number to invalidate the GH actions cache
  cache-version: 1
```

This is the third run on this branch and commit. (Unfortunately, I don't know how to access the logs of the first two runs anymore.)
1. The first run failed with an error in the build step (rate limit on GH API).
2. The second step succeeded but the cache upload step failed with 503, possibly https://github.com/actions/cache/issues/259.
3. The third step succeeded but cache download and upload behave inconsistently as described above.
