### ISSUE TITLE
cache-hit null when no cache hit

### ISSUE THREAD

**Issue by matshou** [actions/cache#533]
Variable `cache-hit` doesn't seem to be set when there was no actual cache hit.
I am expecting the variable to have a boolean value `false` when no hit occurred.

It is very possible I am doing something wrong in my code, but I decided to report this just to be on the safe side.
If there really is a bug with the action itself then the report will be of some help,

Workflow example:
```yaml
# Pull java compile output from cache
- name: Cache build files
  id: cache-build
  uses: actions/cache@v2
  with:
    path: |
      ./build/classes
      ./build/resources
      ./buildSrc/build
    key: ${{ runner.os }}-${{ github.sha }}

 # Check if cache was pulled correctly
- name: Validate cache
  id: cache-validate
  run: |
    echo Validating build cache...
    echo cache_hit: ${{ steps.cache-build.outputs.cache-hit }}
    if [ "${{ steps.cache-build.outputs.cache-hit }}" = false ]; then
        echo ::set-output name=fail::true
        echo ::error Build files were not pulled from cache
    fi
```
Server console log:
```
Run actions/cache@v2
  with:
    path: ./build/classes
  ./build/resources
  ./buildSrc/build
  
    key: Linux-acdbd26a92466c7c492eec0bf78b9c2467605168
  env:
    JAVA_HOME_8.0.282_x64: /opt/hostedtoolcache/jdk/8.0.282/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.282/x64
    JAVA_HOME_8_0_282_X64: /opt/hostedtoolcache/jdk/8.0.282/x64
Cache not found for input keys: Linux-acdbd26a92466c7c492eec0bf78b9c2467605168

Validating build cache...
cache_hit:
```
