### ISSUE TITLE
Error: Input required and not supplied: key - Even when Key provided

### ISSUE THREAD

**Issue by ciaranevans** [actions/cache#536]
Hi Folks,

I've got the following step:

```
- name: Setup root cache
  uses: actions/cache@v2
  id: root-cache
  with:
    path: '~/.local/share/virtualenvs/a-name*'
    key: ${{ hashFiles('~/a-name/a-name/Pipfile.lock') }}
```

Which keeps erroring with:

```
Run actions/cache@v2
  with:
    path: ~/.local/share/virtualenvs/a-name*
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.6/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.6/x64/lib
Error: Input required and not supplied: key
```

I can't for the life of me see why this is failing? The file exists, the reason I have the wildcard in the `path` value is that Pipenv assigns random characters after the directory name (eg. `a-name-7dsf85`).

Any thoughts?

Appreciate it!
