### ISSUE TITLE
cache can't find key which it previously declared is saved

### ISSUE THREAD

**Issue by ahmadnassri** [actions/cache#544]
I have the following configuration:

```yaml
      - uses: actions/cache@v2.1.4
        with:
          key: ${{ hashFiles('**/package-lock.json') }}
          path: |
            ~/.npm
            ~/.turtle
            ~/.gradle/wrapper
            node_modules
```

in the most recent successful runs, I get the following output indicating it successfully stored the cache:

![image](https://user-images.githubusercontent.com/183195/109074263-8a8c0880-76c5-11eb-84bc-a6721687f596.png)

then in subsequent runs it declares it can't find a cache entry for the **same key**:

![image](https://user-images.githubusercontent.com/183195/109074328-a0013280-76c5-11eb-8004-f0e237b0843f.png)

at the end of the run, it saves the results ... again under the same key, and they problem continues at the next run.

which means caching is doing nothing for me here?
