### ISSUE TITLE
Path wrong in windows when post job

### ISSUE THREAD

**Issue by AChenQ** [actions/cache#546]
here is my config
```
      - name: Cache python 3.6.8 in windows
        if: startsWith(matrix.os, 'windows')
        uses: actions/cache@v2
        with:
          path: C:\hostedtoolcache\windows\Python\3.6.8
          key: ${{ runner.os }}-3.6.8-${{ hashFiles('requirements.txt') }}
      - name: Set up Python 3.6.8 
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.8
```
log in my github action
```
Run actions/cache@v2
  with:
    path: C:\hostedtoolcache\windows\Python\3.6.8
    key: Windows-3.6.8-y-1d5e0cabad4cf8994f959aa20d20389ca809c932e4bf79db4f1393b3bef505a5
  env:
    TMPDIR: D:\a\_temp
    HOME: C:\Users\runneradmin
    MSYS2_PATH_TYPE: inherit
    MAKE: make.exe
    Path: C:\Users\runneradmin\.dotnet\tools;C:\Program Files\MongoDB\Server\4.4\bin;C:\aliyun-cli;C:\vcpkg;C:\cf-cli;C:\Program Files (x86)\NSIS\;C:\Program
Cache not found for input keys: Windows-3.6.8-y-1d5e0cabad4cf8994f959aa20d20389ca809c932e4bf79db4f1393b3bef505a5
...
Post job cleanup.
C:\msys64\usr\bin\tar.exe --posix --use-compress-program "zstd -T0" -cf cache.tzst -P -C D:/a/tensorbay-python-sdk/tensorbay-python-sdk --files-from manifest.txt --force-local
/usr/bin/tar: C\:\\hostedtoolcache\\windows\\Python\003.6.8: Cannot stat: No such file or directory
/usr/bin/tar: Exiting with failure status due to previous errors
Warning: Tar failed with error: The process 'C:\msys64\usr\bin\tar.exe' failed with exit code 2
```

The path is right when a try to cache files
but I don't know why there are two more zeros before 3.6.8 when I post job
Has any body can help me 🙏
