### ISSUE TITLE
Restoring cache duration went up from 3m 3s to 1h 40m for v2.1.5

### ISSUE THREAD

**Issue by emanuelschmoczer** [actions/cache#566]
On our builds running on `macOS-latest` we can see a sizeable increase in the duration when restoring a cache. Restoring our cocoapods spec cache now takes 1h 40m instead of the 3m 3s it took before. The cache size is roughly `Cache Size: ~1012 MB (1060687930 B)`

Here is the step from our workflow:
```yml
      - name: Restore cached CocoaPod Spec Repos
        uses: actions/cache@v2
        env:
          cache-name: cache-cocoapods-spec-repos
        with:
          path: ~/.cocoapods/repos
          key: ${{ env.cache-name }}-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: ${{ env.cache-name }}-
```

Downgrading to v2.1.4 resolved the problem for us.
