### ISSUE TITLE
If 'path' Doesn't Match It Results in a Cache Miss

### ISSUE THREAD

**Issue by StephenMP** [actions/cache#572]
If you have the following config:

```yaml
name: Example
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  some-job:
    name: Some Job
    runs-on: ubuntu-latest
    steps:
      - name: Setup some cache
        id: some-cache
        uses: actions/cache@v2
        with:
          key: some-key
          path: | 
            **/this/path
            **/that/path

      # Do stuff that populates the paths in the cache

  some-second-job:
    name: Some Second Job
    runs-on: ubuntu-latest
    needs: [some-job]
    steps:
      # Results in a cache MISS
      - name: Get some cache
        id: some-cache
        uses: actions/cache@v2
        with:
          key: some-key
          path: | 
            **/this/path

  some-third-job:
    name: Some Third Job
    runs-on: ubuntu-latest
    needs: [some-job]
    steps:
      # Results in a cache HIT
      - name: Get some cache
        id: some-cache
        uses: actions/cache@v2
        with:
          key: some-key
          path: | 
            **/this/path
            **/that/path
```

On `some-second-job` you will receive a cache miss because the specified paths don't match; however, on some-third-job you will get a cache hit since the paths do match. Nowhere in the documentation does it specify that the scoping of the cache is also depending on the `path` list matching.

It would be good if either:

1. The docs would be updated to include the `path` arguments needing to match to get cache hits
2. The action is updated to allow you to specify one or more of the paths provided to restore. For example, if you cached the paths `**/this/path` and `**/that/path` that you would be able to, in a later job, only restore `**/this/path` from the cache if it's the only cached path that specific job needed.
