### ISSUE TITLE
Restoring cache on Windows created on Linux silently fails if GNU tar is not on Windows Path

### ISSUE THREAD

**Issue by sebthom** [actions/cache#576]
I setup a CI pipeline where a linux job downloads files from a remote repository and puts them into a cache.
Then jobs on different platforms (linux, macos, windows) are started that reference the cache.
All jobs receive a cache hit but on Windows the downloaded cache archive is empty.

It looks like on Windows the filename `cache.tgz` is expected but on Linux and MacOS `cache.tzst` is used.

These are the logs I get for the jobs using the cache:
```
Linux:
------
Run actions/cache@v2
  with:
    path: .extensions
    key: extensions-802592892
    restore-keys: extensions-
Received 129569068 of 129569068 (100.0%), 136.2 MBs/sec
Cache Size: ~124 MB (129569068 B)
/usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/8f4a3549-d2e9-4b85-a044-4c0d37f47d60/cache.tzst -P -C /home/runner/work/vitcode/vitcode
Cache restored successfully
Cache restored from key: extensions-802592892

MacOS:
------
Run actions/cache@v2
  with:
    path: .extensions
    key: extensions-802592892
    restore-keys: extensions-
Received 129569068 of 129569068 (100.0%),  45.9 MBs/sec
Cache Size: ~124 MB (129569068 B)
/usr/local/bin/gtar --use-compress-program zstd -d -xf /Users/runner/work/_temp/d133514d-3d07-4e10-8844-14d51d463fff/cache.tzst -P -C /Users/runner/work/vitcode/vitcode --delay-directory-restore
Cache restored successfully
Cache restored from key: extensions-802592892

Windows:
--------
Run actions/cache@v2
  with:
    path: .extensions
    key: extensions-802592892
    restore-keys: extensions-
Received 30 of 30 (100.0%), 0.0 MBs/sec
Cache Size: ~0 MB (30 B)
C:\Windows\System32\tar.exe -z -xf D:/a/_temp/7133fe6d-5fa6-462d-a494-8faa9cdd0b31/cache.tgz -P -C D:/a/vitcode/vitcode
Cache restored successfully
Cache restored from key: extensions-802592892
```

Pseudo pipeline config:

```yaml
name: Build

jobs:
  download-extensions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: .extensions
        key: extensions-${{ github.run_id }}
        restore-keys: extensions-
    - name: "Downloading Extensions"
      shell: bash
      run: ... # execute commands that download files to ./.extensions

  build-on-linux:
    runs-on: ubuntu-latest
    needs: [ download-extensions ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: .extensions
        key: extensions-${{ github.run_id }}
    - name: "Build"
      # ... build software

  build-on-macos:
    runs-on: macos-latest
    needs: [ download-extensions ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: .extensions
        key: extensions-${{ github.run_id }}
    - name: "Build"
      # ... build software

  windows-amd64:
    runs-on: macos-latest
    needs: [ download-extensions ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: .extensions
        key: extensions-${{ github.run_id }}
    - name: "Build"
      # ... build software
```

**Comment by sebthom** [comment]
As a workaround I am now adding the GNU tar to the PATH before downloading the cache on windows:
```yaml
  windows-amd64:
    runs-on: macos-latest
    needs: [ download-extensions ]
    steps:
    - name: "Use GNU tar instead BSD tar"
      shell: cmd
      run: echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: .extensions
        key: extensions-${{ github.run_id }}
    - name: "Build"
      # ... build software
```
