### ISSUE TITLE
Is there a way to store cache after some special step and then continue workflow ?

### ISSUE THREAD

**Issue by kuvaldini** [actions/cache#587]
I have a job with the steps like:
```yaml
job:
  steps:
    - checkout
    - actions/cache@v2
    - build
    #- I'd like to store cache at this moment 
    - test
```

Is there a way to store cache after some special step and then continue workflow ?
