### ISSUE TITLE
Sbt / ivy2 example

### ISSUE THREAD

**Issue by niklasf** [actions/cache#59]
Please provide an example for a Scala project built using sbt.

**Comment by YashMathur** [comment]
There may be a better way to do this that involves hashing the files to break it up into multiple caches, but here's what I'm doing right now -
```
- name: Cache Scala artifacts
  uses: actions/cache@v1
  id: cache
  with:
    path: ~/.ivy2/cache
    key: ${{ runner.os }}-ivy2
    restore-keys: |
      ${{ runner.os }}-ivy2
```
