### ISSUE TITLE
Post job cleanup cost too much time even "Cache hit occurred on the primary key ***, not saving cache."

### ISSUE THREAD

**Issue by Jack-Works** [actions/cache#597]
I'm trying to optimize our build time by cache TypeScript build cache and Webpack build cache. Things work well,

TypeScript build time 1m35 => 16s, Webpack build 5m52s => 2m22s

But the total time does not short for too much, I found out the problem is the post-job cleanup of this action.

![image](https://user-images.githubusercontent.com/5390719/120267357-60567200-c2d6-11eb-9bf7-7f8ee0832aa3.png)

All primary keys hits and no new cache updated but it spent 2m17s~ to complete the job. I think that is very strange.

> Cache hit occurred on the primary key Linux-tsc-9f9d320e088153c498989178930188d8c3218d8d5921cf20ed323ba65b15e6a6-248906890a0a9fa80321c42138766476a0f139c60d2b1662e35c1ae1bf76a10e-20210601, not saving cache.

If it is the case, I expect it will complete in 5 seconds.

Here is our config:

```yaml
- uses: actions/cache@v2
  with:
    path: ~/.pnpm-store
    key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
    restore-keys: ${{ runner.os }}-node-
- uses: actions/cache@v2
  with:
    path: "**/dist/"
    # actions/cache will not upload changes in cache if primary key hits
    # by adding date to the primary key, we can ensure the cache updates on the first build of the day
    key: ${{ runner.os }}-tsc-${{ hashFiles('**/tsconfig.json') }}-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ steps.get-date.outputs.date }}
    # Allow fallback to cache of different dependencies but not allowing fallback to different tsconfig
    # because that might indicates a structural/flags changes in tsc emit.
    restore-keys: |
      ${{ runner.os }}-tsc-${{ hashFiles('**/tsconfig.json') }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      ${{ runner.os }}-tsc-${{ hashFiles('**/tsconfig.json') }}
- uses: actions/cache@v2
  with:
    path: ./packages/maskbook/node_modules/.cache/webpack/
    key: ${{ runner.os }}-webpack-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ steps.get-date.outputs.date }}
    # Not fallback to different dependencies. Webpack seems like have bug.
    # An example caused by the webpack cache bug: https://github.com/facebook/react/issues/21587
    restore-keys: |
      ${{ runner.os }}-webpack-${{ hashFiles('**/pnpm-lock.yaml') }}
```

The problematic action: https://github.com/DimensionDev/Maskbook/pull/3279/checks?check_run_id=2715205805
