### ISSUE TITLE
Yarn restores cache, but does not install from it

### ISSUE THREAD

**Issue by glambert** [actions/cache#60]
Hey team!

First, awesome job on this feature, it will immensely help our CI speed for our JavaScript projects, kudos! 

I've been running on the "over the limit" error for a yarn project with workspaces enabled:

```
Post job cleanup.
/bin/tar -cz -f /home/runner/work/_temp/3c08f6f0-f11f-4d8f-bed5-d491e7d8d443/cache.tgz -C /home/runner/.cache/yarn .
##[warning]Cache size of 231440535 bytes is over the 200MB limit, not saving cache.
```

But when I run the same `tar` command locally, I get a 100.3 MB bundle. Is there anything I'm missing here?

Here's my workflow:

```yaml
name: Test
on:
  push:
    branches:
      - '**'
    tags:
      - '!**'
jobs:
  test:
    name: Test, lint, typecheck and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Use Node.js 10.16.0
        uses: actions/setup-node@v1
        with:
          node-version: 10.16.0
      - name: Cache yarn node_modules
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.OS }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: yarn install --frozen-lockfile
        # ...
```

Thanks a lot!

**Comment by glambert** [comment]
As a follow-up, if I use `path: node_modules` it does save the cache successfully:

```
Cache yarn node_modules1s
Cache not found for input keys: ["Linux-yarn-db9ae0b40b59cc89d84b533d906606822c72106dfc77455cf7eee198d6e55858","Linux-yarn-"].
Run actions/cache@v1
  with:
    path: node_modules
    key: Linux-yarn-db9ae0b40b59cc89d84b533d906606822c72106dfc77455cf7eee198d6e55858
    restore-keys: Linux-yarn-
  
Cache not found for input keys: ["Linux-yarn-db9ae0b40b59cc89d84b533d906606822c72106dfc77455cf7eee198d6e55858","Linux-yarn-"].
```

...

```
Post Cache yarn node_modules27s
Cache saved successfully
Post job cleanup.
/bin/tar -cz -f /home/runner/work/_temp/86ca5e8a-8003-4159-b3a0-36827075ec88/cache.tgz -C /home/runner/work/web-tools/web-tools/node_modules .
Cache saved successfully
```

Could that be related?

**Comment by glambert** [comment]
With the recent increase to 400MB now it does save the cache, but `yarn` still does not seem to pick up the cache from `~/.cache/yarn` and still does a clean install. If I do `yarn cache dir` it outputs `/home/runner/.cache/yarn/v6`.

**Comment by joshmgross** [comment]
It's possible there's additional content in `~/.cache/yarn` that's leading to the file size discrepancy between local and the runner. It could be something populated during `actions/setup-node`.

`~/.cache/yarn` may not work for all scenarios, and a better example could use `yarn cache dir` to determine the path and accessing that via an output.

Example:
```YAML
- name: Get Yarn Cache Directory
  id: yarn-cache
  run: |
    echo "::set-output name=dir::$(yarn cache dir)"
- uses: actions/cache@v1
  with:
    path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.OS }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
```

**Comment by glambert** [comment]
Trying it out right now, thanks a lot for the fast reply :+1:

**Comment by glambert** [comment]
```
Run echo "::set-output name=dir::$(yarn cache dir)"
::set-output name=dir::/home/runner/.cache/yarn/v6
```

Then

```
Run actions/cache@v1
/bin/tar -xz -f /home/runner/work/_temp/3b300616-8bbe-4e56-b10d-dcbc31bbca18/cache.tgz -C /home/runner/.cache/yarn/v6
::set-output name=cache-hit,::true
Cache restored from key: Linux-yarn-db9ae0b40b59cc89d84b533d906606822c72106dfc77455cf7eee198d6e55858
```

But install still takes over 2min to run with. Full thing:

```
- name: Use Node.js 10.16.0
        uses: actions/setup-node@v1
        with:
          node-version: 10.16.0
      - name: Get Yarn Cache Directory
        id: yarn-cache
        run: |
          echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.OS }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: yarn install --frozen-lockfile
```
