### ISSUE TITLE
Swift Package Cache not working

### ISSUE THREAD

**Issue by BrentMifsud** [actions/cache#606]
my workflow:

```yml
name: CI

on:
  pull_request:
    branches: [master, develop]

jobs:
  Build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          token: ${{ secrets.MyToken }}
      - name: Cache Swift Packages    
        uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: List available Xcode versions
        run: ls /Applications | grep Xcode
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_12.4.app
      - name: Remove SSH
        run: rm ~/.ssh/id_rsa || true
      - name: Add Github to known hosts
        run:  for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts || true
      - name: Add CI SSH Key
        run: ssh-add - <<< "${{ secrets.Key }}"
      - name: Show Build Destinations
        run: xcodebuild -showdestinations -scheme RideRecordSDK
      - name: Build
        run: xcodebuild test -scheme MyPackage -destination 'platform=iOS Simulator,OS=14.4,name=iPhone 12'
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Lint
        uses: norio-nomura/action-swiftlint@3.2.1
```

Whenever I run the GitHub action I get the following: 

![image](https://user-images.githubusercontent.com/18543934/125690458-50978470-0aa2-4aac-ac95-8a4429d396e5.png)

Has anyone managed to setup a swift package cache successfully?
