### ISSUE TITLE
Post-mount not uploading if location is in %LOCALAPPDATA%

### ISSUE THREAD

**Issue by gjasny** [actions/cache#611]
Hello,

judging from the [examples](https://github.com/actions/cache/blob/main/examples.md#windows-1) the cache path could be relative to an environment variable like:

```yaml
path: |
  %LOCALAPPDATA%\vcpkg\archives
  ~/.cache/vcpkg/archives
``` 

However the post-mount step does not archive any data. I created a [testcase](https://github.com/gjasny/action-cache-testcase) with the following action file:
```yaml
name: Continuous Integration
on: [push]

jobs:
  cmake:
    name: CMake ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-2019]

    steps:
      - name: Mount vcpkg cache
        uses: actions/cache@v2
        with:
          path: |
            %LOCALAPPDATA%\vcpkg\archives
            ~/.cache/vcpkg/archives
          key: vcpkg-${{ matrix.os }}

      - name: Install vcpkg dependencies
        run: vcpkg install benchmark

      - name: "Dump localappdata"
        if: runner.os == 'Windows'
        run: dir -r ${Env:LOCALAPPDATA}\vcpkg\archives
```

The Ubuntu job successfully caches the content, the windows job does not.

Could you please take a look?

Thanks,
Gregor
