### ISSUE TITLE
npm cache is not found / Cache not found for input keys

### ISSUE THREAD

**Issue by judocode** [actions/cache#621]
We just started getting the error "npm cache not found" yesterday. Full console output:

```
Attempting to download 14.16.1...
Acquiring 14.16.1 - x64 from https://github.com/actions/node-versions/releases/download/14.16.1-725059535/node-14.16.1-linux-x64.tar.gz
Extracting ...
/bin/tar xz --strip 1 --warning=no-unknown-keyword -C /home/runner/work/_temp/fb4b9def-a426-4bcb-82a5-4ab097a031ad -f /home/runner/work/_temp/d2b7a61e-3a02-4dd4-8e53-9b1b17dc69dd
Adding to the cache ...
Done
/opt/hostedtoolcache/node/14.16.1/x64/bin/npm config get cache
/home/runner/.npm
npm cache is not found
```

In our github actions, we have defined the setup-node step as follows:
```
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.16.1'
          cache: 'npm'
```

We also have a repository that is using v1.4.4 of setup-node in tandem with v2 of actions/cache:
```
      - name: Configure NPM Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
```

and this is outputting the error: "Cache not found for input keys: Linux-node-3c29296f6131c0b2833531978262b4146776b599209e22d5bd1f2533eec51679, Linux-node-"

We have also attempted to use a combination of different versions of setup-node/cache but continuously get the same error, even after npm install is successful.

In the README, it describes the cache limits:

"A repository can have up to 5GB of caches. Once the 5GB limit is reached, older caches will be evicted based on when the cache was last accessed. Caches that are not accessed within the last week will also be evicted."

The cache was successfully hit minutes before in a previous build, so it seems very hard to believe that cache was evicted. Is there a way to determine whether a cache was evicted because of the 5GB limit? Is there anything else that can cause an eviction of cache? Is there an underlying bug that caused this?

**Comment by slavafomin** [comment]
I'm experiencing a similar behavior. The `advancedcsg-open/actions-rush` action is not using the cache. Also, when I try to use the cache manually, it's created in one job, but can't be found in another.

**Comment by gaby** [comment]
@judocode  I was having the same issue, after several tries I manage to get it working with the following: 


```
jobs:
  auto-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node-version:
          - 14
          - 16
          - 17
        architecture:
          - x64
    steps:
    - run: git config --global core.autocrlf false  # Mainly for Windows
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        architecture: ${{ matrix.architecture }}

    - name: Get npm cache directory
      id: npm-cache-dir
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    - uses: actions/cache@v3
      id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: npm run install
```

My total build time went from 10min to 3min.
