### ISSUE TITLE
Do not save cache if files are empty

### ISSUE THREAD

**Issue by boardfish** [actions/cache#624]
Even if the target files are not present or empty, a cache key is saved:

```
Post job cleanup.
/usr/bin/tar --posix --use-compress-program zstd -T0 -cf cache.tzst -P -C /home/runner/work/boardfish/project --files-from manifest.txt
Cache Size: ~0 MB (22 B)
Cache saved successfully
Cache saved with key: Linux-project-data-17007abbc08...
```

I'd prefer not to register a key or save a cache in this particular instance.

For now, I'll need to check whether the file exists manually. But I'd rather not have to do that and check against a cache hit instead.

```yml
- name: TEST  | Check crystalball map is available
  id: check_crystalball_map_exists
  uses: andstor/file-existence-action@v1
  with:
    files: "tmp/crystalball_data.yml"
```
