### ISSUE TITLE
Permission denied when caching `macports`

### ISSUE THREAD

**Issue by rami3l** [actions/cache#629]
Installing `macports` is a time-consuming part in my CI, so I guess backing up `/opt/local` will help:

```
- name: Get OS build
  run: |
    sw_vers > macos_build.txt
    cat macos_build.txt
- name: Cache MacPorts
  id: cache-macports
  uses: actions/cache@v2
  with:
    path: /opt/local/
    key: ${{ runner.os }}-macports-${{ hashFiles('macos_build.txt') }}
```

However, since #133 didn't accept using `sudo tar`, I got a long error log all about permissons:

```
Run actions/cache@v2
Received 138412032 of 255723896 (54.1%), 132.0 MBs/sec
Received 255723896 of 255723896 (100.0%), 105.3 MBs/sec
Cache Size: ~244 MB (255723896 B)
/usr/local/bin/gtar --use-compress-program zstd -d -xf /Users/runner/work/_temp/68ab3e83-d089-4f96-b645-0834881ca4e5/cache.tzst -P -C /Users/runner/work/pacaptr/pacaptr --delay-directory-restore
/usr/local/bin/gtar: ../../../../../opt/local: Cannot mkdir: Permission denied
/usr/local/bin/gtar: ../../../../../opt/local: Cannot mkdir: Permission denied
```

Is is possible to introduce some sort of `sudo`, or is there any workaround? Thanks in advance!
