### ISSUE TITLE
Add Example for Yarn v2 Zero-Installs to README

### ISSUE THREAD

**Issue by Kurt-von-Laven** [actions/cache#635]
It would be ideal to add Yarn v2 [Zero-Installs](https://yarnpkg.com/features/zero-installs) to the README beneath [Yarn v2](https://github.com/actions/cache/blob/main/examples.md#node---yarn-2), because the presently recommended approach does not apply when Zero-Installs is used. Yarn allows you to transparently check zipped versions of your dependencies into your repository directly. The `--check-cache` flag to `yarn install` is often omitted for performance reasons (or simply because it is not the default), but is [an important security consideration](https://yarnpkg.com/features/zero-installs#does-it-have-security-implications). Fortunately, the cache action empowers you to cache an empty file signifying that you have checked the cache against the canonical registry, which can dramatically improve job performance. Here is an example of the GitHub Actions steps required in the Zero-Installs case:

```yaml
      - name: Cache the fact that we have checked the yarn cache.
        id: yarn-cache
        uses: actions/cache@v2.1.6
        with:
          path: .cacheChecked
          key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies without refetching on cache hit.
        if: ${{ steps.yarn-cache.outputs.cache-hit == 'true' }}
        run: yarn install --immutable --immutable-cache
      - name: Install dependencies, refetching on cache miss for added security.
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
        run: |
          # See https://yarnpkg.com/features/zero-installs#does-it-have-security-implications
          yarn install --immutable --immutable-cache --check-cache
          touch .cacheChecked
```
