### ISSUE TITLE
Caching data in composite actions

### ISSUE THREAD

**Issue by ruslandulina** [actions/cache#638]
Caching doesn't work in composite actions today. Action composition allows to reduce duplication in workflows and make maintenance easier, however cache action doesn't work in composite actions – cache is always not found.

```
runs:
  using: 'composite'
  steps:
    - name: Restore node_modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ steps.cache-key.outputs.key }}-${{ hashFiles('**/yarn.lock') }}
```

Linux github runners:
**Cache not found for input keys:** yarn-1.22.11-npm-node-v14.17.6-linux-x64-3b1bb16fe4c6727612fe59b0f434064665aefa0f459f4351c238dc733610bf5b

Windows github runners:
**Cache not found for input keys:** yarn-1.22.11-npm-node-v14.17.6-win32-x64-3b1bb16fe4c6727612fe59b0f434064665aefa0f459f4351c238dc733610bf5b

MacOS github runners:
**Cache not found for input keys:** yarn-1.22.11-npm-node-v14.17.6-darwin-x64-3b1bb16fe4c6727612fe59b0f434064665aefa0f459f4351c238dc733610bf5b

**_These steps work correctly outside the composite action (cache is created in post action)_**

Related [issue ](https://github.com/actions/setup-node/issues/329) in setup-node action.

Possible root cause: post action(cache is created there) is not executed if cache action runs in composite action.
Possible solution: https://github.com/actions/cache/issues/587

**Comment by ChristopherHX** [comment]
I don't know why it didn't work for you, but it does for me
> Possible root cause: post action(cache is created there) is not executed if cache action runs in composite action.

It does get called:
https://github.com/ChristopherHX/conditional/runs/3655221467?check_suite_focus=true#step:5:7
Then in another job which depends on the previous one I call the same action and it restored the cache

https://github.com/ChristopherHX/conditional/runs/3655225157?check_suite_focus=true#step:5:3

My composite test action I used is here https://github.com/ChristopherHX/conditional/blob/main/.github/tests/test1/action.yml

.github/tests/test1/action.yml
```yaml
inputs:
  sampleInput:
    description: sampleInput
    default: Test value
  nodever:
    description: sampleInput
    default: '16'
runs:
  using: composite
  steps:
  - uses: actions/cache@v2
    id: cacheaction
    with:
      key: mycache-${{github.run_id}}
      path: |
        ~/cache
  - uses: ChristopherHX/conditional@b4a9649204f81002ec9a4ef7d4bf7d6b2ab7fa55
    with:
      if: ${{steps.cacheaction.outputs.cache-hit != 'true'}}
      step: |
        uses: actions/setup-node@v2
        with:
          node-version: ${{inputs.nodever}}
  - uses: ChristopherHX/conditional@b4a9649204f81002ec9a4ef7d4bf7d6b2ab7fa55
    with:
      if: ${{steps.cacheaction.outputs.cache-hit != 'true'}}
      step: |
        run: |
          mkdir -p ~/cache
          echo '${{inputs.sampleInput}}' > ~/cache/tmp.txt
        shell: bash
  - run: |
      cat ~/cache/tmp.txt
    shell: bash
```

I used the run_id in the cache key to avoid a cache hit on the first call in my test workflow.
However I didn't use hashfiles or tried to restore the cache in the same job as storing it.

Call it in two depending jobs in a workflow and you see cache is working.

**Comment by michaelfoidl** [comment]
I have exactly the same problem. The first job logs the following in the post-build action:
```Post job cleanup.
Post job cleanup.
Post job cleanup.
Post job cleanup.
/usr/bin/tar --posix --use-compress-program zstd -T0 -cf cache.tzst -P -C /home/runner/work/spritify/spritify --files-from manifest.txt
Cache Size: ~3 MB (2648796 B)
Cache saved successfully
Cache saved with key: spritify-common-build-e1011132409c42ceab59eb2eb5358c694c44cbb6
Post job cleanup.
Post job cleanup.
```
However, in a dependent job, restoring the cache fails:
```with:
    path: .
    key: spritify-common-build-e1011132409c42ceab59eb2eb5358c694c44cbb6
  env:
    dotnet-version: 5.0.x
    node-version: 14.17.x
Cache not found for input keys: spritify-common-build-e1011132409c42ceab59eb2eb5358c694c44cbb6
```

Both jobs use composite actions that build my project. Can I provide any further information to help solving this issue?

My current workaround is to use artifacts instead of caches, however, this increases the runtime significantly and I would love to get rid of them.

**Comment by michaelfoidl** [comment]
I've finally found out why it didn't work for me: The cache action expects the path that was used for saving the cache and the path used for restoring the cache to be equal. In my case, saving and restoring happens in two different actions, therefore the confusion.
You can also see this behavior in a sample project I've created: https://github.com/michaelfoidl/github-caching-tests/actions

Maybe this should be somehow emphasized in the docs?

**Comment by piurafunk** [comment]
This should for sure be documented (or fixed, if undesired behavior).

I discovered https://github.com/actions/cache/issues/735 first, and put my findings there. Basically, the path must match exactly, and I was using `${{ github.workspace }}/prod.tar.gz` for the path. This is different between GH hosted and the self-hosted it was running on. That influences whether the cache can be found or not.

https://github.com/autowarefoundation/autoware-github-actions/issues/47 also seems to have the same problem, they fixed it in https://github.com/autowarefoundation/autoware-github-actions/pull/48 by making the cache paths match exactly.

**Comment by BaseInfinity** [comment]
@piurafunk just ran into this myself, I made a feature request:
https://github.com/actions/cache/issues/815

**Comment by antdking** [comment]
I think there's a second issue here, in that Github Actions isn't passing Step Outputs into the string formatter for the post-step.

[Example](https://github.com/datapane/datapane/runs/7434551949?check_suite_focus=true):

<details>
<summary>Restore-cache</summary>

```
##[debug]Evaluating: format('cache-poetry-cache-v1-{0}-{1}-{2}', runner.os, steps.preinstall.outputs.python-version, inputs.poetry-version)
##[debug]Evaluating format:
##[debug]..Evaluating String:
##[debug]..=> 'cache-poetry-cache-v1-{0}-{1}-{2}'
##[debug]..Evaluating Index:
##[debug]....Evaluating runner:
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'os'
##[debug]..=> 'Linux'
##[debug]..Evaluating Index:
##[debug]....Evaluating Index:
##[debug]......Evaluating Index:
##[debug]........Evaluating steps:
##[debug]........=> Object
##[debug]........Evaluating String:
##[debug]........=> 'preinstall'
##[debug]......=> Object
##[debug]......Evaluating String:
##[debug]......=> 'outputs'
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'python-version'
##[debug]..=> '50858736'
##[debug]..Evaluating Index:
##[debug]....Evaluating inputs:
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'poetry-version'
##[debug]..=> '1.1.14'
##[debug]=> 'cache-poetry-cache-v1-Linux-50858736-1.1.14'
##[debug]Result: 'cache-poetry-cache-v1-Linux-50858736-1.1.14'
```

</details>

<details>
<summary>Save-cache</summary>

```
##[debug]Evaluating: format('cache-poetry-cache-v1-{0}-{1}-{2}', runner.os, steps.preinstall.outputs.python-version, inputs.poetry-version)
##[debug]Evaluating format:
##[debug]..Evaluating String:
##[debug]..=> 'cache-poetry-cache-v1-{0}-{1}-{2}'
##[debug]..Evaluating Index:
##[debug]....Evaluating runner:
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'os'
##[debug]..=> 'Linux'
##[debug]..Evaluating Index:
##[debug]....Evaluating Index:
##[debug]......Evaluating Index:
##[debug]........Evaluating steps:
##[debug]........=> Object
##[debug]........Evaluating String:
##[debug]........=> 'preinstall'
##[debug]......=> null
##[debug]....=> null
##[debug]..=> null
##[debug]..Evaluating Index:
##[debug]....Evaluating inputs:
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'poetry-version'
##[debug]..=> '1.1.14'
##[debug]=> 'cache-poetry-cache-v1-Linux--1.1.14'
##[debug]Result: 'cache-poetry-cache-v1-Linux--1.1.14'
```

</details>

We also use step outputs in the `path` section.
Is this a case of using `set-state` for all inputs going forward, given the Composite limitation?

**Comment by Sytten** [comment]
To further comment on this, actually no inputs are correctly passed to nested composite action post hooks.
I believe the parent context is used so if the name are the same it will work.

**Comment by bishal-pdMSFT** [comment]
Since this issue is not specific to cache action and is being tracked in https://github.com/actions/runner/issues/2009, I will go ahead and close it.

**Comment by keradus** [comment]
For those who stumbled on using `inputs` or `outputs` for composite GitHub Actions, I found using `$GITHUB_ENV` to be a viable workaround.

You may find a working example in https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7415 .
(And also a lot of debugging in https://github.com/keradus/PHP-CS-Fixer/pull/36 .)

```yml
name: "Install composer deps"

inputs:
  flags:
    description: 'Composer flags'
    required: false

runs:
  using: "composite"
  steps:
    # Warning!
    # Use $GITUB_ENV instead of $GITHUB_OUTPUT.
    #
    # The actions/cache is, on calling it in this composite action, reading the cache,
    # and then also registering a shutdown function for whole workflow, to write the cache afterwards.
    #
    # That registered shutdown function is _NOT_ having access to inputs.* nor steps.*.outputs for
    # `path` parameter, which is evaluated on both stages (read and write), yet `key` parameters
    # are evaluated on start only and are not affected by this issue.
    #
    # Unfortunately, when the issue is faced, it does not break the build, simply raising a warning
    # and completing the build successuflly, yet without storing the cache:
    # > Warning: Input required and not supplied: path

    - name: Get Composer cache params
      shell: bash
      run: |
        echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV
        echo "COMPOSER_CACHE_PHP=$(php -r 'echo PHP_VERSION;')" >> $GITHUB_ENV

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: ${{ env.COMPOSER_CACHE_DIR }}
        key: Composer-${{ runner.os }}-${{ env.COMPOSER_CACHE_PHP }}-${{ hashFiles('**/composer.json') }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          Composer-${{ runner.os }}-${{ env.COMPOSER_CACHE_PHP }}-${{ hashFiles('**/composer.json') }}-
          Composer-${{ runner.os }}-${{ env.COMPOSER_CACHE_PHP }}-
          Composer-${{ runner.os }}-

    - name: Install dependencies
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 5
        max_attempts: 5
        retry_wait_seconds: 30
        # `--no-scripts` to avoid side-effects (e.g. installing dev-tools for all jobs on CI level),
        # all executed scripts should be explicit and run only when needed.
        command: composer update --optimize-autoloader --no-interaction --no-progress --no-scripts ${{ inputs.flags }}

    - name: Show versions of packages
      shell: bash
      run: composer info -D

```
