### ISSUE TITLE
/bin/tar: unrecognized option: posix

### ISSUE THREAD

**Issue by williamdes** [actions/cache#640]
Using `alpine` 

workflow:
```yaml
    deploy-staging:
        if: startsWith(github.ref, 'refs/tags/staging/')
        name: Deploy to staging
        container:
            image: alpine
```

```
Post job cleanup.
/usr/bin/docker exec  dcb7efcd78f1493a0f203170c30683f32416b29cf23efa36edc84c025749696f sh -c "cat /etc/*release | grep ^ID"
/bin/tar --posix -z -cf cache.tgz -P -C /__w/xxxxxxxx/xxxxxxxx --files-from manifest.txt
/bin/tar: unrecognized option: posix
BusyBox v1.33.1 () multi-call binary.

Usage: tar c|x|t [-ZzJjahmvokO] [-f TARFILE] [-C DIR] [-T FILE] [-X FILE] [OPTION]... [FILE]...

Create, extract, or list files from a tar file

	c	Create
	x	Extract
	t	List
	-f FILE	Name of TARFILE ('-' for stdin/out)
	-C DIR	Change to DIR before operation
	-v	Verbose
	-O	Extract to stdout
	-m	Don't restore mtime
	-o	Don't restore user:group
	-k	Don't replace existing files
	-Z	(De)compress using compress
	-z	(De)compress using gzip
	-J	(De)compress using xz
	-j	(De)compress using bzip2
	--lzma	(De)compress using lzma
	-a	(De)compress based on extension
	-h	Follow symlinks
	-T FILE	File with names to include
	-X FILE	File with glob patterns to exclude
	--exclude PATTERN	Glob pattern to exclude
	--overwrite		Replace existing files
	--strip-components NUM	NUM of leading components to strip
	--no-recursion		Don't descend in directories
	--numeric-owner		Use numeric user:group
	--no-same-permissions	Don't restore access permissions
Warning: Tar failed with error: The process '/bin/tar' failed with exit code 1

```

**Comment by williamdes** [comment]
Fix: `apk --no-cache add tar`

But maybe the code could handle busybox tar

**Comment by williamdes** [comment]
Basic example

```yml
name: Build and lint

on: [push, pull_request]

jobs:
    build-and-lint:
        name: Build and lint
        container:
            image: node:14-alpine
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"
            - name: Cache node modules
              uses: actions/cache@v2
              id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
              with:
                path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                restore-keys: ${{ runner.os }}-yarn-
            - name: Install node modules
              run: yarn install
            - name: Lint files
              run: yarn lint
            - name: Build package
              run: yarn build
```
