### ISSUE TITLE
Warning when cache item exists for cache key

### ISSUE THREAD

**Issue by localheinz** [actions/cache#65]
When assembling cache keys that have been used before, a warning is issued:

![Screen Shot 2019-11-07 at 08 13 44](https://user-images.githubusercontent.com/605483/68367772-b97c1500-0136-11ea-8a82-f6bc46e1a95b.png)

The question is: why?

The point of a cache item is to be reusable, so when we use the same cache key/item multiple times, why would that be worth a warning?

In this particular case, the cache key is assembled like this:

```yml
- name: "Cache dependencies installed with composer"
  uses: actions/cache@v1.0.0
  with:
    path: ~/.composer/cache
    key: php7.2-composer-locked-${{ hashFiles('**/composer.lock') }}
    restore-keys: |
      php7.2-composer-locked-
```

However, when the content of `composer.lock` has not changed, the same cache key will be generated, and apparently the action then issues a warning as a cache item with a corresponding cache key already exists. 

Issuing a warning probably makes sense when someone uses a cache key that will always be the same (something that does not use expressions), but here it is intended.

I have fallen back to using the `github.sha` now, but I'm not sure whether this is the best approach. This will create a lot more cache items.

What do you think?

```diff
 - name: "Cache dependencies installed with composer"
   uses: actions/cache@v1.0.0
   with:
     path: ~/.composer/cache
-    key: php7.2-composer-locked-${{ hashFiles('**/composer.lock') }}
+    key: php7.2-composer-locked-${{ github.sha }}
     restore-keys: |
       php7.2-composer-locked-
```

For reference, see [`.github/workflows/continuous-integration.yml`](https://github.com/localheinz/php-library-template/blob/33613b50b8b97c2c21d3db78eef60736f33b1bdd/.github/workflows/continuous-integration.yml#L25-L31).
