### ISSUE TITLE
Cocoapods cache not found on successive runs

### ISSUE THREAD

**Issue by casconed** [actions/cache#659]
Getting the following error: 
` Cache not found for input keys: macOS-pods-1e06307a62c2ab8a82233beddae44a88f1a593085e7fc368520a54a3d0cd7bf9, macOS-pods-`

However on a run immediately previous to this one I get:

`Cache saved with key: macOS-pods-1e06307a62c2ab8a82233beddae44a88f1a593085e7fc368520a54a3d0cd7bf9`

Caching is working in a different step, on a different directory 

Full output from the restore step:

```
Run actions/cache@v2
  with:
    path: ios/Pods
    key: macOS-pods-1e06307a62c2ab8a82233beddae44a88f1a593085e7fc368520a54a3d0cd7bf9
    restore-keys: macOS-pods-
  env:
    CI: true
    BUILDCACHE_DEBUG: 1
    BUILDCACHE_MAX_CACHE_SIZE: 2000000000
    BUILDCACHE_MAX_LOCAL_ENTRY_SIZE: 402653184
    PATH: /usr/local/opt/pipx_bin:/Users/runner/.cargo/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Users/runner/Library/Android/sdk/ndk-bundle:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.dotnet/tools:/Users/runner/.ghcup/bin:/Users/runner/hostedtoolcache/stack/2.7.3/x64
Cache not found for input keys: macOS-pods-1e06307a62c2ab8a82233beddae44a88f1a593085e7fc368520a54a3d0cd7bf9, macOS-pods-
```
