### ISSUE TITLE
doesn't cache anything...

### ISSUE THREAD

**Issue by Raffaello** [actions/cache#664]
I have set up  a cache for sonarcloud like this:
```yaml
 - uses: actions/cache@v2
        id: sonar-cache
        with:
            path: |
              $HOME\.sonar\/sonar-scanner-${{ env.SONAR_SCANNER_VERSION }}-windows
              $HOME\.sonar\/build-wrapper-win-x86
            key: ${{ runner.os }}-sonar-cache-${{ hashFiles('**/*') }}
            restore-keys: ${{ runner.os }}-sonar-cache
            
- name: Download and set up sonar-scanner
        #if: steps.sonar-cache.outputs.cache-hit != 'true'
        env:
          SONAR_SCANNER_DOWNLOAD_URL: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${{ env.SONAR_SCANNER_VERSION }}-windows.zip
        run: |
          New-Item -Force -ItemType directory -Path $HOME\.sonar
          curl -sSLo $HOME\.sonar\sonar-scanner.zip ${{ env.SONAR_SCANNER_DOWNLOAD_URL }}
          unzip -o $HOME\.sonar\sonar-scanner.zip -d $HOME\.sonar\
          rm $HOME\.sonar\sonar-scanner.zip
      - name: Download and set up build-wrapper
        #if: steps.sonar-cache.outputs.cache-hit != 'true'
        env:
          BUILD_WRAPPER_DOWNLOAD_URL: ${{ env.SONAR_SERVER_URL }}/static/cpp/build-wrapper-win-x86.zip
        run: |
          curl -sSLo $HOME\.sonar\build-wrapper.zip ${{ env.BUILD_WRAPPER_DOWNLOAD_URL }}
          unzip -o $HOME\.sonar\build-wrapper.zip -d $HOME\.sonar\
          rm $HOME\.sonar\build-wrapper.zip
      - name: set up PATH
        run: |
          echo "$HOME\.sonar\sonar-scanner-${{ env.SONAR_SCANNER_VERSION }}-windows\bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
          echo "$HOME\.sonar\build-wrapper-win-x86" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
          
## ....
```

i am expecting that the content of those folders, that are later on deflated from a downloaded zip should be stored.

i have tried as well to use the parent folder in the path, but nothing changes. what is processed is:

```
Run actions/cache@v2
  with:
    path: $HOME\.sonar\/sonar-scanner-4.4.0.2170-windows
  $HOME\.sonar\/build-wrapper-win-x86
  
    key: Windows-sonar-cache-
    restore-keys: Windows-sonar-cache
  env:
    SONAR_SCANNER_VERSION: 4.4.0.2170
    SONAR_SERVER_URL: https://sonarcloud.io
    BUILD_WRAPPER_OUT_DIR: build
    JAVA_HOME_11.0.13_x64: C:\hostedtoolcache\windows\jdk\11.0.13\x64
    JAVA_HOME: C:\hostedtoolcache\windows\jdk\11.0.13\x64
    JAVA_HOME_11_0_13_X64: C:\hostedtoolcache\windows\jdk\11.0.13\x64
Cache not found for input keys: Windows-sonar-cache-, Windows-sonar-cache
```

and then:

```
Post job cleanup.
C:\Windows\System32\tar.exe --posix -z -cf cache.tgz -P -C D:/a/sdl2-sonic-drivers/sdl2-sonic-drivers --files-from manifest.txt
Cache Size: ~0 MB (30 B)
Cache saved successfully
Cache saved with key: Windows-sonar-cache-
```

wondering if that parameter `--files-from manifest.txt` is messing around and honestly not clear neither why is there..

I think this is a bug on the cache actions or either is not well documented.

Unless the `$HOME` variable changes in the cache actions 

it can be seen here for further details: https://github.com/Raffaello/sdl2-sonic-drivers/runs/3983682672?check_suite_focus=true
