### ISSUE TITLE
Cache size always 0MB (caching pip)

### ISSUE THREAD

**Issue by rbhalla** [actions/cache#665]
```
jobs:
  e2e-job:
    runs-on: ubuntu-latest
    container: python:3.9
    services:
      elasticsearch:
        image: elasticsearch:7.14.1
        env:
          'discovery.type': single-node
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Cache pip dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-pip-dependencies
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ env.cache-name }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Run tests
        env:
          ELASTICSEARCH_HOST: elasticsearch
        run: make dev-test
 ```

I've tried a few variations of this but I don't think I fundamentally understand how things work, so apologies if this is obvious.

This is the type of logs I see in the post cache step:

```
Post job cleanup.
/usr/bin/docker exec  eac2516d441d567f76438f7860e3596fc47664738d835124085fb1566a3bf375 sh -c "cat /etc/*release | grep ^ID"
/bin/tar --posix -z -cf cache.tgz -P -C /__w/second/second --files-from manifest.txt
Cache Size: ~0 MB (45 B)
Cache saved successfully
Cache saved with key: Linux-pip-cache-pip-dependencies-787fe77abdcacba9f6abe78e00209fe63740ffd3b12252ab9ce569e07a7cfcb0
```

I've tried running it on other containers too but I get similar results. I have run into oddities like with the container `ubuntu:16.04` where pip wasn't found. I'm not entirely sure what may be causing that but I've run out of variations to try.

**Comment by ivankprod** [comment]
Try this:

```
jobs:
  e2e-job:
    runs-on: ubuntu-latest
    container: python:3.9
    services:
      elasticsearch:
        image: elasticsearch:7.14.1
        env:
          'discovery.type': single-node
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Cache pip dependencies
        uses: actions/cache@v2
         id: cache
        env:
          cache-name: cache-pip-dependencies
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ env.cache-name }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: python -m pip install -r requirements.txt
      - name: Run tests
        env:
          ELASTICSEARCH_HOST: elasticsearch
        run: make dev-test

```
