### ISSUE TITLE
Action does not use the latest cache artifact

### ISSUE THREAD

**Issue by sidey79** [actions/cache#674]
I have trouble, that the action does not use the latest cache. Instead it uses an older cache.
May i have misundersood how the cache entry is elected.

### Run which save a cache artifact

This is the step where i generate a timestamp which i use to specify my cache key:
( I do not want to have more than one cache entry per hour)

```
      - name: Get current date 
        id: get-date
        run: |
          echo "::set-output name=timestamp::$(/bin/date -u "+%Y%m%d%H" )"
        shell: bash
```

This is the cache step, where i use the timestamp above:

```
      - name: Cache .git directory
        # Some room for improvement because we create a new cache on every run where a new ref is fetched, this isn't very nice, normaly weneed only the last one and it takes 7 days until they are deleted
        id: cache-fhem
        uses: actions/cache@v2.1.6
        with:
          path: ./src/fhem-mirror/.git
          key: ${{ runner.os }}-fhemsvndir-${{ steps.get-date.outputs.timestamp }}
          restore-keys: |
            ${{ runner.os }}-fhemsvndir-
```

This is evalulated to somethink like this, which looks good:

```
##[debug]=> 'Linux-fhemsvndir-2021111021'
##[debug]Result: 'Linux-fhemsvndir-2021111021'
``` 

Within this run the post part of the action tells me, that this cache entry is saved
```
Cache saved successfully
Cache saved with key: Linux-fhemsvndir-2021111021
##[debug]Node Action run completed with exit code 0
##[debug]Finishing: Post Cache .git directory
```

The full run can be seen [here](https://github.com/sidey79/fhem-mirror/runs/4170901483?check_suite_focus=true)

### Following run which elects an older cache entry

I would except, that the next run in the workflow will elect the cache entry with my timestamp `2021111021`.

So the next run, evaluates like this, which first looks fine:

```
##[debug]["Linux-fhemsvndir-2021111105","Linux-fhemsvndir-"]
```

But then it does elect a much older cache artifact from 2021-11-09 and not from 2021-11-10

```
##[debug]Cache Result:
##[debug]{"scope":"refs/heads/main","cacheKey":"Linux-fhemsvndir-","cacheVersion":"173c5fe307d6306075fe742daa53fa07c126d69a10a69d9478912efb038c3559","creationTime":"2021-11-09T21:08:09.02Z","archiveLocation":"***"}
```

The run can be seen [here](https://github.com/sidey79/fhem-mirror/runs/4174314031?check_suite_focus=true), but i aborted it.

I tried it multiple times, and always the cache entry from 2021-11-09 is used.
