### ISSUE TITLE
actions/cache is not working as expected in 32-bit linux containers

### ISSUE THREAD

**Issue by flavorjones** [actions/cache#675]
See a similar issue for actions/checkout at https://github.com/actions/checkout/issues/334

When running the `actions/cache` action in a 32-bit linux container, I see the following error message:

```
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: no such file or directory: unknown
```

The complete output from the action is:

```
Run actions/cache@v1
  with:
    path: ports/archives
    key: tarballs-ubuntu-4d009fdcf7f076f84ea105c65a33a1459e9643b3c9b7327f7bbc2f3aad9600aa
/usr/bin/docker exec  eba8798f1fb0a828fa7e051847f1ef32b8f84072933a54084fe2f1b53e49f3c1 sh -c "cat /etc/*release | grep ^ID"
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: no such file or directory: unknown
```

An example job config that should reproduce the issue:

```yaml
jobs:
  myjob:
    runs-on: ubuntu-latest
    container:
      image: "larskanis/rake-compiler-dock-mri-x86-linux:1.1.0"
    steps:
      - uses: actions/checkout@v1 # v1 because of https://github.com/actions/checkout/issues/334
      - uses: actions/cache@v2
        with:
          path: ports/archives
          key: tarballs-ubuntu
```
