### ISSUE TITLE
Relative paths? - Or some root path that's not in my GITHUB_WORKSPACE?

### ISSUE THREAD

**Issue by SamuelMarks** [actions/cache#684]
This didn't work:

```yml
      - name: Cache vcpkg
        uses: actions/cache@v2
        env:
          cache-name: cache-vcpkg
        with:
          path: ${{ github.workspace }}/../vcpkg
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
```

Which gave:

> Warning: Invalid pattern 'D:\a\libacquire\libacquire/../vcpkg'. Relative pathing '.' and '..' is not allowed.

Happy to put my `vcpkg` directory somewhere else, just not sure where a good place is.

Suggestions on handling relative paths or a better directory than I've chosen are appreciated.
