### ISSUE TITLE
Permission issues on Windows restoring boost from cache

### ISSUE THREAD

**Issue by michaeltryby** [actions/cache#693]
I developed the following Actions steps to install/cache/restore Boost on Windows. Installs and caches great!

```
    - name: Cache boost
      id: cache-boost
      uses: actions/cache@v2
      env:
        cache_paths: |
            C:/ProgramData/chocolatey/lib/boost-*
            C:/local/boost_*
        pkg_file_hash: ${{ hashFiles('**/windows/packages.config') }}
      with:
        path: ${{ env.cache_paths }}
        key: ${{ runner.os }}-cache-boost-${{ env.pkg_file_hash }}
        restore-keys: |
          ${{ runner.os }}-cache-boost-
          ${{ runner.os }}-cache-
          ${{ runner.os }}-

    - name: Install boost
      if: steps.cache-boost.outputs.cache-hit != 'true'
      env:
        pkg_cmnd: choco install -y packages.config
      run: ${{ env.pkg_cmnd }}
```

When I try to restore, however, I get the following

```
Run actions/cache@v2
  with:
    path: C:/ProgramData/chocolatey/lib/boost-*
  C:/local/boost_*
  
    key: Windows-cache-boost-28766d589de4d912981b644c23313c24f5a3eff52d0507cedb225f86af2d46cc
    restore-keys: Windows-cache-boost-
  Windows-cache-
  Windows-

  env:
    OMP_NUM_THREADS: 1
    BUILD_HOME: build
    TEST_HOME: nrtests
    cache_paths: C:/ProgramData/chocolatey/lib/boost-*
  C:/local/boost_*
    pkg_file_hash: 28766d589de4d912981b644c23313c24f5a3eff52d0507cedb225f86af2d46cc

Received 134217728 of 615036702 (21.8%), 127.2 MBs/sec
Received 306184192 of 615036702 (49.8%), 145.4 MBs/sec
Received 486539264 of 615036702 (79.1%), 154.2 MBs/sec
Received 615036702 of 615036702 (100.0%), 87.1 MBs/sec
Cache Size: ~587 MB (615036702 B)

C:\Windows\System32\tar.exe -z -xf D:/a/_temp/b1603dff-bd46-4c02-b156-1eae6a2b580e/cache.tgz -P -C D:/a/Stormwater-Management-Model/Stormwater-Management-Model
C:/local/boost_1_74_0/: Can't create '\\\\?\\C:\\local\\boost_1_74_0'
C:/local/boost_1_74_0/boost/: Can't create '\\\\?\\C:\\local\\boost_1_74_0\\boost'
C:/local/boost_1_74_0/boost-build.jam: Can't create '\\\\?\\C:\\local\\boost_1_74_0\\boost-build.jam'
C:/local/boost_1_74_0/boost.css: Can't create '\\\\?\\C:\\local\\boost_1_74_0\\boost.css'
C:/local/boost_1_74_0/boost.png: Can't create '\\\\?\\C:\\local\\boost_1_74_0\\boost.png'
C:/local/boost_1_74_0/boostcpp.jam: Can't create '\\\\?\\C:\\local\\boost_1_74_0\\boostcpp.jam'
C:/local/boost_1_74_0/bootstrap.bat: Can't create '\\\\?\\C:\\local\\boost_1_74_0\\bootstrap.bat'
C:/local/boost_1_74_0/bootstrap.sh: Can't create '\\\\?\\C:\\local\\boost_1_74_0\\bootstrap.sh'
C:/local/boost_1_74_0/doc/: Can't create '\\\\?\\C:\\local\\boost_1_74_0\\doc'
C:/local/boost_1_74_0/index.htm: Can't create '\\\\?\\C:\\local\\boost_1_74_0\\index.htm'
...
```
Seems choco had permission to install to C:/local but cache doesn't have permission to restore there. How can this be fixed?
