### ISSUE TITLE
BUG: dumb check makes cache fail

### ISSUE THREAD

**Issue by jelmd** [actions/cache#695]
```
...
      - name: Fetch stack cache
        id: stack_cache
        uses: actions/cache@v2
        with:
          path: /var/tmp/stack
          key: stack-${{ runner.os }}
...
```
fails with `Preventing creation of stack root '/tmp/stack/'. Parent directory '/tmp/' is owned by someone else.` This is absolutely non-sense because such directories (`/tmp`, `/var/tmp`, `/dev/shm` and possibly others) are especially made writeable by anybody - have mode `01777`. So please skip such bogus checks and just try-and-error to get a robust implementation (or is handling ACLs on the todo list as well?).
