### ISSUE TITLE
/usr/bin/tar: ../../../../../usr/lib/libta_lib.a: Cannot open: Permission denied

### ISSUE THREAD

**Issue by cryptocoinserver** [actions/cache#703]
```
- name: Cache talib
        if: ${{ runner.os == 'Linux' }}
        uses: actions/cache@v2
        id: talib-cache
        with:
          path: |
           /usr/lib/libta_lib.a
           /usr/lib/libta_lib.la
           /usr/lib/libta_lib.so
           /usr/lib/libta_lib.so.0
           /usr/lib/libta_lib.so.0.0.0
          key: ta-lib-cache-0.4.0
```

```
Run actions/cache@v2
  with:
    path: /usr/lib/libta_lib.a
  /usr/lib/libta_lib.la
  /usr/lib/libta_lib.so
  /usr/lib/libta_lib.so.0
  /usr/lib/libta_lib.so.0.0.0
  
    key: ta-lib-cache-0.4.0
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.12/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.12/x64/lib
Received 1546909 of 1546909 (100.0%), 2.2 MBs/sec
Cache Size: ~1 MB (1546909 B)
/usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/0e0d233c-3081-4372-bc31-d684ff62f46a/cache.tzst -P -C /home/runner/work/jesse/jesse
/usr/bin/tar: ../../../../../usr/lib/libta_lib.a: Cannot open: Permission denied
/usr/bin/tar: ../../../../../usr/lib/libta_lib.la: Cannot open: Permission denied
/usr/bin/tar: ../../../../../usr/lib/libta_lib.so: Cannot create symlink to ‘libta_lib.so.0.0.0’: Permission denied
/usr/bin/tar: ../../../../../usr/lib/libta_lib.so.0: Cannot create symlink to ‘libta_lib.so.0.0.0’: Permission denied
/usr/bin/tar: ../../../../../usr/lib/libta_lib.so.0.0.0: Cannot open: Permission denied
/usr/bin/tar: Exiting with failure status due to previous errors
Warning: Tar failed with error: The process '/usr/bin/tar' failed with exit code 2
```

Any ideas why this happens. Seems we can't cache /usr/lib files?
Thank you.

**Comment by hori-ryota** [comment]
It's not the answer to your question, if you can tolerate expanding to another directory use followings.

```yaml
- name: Set up ta-lib dir
  run: |
    mkdir -p $HOME/.local/ta-lib
    echo "LD_LIBRARY_PATH=$HOME/.local/ta-lib/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
    echo "TA_INCLUDE_PATH=$HOME/.local/ta-lib/include" >> $GITHUB_ENV
    echo "TA_LIBRARY_PATH=$HOME/.local/ta-lib/lib" >> $GITHUB_ENV
- name: Set up ta-lib cache
  uses: actions/cache@v2
  id: ta-lib-cache
  with:
    path: |
      ~/.local/ta-lib/lib
      ~/.local/ta-lib/include

```

and install ta-lib to `~/.local/ta-lib` like followings.

```sh
        ./configure --prefix=$HOME/.local/ta-lib
        make
        sudo make install
```
