### ISSUE TITLE
Do `restore-keys` even work?

### ISSUE THREAD

**Issue by Jason3S** [actions/cache#716]
Based upon the code, `restore-keys` are never written.

https://github.com/actions/cache/blob/2ebdcff279bac9704c2b319b25ac54b63d6800c2/src/save.ts#L51

I was looking through the examples and two things struck me:

1. Caches are never updated.
2. Restore Keys are never written.

Given those two things, most of the example seem a bit useless.

```yaml
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
```

<details>
  <summary>Full Example</summary>

From: [example-using-the-cache-action](https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows#example-using-the-cache-action)

```yaml
name: Caching with npm

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm build

      - name: Test
        run: npm test
```

</details>

Please note, I'm not questioning if the restore process works. I am guessing it does. 

The issue is:
1. The caches associated with the restore keys are never getting populated. 
2. Even if they did, they become stale very fast and do not get updated.
    - Imagine the restore key of `${{ runner.os }}` which becomes something like `linux` might still be holding some very old `node_module` from Node 10. How would these get updated?
    - What happens when the same restore key is generated by different workflows? They are likely to be caching different files.
