### ISSUE TITLE
caching a folder on ubuntu and restore it on macos doesn't work

### ISSUE THREAD

**Issue by megetron** [actions/cache#719]
when you try to cache a folder between two different jobs which are on a different operating system runner, it seems like the caching mechanism doesn't work.

i am using this pipeline to reproduce the issue:
```
name: Build Unity TestProject
on: [pull_request]

jobs:
  buildAndTestForSomePlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2020.3.25f1
        targetPlatform:
          - Android
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - run: mkdir build && mkdir build/Android && touch build/Android/Android.apk
      
      - name: cache build folder
        uses: actions/cache@v2
        with:
          path: build/${{ matrix.targetPlatform }}
          key: build-${{ matrix.targetPlatform }}-${{ github.run_id }}
      - run: ls build
  testOnAndroidEmulator:
    name: execute tests
    needs: buildAndTestForSomePlatforms
    runs-on: macos-latest
    steps:
      - name: restore 'Android' build folder
        uses: actions/cache@v2
        with:
          path: build/Android
          key: build-Android-${{ github.run_id }}
      - run: ls 

```
