### ISSUE TITLE
Allow caching by github.ref AND github.sha

### ISSUE THREAD

**Issue by Mahoney** [actions/cache#740]
I would like to use the cache action in two currently incompatible ways:

1. Cache by branch name:
```yaml
      - uses: actions/cache@v2
        with:
          path: cached.txt
          key: mycache-${{ github.ref }}-${{ github.run_number }}
          restore-keys: |
            mycache-${{ github.ref }}-
            mycache-
```
Here a subsequent push to a branch benefits from the cache generated by the previous push to that branch.

2. Cache by commit hash:
```yaml
      - uses: actions/cache@v2
        with:
          path: cached.txt
          key: mycache-${{ github.sha }}
```

Here tagging a previously built commit gets _exactly_ the cache generated by the build of that _specific commit_ on any branch.

I can think of two ways this could be implemented:
1. Allow a cache to be stored under multiple keys:
```yaml
      - uses: actions/cache@v2
        with:
          path: cached.txt
          keys: |
            mycache-${{ github.ref }}-${{ github.run_number }}
            mycache-${{ github.sha }}
          restore-keys: |
            mycache-${{ github.ref }}-
            mycache-
```
this wouldn't require storing the actual blob multiple times of course, it would just be two pointers to the same blob.

2. Allow glob expressions in restore-keys:
```yaml
      - uses: actions/cache@v2
        with:
          path: cached.txt
          key: mycache-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            **-${{ github.sha }}
            mycache-${{ github.ref }}-
            mycache-
```
This would keep the single key behaviour, but would allow a cache with primary key `mycache-refs/heads/somebranch-2be41deebcd2d46926eff0989c6992229aa6d6d3` to be matched first by `mycache-refs/tags/0.1.0-2be41deebcd2d46926eff0989c6992229aa6d6d3` rather than falling back on whatever was last cached under `mycache-`.
