### ISSUE TITLE
Step should not succeed when tar fails with error

### ISSUE THREAD

**Issue by macropin** [actions/cache#757]
Using a simple step to restore the build x cache we encountered an error (below). I believe the issue is that the GitHub cache became corrupt. However actions/cache did not catch the error.

```
      - name: Cache layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
```

So only a warning was printed instead of failing the step:

```
....
/*stdin*\ : Decoding error (36) : Restored data doesn't match checksum 
/usr/bin/tar: Child returned status 1
/usr/bin/tar: Error is not recoverable: exiting now
Warning: Tar failed with error: The process '/usr/bin/tar' failed with exit code 2
````
