### ISSUE TITLE
Save cache but not use it

### ISSUE THREAD

**Issue by leighmcculloch** [actions/cache#761]
It would be helpful if there was a way to specify that a job should generated save to the cache, but not load the cache. The use case I have is we want our default branch to run without cache, but we want it to write to the cache so that all PRs use the cache.

The work around at the moment is that we can remove all the cached directories after they are loaded, but this means that the job is spending time downloading the cache unnecessarily.

**Comment by Makaiza** [comment]
Yes

**Comment by vsvipul** [comment]
@leighmcculloch  Can you give more context on what workflow and key are you using ?

**Comment by headsvk** [comment]
@vsvipul  my use case is creating Android emulator on `main` branch and then using it on PR branches. The cache should be write-only on `main` since there's no need to download it and restore it, it won't be used. And it should be read-only on any other branch. Cache key is static, for example `android-emulator`.

**Comment by leighmcculloch** [comment]
> @leighmcculloch Can you give more context on what workflow and key are you using ?

@vsvipul Yes of course! The use case is the https://github.com/stellar/go repo.

We cache Go build and test artifacts so that builds in PRs only actually spend time on tests that have changed, including integration tests. But we want all tests to run on the default branch as a safety net, and so, we don't actually want the default branch to load the cache because we don't need it. Right now we achieve this by deleting the cache after it is loaded, so the loading of the cache is a bit wasteful.

The reason we still use the cache action on the default branch is to make sure there is a cache for new branches to load cache from on their first run. According to the readme cache entries that are stored from the default branch are the only cache entries available to a new branch the first time the branch's workflows run:
https://github.com/actions/cache/blob/136d96b4aee02b1f0de3ba493b1d47135042d9c0/README.md#L57-L58

Deleting the cache after it is loaded on the default branch isn't such a bad work-around really, as it is only one extra step in the workflows. You can see it here:

https://github.com/stellar/go/blob/abd5fb704/.github/actions/setup-go/action.yml#L51-L55

**Comment by vsvipul** [comment]
```
  # Reset the cache for master/protected branches, to ensure they build and run the tests from zero
  # and that the module cache is cleaned (otherwise it accumulates orphan dependencies over time).
```
This looks like a problem with Go itself and not with our action. Ideally, if the key provided is correct, like `package.json` in nodejs, which is always guaranteed to update in case a dependency is updated, it is guaranteed that it will clean the old cache and create a new one. So, I'm not able to understand how orphan dependencies can accumulate in this case.

If you don't want cache on the default branch you can add an if condition on the branch in the workflows itself like this -
```
on:
  push:
    branches:
      - '*'
      - '!master'
```

If you want a cache on master for the PRs to use, it is obvious to keep it updated. You can't have both the things-
- Not have cache on main branch.
- Have a cache for PRs to use.

And if the cache action is not run on main branch often, it will eventually get out of date. So it needs to be updated on every workflow run.

> but it feels a bit sad for GitHub Actions to be doing the work of restoring cache unnecessarily.
This I couldn't understand. Could you explain a bit more?

**Comment by leighmcculloch** [comment]
>This looks like a problem with Go itself and not with our action. Ideally, if the key provided is correct, like package.json in nodejs, which is always guaranteed to update in case a dependency is updated, it is guaranteed that it will clean the old cache and create a new one.

Caching is a tradeoff. Go doesn't check the contents of test fixtures and rather uses modified timestamps, because fixtures can be large files and costly to hash on every test run. Unfortunately I don't think this will change, and so the cache may be imperfect.

>If you want a cache on master for the PRs to use, it is obvious to keep it updated. You can't have both the things-

We do have both things actually. We add a `rm -rf ~/.cache/go-build ~/go/pkg/mod` on master builds, so that the cache is enabled, it is checked out, and we wipe it clean to guarantee it is fresh.

> > but it feels a bit sad for GitHub Actions to be doing the work of restoring cache unnecessarily.
> 
> This I couldn't understand. Could you explain a bit more?

Because `actions/cache` does not have a way for us to say "use cache, but don't load the cache stored at the cache key, only store the cache generated by this build," we end up loading a cache that we delete immediately. Ideally there would be a way for a job to save to a cache key without loading from it.

**Comment by vsvipul** [comment]
@leighmcculloch One workaround we discussed upon this was to not use restore-keys for protected branch. Something like this - 
```
  # Cache any build and test artifacts during the job, which will speed up
  # rebuilds and cause test runs to skip tests that have no reason to rerun.
  - uses: actions/cache@v2
    if: github.ref_protected
    with:
      path: ~/.cache/go-build
      key: ${{ env.PREFIX }}-go-build-${{ github.ref }}-${{ hashFiles('**', '!.git') }}
        
  # Cache any build and test artifacts during the job, which will speed up
  # rebuilds and cause test runs to skip tests that have no reason to rerun.
  - uses: actions/cache@v2
    if: !github.ref_protected
    with:
      path: ~/.cache/go-build
      key: ${{ env.PREFIX }}-go-build-${{ github.ref }}-${{ hashFiles('**', '!.git') }}
      restore-keys: |
        ${{ env.PREFIX }}-go-build-${{ github.ref }}-
        ${{ env.PREFIX }}-go-build-
```

This will allow only writes to the master branch and other branches can read from it using the `restore-keys` . Unfortunately, this is also not very straightforward, I get that. We are looking into options to allow user to only save or only restore cache as arguments, but nothing concrete for now. Will update if we do decide to work on that.

@headsvk You can also use the above solution with commit id as key for the main branch which will help you achieve what you want. Static keys don't make sense as the cache will never be updated in that case.
