### ISSUE TITLE
Unable to restore the cache across different builds

### ISSUE THREAD

**Issue by tbhaxor** [actions/cache#764]
I want to restore the yarn cache across different builds but it is being cached for the current build only. For example, if workflow 1 has cached, then workflow 2 should be able to restore the cache.

I am only able to restore the cache when supposedly any job fails and then I have to re-run 

```yaml
steps:
  - name: Get yarn cache directory path
    id: yarn-cache-dir-path
    run: 'echo "::set-output name=dir::$(yarn cache dir)"'
  - name: Restore the cache
    uses: actions/cache@v2
    id: yarn-cache
    with:
      path: '${{ steps.yarn-cache-dir-path.outputs.dir }}'
      key: '${{ runner.os }}-yarn-${{ hashFiles(''**/yarn.lock'') }}'
      restore-keys: |
        ${{ runner.os }}-yarn-

```
