### ISSUE TITLE
Yarn workspaces

### ISSUE THREAD

**Issue by chemitaxis** [actions/cache#77]
Hi, we need to work with yarn workspaces but we don't have any option to use a param to select which folder we need to cache... 

When we used CircleCI, we have something like this:

```
- save_cache:
    key: yarn-{{ checksum "yarn.lock" }}
    paths:
      - node_modules
      - workspace-a/node_modules
      - workspace-b/node_modules
```

Can we do that with Github Actions Cache? 

Thanks.
