### ISSUE TITLE
Problem with cache restore between container and not containers steps.

### ISSUE THREAD

**Issue by es1o** [actions/cache#787]
Hello.

I use cache@v3 and I have problem.

I have workflow with multiple jobs.

In one job I create a cache:
```
      - name: Cache public/build
        uses: actions/cache@v3
        id: vendor
        with:
          path: |
            public/build
          key: ${{ runner.os }}-${{ github.sha }}-${{ github.run_attempt }}
          restore-keys: |
            ${{ runner.os }}-${{ github.sha }}-${{ github.run_attempt }}
```

The cache is created, in logs I see:
```
Cache saved with key: Linux-5e15781dd06305d712a2f088383b3b0deecb8bfc-1
```

I have two more jobs, in one (that is executed right after job when I created cache) cache is restored successfully but in another I see:

```
Cache not found for input keys: Linux-5e15781dd06305d712a2f088383b3b0deecb8bfc-1, Linux-5e15781dd06305d712a2f088383b3b0deecb8bfc-1
```

I tried to comment job when cache is used (I thought that cache can be used only once) but without effect. Cache is not restored.

I use ubuntu-latest. Jobs when I create cache and job when cache works are running in container but job when cache doesn't work I don't use container.

When I create test job:
```
 cache-test:
    runs-on: ubuntu-latest
    container:
      image: myrepo:my_tag
      credentials:
        username: xxxxx
        password: yyyyy
      options: --user 1001

    steps:
      - name: Clean workspace
        run: rm -rf *

      - name: Trust My Directory
        run: export GIT_CEILING_DIRECTORIES=/__w # only work before git v2.35.2

      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - name: Cache public/build
        uses: actions/cache@v3
        id: vendor
        with:
          path: |
            public/build
          key: ${{ runner.os }}-${{ github.sha }}-${{ github.run_attempt }}
          restore-keys: |
            ${{ runner.os }}-${{ github.sha }}-${{ github.run_attempt }}
      - run: ls -lahrt public/build
```

Cache is working. Looks like when I create cache inside container it is not accessible if I use build on ubuntu-latest without container.

I found similar problem on stackoverflow: https://stackoverflow.com/questions/70761005/cache-created-in-ubuntu-latest-cannot-be-restored-in-docker-container
