### ISSUE TITLE
Issues with using cache across different jobs of the same workflow

### ISSUE THREAD

**Issue by dvcrn** [actions/cache#790]
Following usecase: Have a ubuntu machine do all the build and installation stuff, then cache the artifacts, spin up a macOS worker to do mac specific things and keep the runtime as low as possible (they're expensive)

Job1:
```
    - name: Cache multiple paths
      uses: actions/cache@v3
      with:
        path: |
           ./file1
           ./file2
           ./file3
        key: ${{ steps.vars.outputs.cache_key }}
```

Then in job2 (macOS):
```
  release:
    runs-on: macOS-latest
    needs: build // <- name of job above
    permissions:
    steps:
    - name: Restore from cache
      uses: actions/cache@v3
      with:
        path: |
           ./file1
           ./file2
           ./file3
        key: ${{ needs.build.outputs.cache_key }}
```

Cache key is computed with `${{ github.run_number }}` and is only used for sharing these artifacts to the release job to do the actual release steps.

Workflow output:

Job1:
```
Cache Size: ~21 MB (21741490 B)
Cache saved successfully
Cache saved with key: dist-20220426-94
```

Job2:
```
Run actions/cache@v3
Cache not found for input keys: dist-20220426-94
```

I was under the impression that it should be possible to restore the cache from a previous job of the same workflow, but now I'm wondering if that's not possible and if build artifacts have to be used
