### ISSUE TITLE
tar doesn't have permission to restore the cache

### ISSUE THREAD

**Issue by Xophmeister** [actions/cache#792]
I'm trying to use `actions/cache` to cache a Conda environment, that is created in the course of the workflow, on the GitHub-hosted Ubuntu runner. The steps I've taken to create the cache appear to work fine:

```yaml
- name: Setup Conda
  uses: conda-incubator/setup-miniconda@v2
  with:
    activate-environment: MY_ENV
    auto-activate-base: false

- name: Establish Conda environment directory
  id: conda_env
  run: |
    conda info --json | jq -r '"::set-output name=dir::\(.envs_dirs[0])"'

- name: Setup Conda environment caching
  id: cache
  uses: actions/cache@v3
  env:
    # Increase this to manually invalidate the cache
    CACHE_NUMBER: 0
  with:
    path: ${{ steps.conda_env.outputs.dir }}
    key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml', 'requirements.txt') }}-${{ env.CACHE_NUMBER }}

- name: Update Conda environment
  run: conda env update -n MY_ENV -f environment.yml
  if: steps.cache.outputs.cache-hit != 'true'
```

Here, the cache directory turns out to be `/usr/share/miniconda/envs`, which can be (and, indeed, is) written to. When the post-cache step runs, `actions/cache` archives and uploads about 2GiB of data, which is about what I would expect.

On subsequent runs, the key is matched and the download succeeds. However, when `actions/cache` comes to extracting the archive, it gives this error:

```
/usr/bin/tar: ../../../../../usr/share/miniconda/envs: Cannot utime: Operation not permitted
/usr/bin/tar: ../../../../../usr/share/miniconda/envs: Cannot change mode to rwxr-xr-x: Operation not permitted
/usr/bin/tar: Exiting with failure status due to previous errors
Warning: Tar failed with error: The process '/usr/bin/tar' failed with exit code 2
```

AFAIK, there's nothing special about `/usr/share/miniconda/envs`. What `tar` is trying to do requires elevated permissions, but that should only apply (I think) for files that are not owned by the current user. (That shouldn't be the case, but maybe the Conda action is doing something weird with ownership/permissions...)

While this may be a problem caused by something besides `actions/cache` -- it's hard to tell -- I feel that creating a cache that cannot later be extracted should fail, with a clear reason, before it gets to that point.

**Comment by Xophmeister** [comment]
Thanks, @Phantsure. I'm using the GitHub-hosted Ubuntu runner (i.e., `ubuntu-latest`), whose software manifest is [here](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md). It doesn't explicitly mention which version of `tar` it has installed, but if it's Ubuntu, then I would assume it to be GNU Tar, which is [definitely POSIX-compliant](https://www.gnu.org/software/tar/manual/html_node/posix.html).

**Comment by Phantsure** [comment]
@Xophmeister Does that mean this is not running in any containers? Refer this https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container
Is it possible to share the workflow file to verify failure? Thanks.

**Comment by Xophmeister** [comment]
There's not much to it beyond what I pasted above. It's basically:

```yaml
name: foo
on:
  pull_request:
  push:
    branches: main

defaults:
  run:
    shell: bash -l {0}

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # The steps outlined in the opening post to this issue

      # Some other, workflow-specific steps...
```
