### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by gnumoksha** [actions/cache#794]
This error started today, for no apparent reason:

```
Error: .github/workflows/test.yml (Line: 85, Col: 16):
Error: The template is not valid. .github/workflows/test.yml (Line: 85, Col: 16): An error occurred trying to start process '/home/runner/runners/2.290.1/externals/node16/bin/node' with working directory '/__w/my-project/my-project'. No such file or directory
```

Here is the `test.yml`. Line 85 is `key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}`
```yaml
[...]
steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
[...]
```
