### ISSUE TITLE
Unable to use inputs when using action/cache inside another action

### ISSUE THREAD

**Issue by lchenay** [actions/cache#803]
Here a bug that we found : 
- When using inputs as value for path in action/cache
- It's works if you directly use the action/cache inside workflow or another action
- it doesn't works if you user it from an action that is used inside another actions

The value of inputs is set to action/cache with the right value during run phase. But during the post phase the value become empty and we get a warning `Warning: Input required and not supplied: path`

We are using complex action for our IOS build. that resulting in a path like that:
* workflow -> action to prepare the env -> swift dedicated cache -> action/cache

Here A very simple flow to reproduce: https://github.com/lchenay/action-cache-bug
CF this run: https://github.com/lchenay/action-cache-bug/runs/6447875863?check_suite_focus=true

If I manually change the path to be `workflow -> complex-cache -> action/cache`, then it does works.

**Comment by vsvipul** [comment]
Hi @lchenay . This might be related to https://github.com/actions/runner/issues/665 .
When authoring a composite action, inputs must be mapped into inner steps using GitHub Actions [expressions](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions).

So in your  case try using 
```    
   - uses: actions/cache@v2
      name: "Cache"
      with:
        path: ${DIR}
        key: complex-cache
      env:
        DIR: ${{ inputs.dir }}

```

in `complex-cache/action.yaml` . This should fix it. If you have any comments about why this is the case and does not follow normal behaviour please follow up on the above linked issue. Thanks.

**Comment by lchenay** [comment]
It does work with that.
Thank you. Quick and perfect answer.

**Comment by mxxk** [comment]
Hmm, I also ran into the same issue but when I investigated the workaround I see that:

1. The `path` input passed to `actions/cache@v2` is literally the string `${DIR}`.
2. `actions/cache@v2` depends on the Actions Toolkit library `@actions/cache`, which does not perform any additional expansion of environment variables.
3. Since `${DIR}` does not exist as a literal path, the cache file saved is empty.

This is confirmed by examining the `Post Run actions/cache@v2` output with [GH actions step debugging enabled](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging):

```
##[debug]Search path '/home/runner/work/gh-actions-cache-issue-803/gh-actions-cache-issue-803/${CACHE_PATH}'
##[debug]Cache Paths:
##[debug][]
```

(Source: https://github.com/mxxk/gh-actions-cache-issue-803/runs/7440178030)

As such, I believe the solution proposed in https://github.com/actions/cache/issues/803#issuecomment-1127576674 didn't actually end up solving the problem. And since `actions/cache@v2` can save an empty cache archive (instead of `actions/cache@v3`, which prints a warning), it probably wasn't clear that the ["fixed" run](https://github.com/lchenay/action-cache-bug/runs/6451566574) saved an empty archive.

I'll open a new issue for this and include more information.

**Comment by mxxk** [comment]
Actually, the rootcause here may not be specific to `actions/cache` at all. I suspect it lies with `actions/runner`, but per the instructions in their new issue template, I posted on https://github.community/t/inputs-passed-to-action-are-blank-in-post-script/262930 to confirm that this is indeed an issue with the runner.

**Comment by keradus** [comment]
For those who stumbled on using `inputs` or `outputs` for composite GitHub Actions, I found using `$GITHUB_ENV` to be a viable workaround.

You may find a working example in https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7415 .
(And also a lot of debugging in https://github.com/keradus/PHP-CS-Fixer/pull/36 .)

```yml
name: "Install composer deps"

inputs:
  flags:
    description: 'Composer flags'
    required: false

runs:
  using: "composite"
  steps:
    # Warning!
    # Use $GITUB_ENV instead of $GITHUB_OUTPUT.
    #
    # The actions/cache is, on calling it in this composite action, reading the cache,
    # and then also registering a shutdown function for whole workflow, to write the cache afterwards.
    #
    # That registered shutdown function is _NOT_ having access to inputs.* nor steps.*.outputs for
    # `path` parameter, which is evaluated on both stages (read and write), yet `key` parameters
    # are evaluated on start only and are not affected by this issue.
    #
    # Unfortunately, when the issue is faced, it does not break the build, simply raising a warning
    # and completing the build successuflly, yet without storing the cache:
    # > Warning: Input required and not supplied: path

    - name: Get Composer cache params
      shell: bash
      run: |
        echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV
        echo "COMPOSER_CACHE_PHP=$(php -r 'echo PHP_VERSION;')" >> $GITHUB_ENV

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: ${{ env.COMPOSER_CACHE_DIR }}
        key: Composer-${{ runner.os }}-${{ env.COMPOSER_CACHE_PHP }}-${{ hashFiles('**/composer.json') }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          Composer-${{ runner.os }}-${{ env.COMPOSER_CACHE_PHP }}-${{ hashFiles('**/composer.json') }}-
          Composer-${{ runner.os }}-${{ env.COMPOSER_CACHE_PHP }}-
          Composer-${{ runner.os }}-

    - name: Install dependencies
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 5
        max_attempts: 5
        retry_wait_seconds: 30
        # `--no-scripts` to avoid side-effects (e.g. installing dev-tools for all jobs on CI level),
        # all executed scripts should be explicit and run only when needed.
        command: composer update --optimize-autoloader --no-interaction --no-progress --no-scripts ${{ inputs.flags }}

    - name: Show versions of packages
      shell: bash
      run: composer info -D

```
