### ISSUE TITLE
hashFiles does not accept variables

### ISSUE THREAD

**Issue by trombik** [actions/cache#805]
[hashFiles](https://docs.github.com/en/actions/learn-github-actions/expressions#hashfiles)

> Returns a single hash for the set of files that matches the path pattern. You can provide a single path pattern or multiple path patterns separated by commas. 

however, the documentation is not clear about what `path` means. from my experiment, it does not accept variables. `hashFiles('${{ matrix.box }}/box.pkr.hcl')` appears invalid. in all the examples I could find, `path` is a literal string.

is it possible to use variables in `path`? am I missing some trick to workaround?

the following is my failed attempt to use `hashFiles` with a variable.

```yaml
jobs:
  packer:
    runs-on: macos-10.15
    strategy:
      matrix:
        box:
          - FreeBSD-13.0
          - FreeBSD-12.3
          - OpenBSD-7.1
          - OpenBSD-7.0
          - OpenBSD-6.9
          - Ubuntu-20.04
          - Devuan-3
          - Devuan-4
          - Debian-11
          - Fedora-35
          - Fedora-36
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7 
          bundler-cache: true                                                                                                                                                                                                                                                   

      - name: Cache packer_cache
        uses: actions/cache@v2
        env:
          cache-name: packer_cache
        with:
          path: ${{ matrix.box }}/packer_cache
          key: packer_cache-${{ matrix.box }}-${{ hashFiles('${{ matrix.box }}/box.pkr.hcl') }}
```
