### ISSUE TITLE
Path Validation Error when caching on container jobs

### ISSUE THREAD

**Issue by Iduoad** [actions/cache#814]
When I use the cache action with a container job, the cache is not saved during the post cache step and instead I get the following error

```
Post job cleanup.
/usr/bin/docker exec  ecc19d4d[2](https://github.com/daoudi-mohammed/spring-boilerplate/runs/6771275062?check_suite_focus=true#step:10:2)b410eadd[3](https://github.com/daoudi-mohammed/spring-boilerplate/runs/6771275062?check_suite_focus=true#step:10:3)082d7a7d5d22cc782f29dfba69ac4a8edc83090a10843c sh -c "cat /etc/*release | grep ^ID"
Warning: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
```

Here is the code for my job
```yaml
jobs:
  unit-tests:
    
    runs-on: ubuntu-latest

    container: openjdk:17-jdk-alpine

    steps:
      - name: Setup git
        working-directory: ""
        run: |
          apk add -q --no-cache --no-progress git yq tar
          git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Cache maven packages
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.m2/repository
          key: test

      - name: Run liquibase update
        run: |
          mkdir -pv ${{ github.workspace }}/.m2/repository/
          echo "hello" > ${{ github.workspace }}/.m2/repository/hello.txt
```
I tried replacing the ${{ github.workspace }} with it's exact value (absolute path) but nothing worked.

However when I use a hardcoded path that has nothing to do with ${{ github.workspace }} it works
```yaml
with:
          path: |
            /test/.m2/repository
          key: test

      - name: Run liquibase update
        run: |
          mkdir -pv test/.m2/repository/
          echo "hello" > test/.m2/repository/hello.txt
```

**Comment by kotewar** [comment]
Hi @Iduoad 
Few questions for you. 
1. Are you using windows image? What all images are you facing this issue on?
2. What is the size of cache that's getting generated for you when you're hardcoding the path? Can you please share the logs?

**Comment by kotewar** [comment]
Thanks for sharing the info @Iduoad 
I used the workflow you shared with and without `${{ github.workspace }}`

I was able to run without any issues with `${{ github.workspace}}` , here's my [workflow file](https://github.com/kotewar/learning-actions/actions/runs/2459559476/workflow#L21) and corresponding [run with 
debug logs](https://github.com/kotewar/learning-actions/runs/6788169889?check_suite_focus=true)

Then I tried replacing the `${{ github.workspace}}` path with hardcoded paths as you suggested - 
 ```
          path: |
            /test/.m2/repository
          key: test
      - name: Run liquibase update
        run: |
          mkdir -pv test/.m2/repository/
          echo "hello" > test/.m2/repository/hello.txt
```
Here's my [workflow file](https://github.com/kotewar/learning-actions/actions/runs/2459566282/workflow#L21) and corresponding [run with debug logs](https://github.com/kotewar/learning-actions/runs/6788187925?check_suite_focus=true) after replacing `${{ github.workspace}}` with hardcoded values . However this time I got the error that you mentioned -
```
Warning: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
```
Then I realised that you are using `/test` in the path for `Cache maven packages` whereas the `Run liquibase update` runs in current working directory with `test/...` without `/` before the test. In other words `/test` is present at the root directory of your image whereas `test/...` is present in current working directory of your image. The current working directory is usually `/home/runner/work/repo-name/repo-name` so `test/...` would actually be `/home/runner/work/repo-name/repo-name/test/...` resulting into the following error -
<img width="924" alt="Screenshot 2022-06-08 at 12 17 52 PM" src="https://user-images.githubusercontent.com/98868223/172550308-0e577300-eea7-404d-839b-3eaea96854ef.png">
As you can see `Cache Paths` is having `[]` an empty array here because the path mentioned doesn't exist.

To confirm that, I ran the hardcoded workflow again, but this time without the `/` root reference `/test`. Here's my [workflow file](https://github.com/kotewar/learning-actions/actions/runs/2459610726/workflow/#L21) and corresponding [run with debug logs](https://github.com/kotewar/learning-actions/runs/6788302789?check_suite_focus=true) with `test` for the same. 

As you can see below, this time the paths were found and cache was saved successfully.
<img width="1268" alt="Screenshot 2022-06-08 at 12 20 34 PM" src="https://user-images.githubusercontent.com/98868223/172550831-c1c8de49-ccc5-4d40-b5de-8b65b46e1d13.png">

Please check the workflows and their outputs and let me know if you see any issues in the executions I've done based on the info you've provided. If everything seems correct, please validate your actual workflow files for any typo or `/` root references. 
The `Path Validation Error` warning you have received is a recent implementation done to avoid empty cache saves. And this also helps users realise that the paths they've provided might not have any content at all if provided incorrectly.

Do let me know your findings, happy to help! :)

**Comment by Iduoad** [comment]
Thank you @kotewar for the detailed description. 

The only difference is that I run a container job like I mentioned before.

Sorry if that wasn't clear. I edited the issue's description to mention that.

Here is the workflow file
```
jobs:
  unit-tests:
    
    runs-on: ubuntu-latest

    container: openjdk:17-jdk-alpine

    steps:
      - name: Setup git
        working-directory: ""
        run: |
          apk add -q --no-cache --no-progress git yq tar
          git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Cache maven packages
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.m2/repository
          key: test

      - name: Run liquibase update
        run: |
          mkdir -pv ${{ github.workspace }}/.m2/repository/
          echo "hello" > ${{ github.workspace }}/.m2/repository/hello.txt
```

**Comment by kotewar** [comment]
Let me check the behaviour with `openjdk:17-jdk-alpine` and get back to you.

**Comment by kotewar** [comment]
Here's the difference after using openjdk container.

The search path is getting evaluated to - 
>Search path '/__w/learning-actions/learning-actions/.m2/repository'

whereas the given path in action is - `/home/runner/work/learning-actions/learning-actions/.m2/repository`

<img width="1346" alt="Screenshot 2022-06-08 at 2 33 27 PM" src="https://user-images.githubusercontent.com/98868223/172577346-fb04fd21-9ff7-4000-aa99-87478f44eb0b.png">
[Workflow file](https://github.com/kotewar/learning-actions/actions/runs/2460328311/workflow) [logs](https://github.com/kotewar/learning-actions/runs/6790248919?check_suite_focus=true)
I need to find out why the value of `${{ github.workspace }}` needs to be `/__w` in case of `openjdk:17-jdk-alpine` container.

Note - I've used previous version v3.0.2 of @actions/cache hence its not giving any error message, but also it would be storing and restoring empty cache as nothing exists at the path provided.

**Comment by kotewar** [comment]
This is a mixed scenario where the workflow is running on ubuntu image sometimes, and on the container the rest of the times. That's why `${{ github.workspace }}` is sometimes evaluated as `/__w` and `/home/runner/work/repo-name/repo-name` the rest of the times. To investigate the issue, we went ahead to understand the behaviour of actions when ran in a container. If interested to know, please refer the [workflow](https://github.com/aparna-ravindra/simple-java-maven-app/actions/runs/2461935913/workflow) and [run](https://github.com/aparna-ravindra/simple-java-maven-app/runs/6794806123?check_suite_focus=true) executed to understand the same. The logs will give you a better idea of the same.

To conclude our understandings, here's what we found -
1. Containers will always have `${{ github.workspace }}` as `/__w`. If anything is running with `/home/runner/work/repo-name/repo-name` as current working directory, its outside your container in the `ubuntu-latest` image (or base image for that matter).
2. To run actions cache inside the container for java application, the appropriate location of `.m2` folder must be known. After investigation, it turns out that `.m2` folder in `openjdk:17-jdk-alpine` is actually present at `/root/.m2/repository` location. So this should actually be the path that must be used to cache the `/.m2/repository` folder. Refer [this](https://stackoverflow.com/a/16218772/6279996)
3. After the `/.m2` folder is located, it should be referred in path parameter of the cache action.

Sample code to get `.m2` folder location and setting it in the appropriate location.
```
     - id: cache-path
        run: | 
          echo "::set-output name=dir::$(mvn help:evaluate -Dexpression=settings.localRepository | grep 'm2/repository')"
      - name: Cache maven packages
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.cache-path.outputs.dir }}
          key: test_100
```

Please try using this and see if you get the expected results. You can refer this [workflow](https://github.com/aparna-ravindra/simple-java-maven-app/blob/fd65225ee7bb149747f626e8fd920195db634f61/.github/workflows/test_container.yaml).
Hope this helps! 😊
