### ISSUE TITLE
'Job A' unable to access cache of downstream 'Job B'

### ISSUE THREAD

**Issue by underyx** [actions/cache#817]
Heya! I have these two jobs where Job B needs Job A: https://github.com/returntocorp/semgrep/blob/a9e8b90c2e3de705c54ca311b414608ffaa32ff7/.github/workflows/tests.yml#L15-L67

Both jobs do this:

```yaml
        uses: actions/cache@v3
        with:
          path: ocaml-build-artifacts.tgz
          key: foo
```

But only Job B ever builds that artifact, while Job A only tries to restore it to see if Job B can be skipped altogether.

Now, I don't see why this wouldn't work, but it does not, see these logs:

- Job A fails to restore the cache: https://github.com/returntocorp/semgrep/runs/6823861478?check_suite_focus=true#step:5:38
- Job B successfully restores the cache: https://github.com/returntocorp/semgrep/runs/6823863765?check_suite_focus=true#step:6:61

I would expect the restore to succeed in Job A as well.
