### ISSUE TITLE
Missing a way to update package cache when upstream versions change

### ISSUE THREAD

**Issue by robx** [actions/cache#82]
One common use case for caching appears to be caching build dependencies, like:

```
- name: Dependency cache
  uses: actions/cache@v1
  with:
    key: {os}-{language tooling version}-${{ hashFiles('dependencies') }}
- run: pkgtool update
- run: pkgtool build-dependencies
```

Unless dependency versions are precisely specified using some lock file, this will mean that the key doesn't change with time / newly released upstream dependency versions. On the other hand the call to `pkgtool update` will be aware of those upstream updates, and hence they will be rebuilt. But since the cache key doesn't change, actions/cache won't update the cache.

I see a couple of approaches to address this, but none seem to be available right now:

- allow specifying whether to update the cache even on a cache hit, using something like `with: update: true`
- provide the current date or timestamp, which might then be incorporated in the cache key
- have actions/cache take pre- and post-checksums of the cached path, and update the cache if the checksum changed

**Comment by stevencpp** [comment]
+1 . I think vcpkg needs something like to be able to handle the case where one of the packages is updated (or a new dependency is added), and you want to load the cache, rebuild only that single package (instead of rebuilding all of the dependencies) and save the cache. ccache/clcache probably need the same incremental caching support as well.

**Comment by joshmgross** [comment]
@robx If you want to use the date in your key, you can do something like:
```yaml

# http://man7.org/linux/man-pages/man1/date.1.html
- name: Get Date
  id: get-date
  run: |
    echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
  shell: bash # For Windows, Linux and macOS default to bash already

- uses: actions/cache@v1
  with:
    path: ~/.cache/directory
    key: ${{ runner.OS }}-build-${{ steps.get-date.outputs.date }}
```
