### ISSUE TITLE
Cache Not Restored if Created on Base Branch

### ISSUE THREAD

**Issue by daniel-nagy** [actions/cache#823]
Given the following branches,

`main -> base-1 -> base-2`

Caches created on `base-1` cannot be restored on `base-2`. However, according to the documentation it sounds like this should work.

> A workflow can access and restore a cache created in the current branch, the base branch (including base branches of forked repositories), or the default branch (usually main)

This is enough to reproduce.

```yaml
name: GH Actions Test
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    env:
      BASE_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || '' }}
      HEAD_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
    runs-on: ubuntu-latest
    steps:
      - name: try to restore cache from base branch
        if: github.event_name == 'pull_request'
        id: restore-cache
        uses: actions/cache@v3
        with:
          path: ${{ env.BASE_SHA }}
          key: ${{ runner.os }}-${{ env.BASE_SHA }}
      - name: cache
        uses: actions/cache@v3
        with:
          path: ${{ env.HEAD_SHA }}
          key: ${{ runner.os }}-${{ env.HEAD_SHA }}
      - name: debug
        run: echo ${{ steps.restore-cache.outputs.cache-hit }}
      - name: create file
        run: |
          mkdir $HEAD_SHA 2>/dev/null && echo 'foo' > "$HEAD_SHA/foo.txt"
```

`base-1` is able to restore the cache create by `main` but `base-2` is not able to restore the cache created by `base-1`.
