### ISSUE TITLE
Add timeout 

### ISSUE THREAD

**Issue by janisz** [actions/cache#824]
Add timeout for retrieving data from cache. Here I have example when it took over 5h. It wil be great if I can set a limit to 1 minute
https://github.com/janisz/DU/runs/6930686406?check_suite_focus=true

**Comment by Gelassen** [comment]
@janisz you might be interested to add a timeout for your job as a whole: 

```
  build-and-test:
    name: ⚙️ Build, Lint and Test
    runs-on: macos-latest
    if: ${{ !github.event.pull_request.draft }}
    timeout-minutes: 30 
```
Ref: https://github.com/boitakub/Bogadex/blob/main/.github/workflows/main.yml
