### ISSUE TITLE
Is it possible to have time-based cache expiration?

### ISSUE THREAD

**Issue by DanTup** [actions/cache#83]
For example, the latest stable Dart SDK is at:

https://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-{os}-x64-release.zip

The URL does not change when a new stable release is made, but there's no easy access to invalidate a cache because it's not easy to tell if the zip contains a new version. It'd be convenient to be able to cache a folder for a period (for ex. 24hours) and have it automatically removed (regardless of use when it was last accessed).

This would ensure you're generally on the latest version (to within 24hrs, or whatever) but you don't need to download it every time.

There are many parts of my builds that are versioned similarly to this (Dart stable/dev SDK, Flutter master/dev branch, VS Code stable/insiders builds) and trying to code caching strategies for them all would be complicated so it's easiest to just download them every time, but a short time-based cache would save on both resources and runtime.

**Comment by joshmgross** [comment]
@DanTup you could incorporate the date into your key, to ensure that every day you create a new cache. Unused caches will already be evicted after 7 days, so you don't need to worry about that (see [docs](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy))

Example:
```yaml

# http://man7.org/linux/man-pages/man1/date.1.html
- name: Get Date
  id: get-date
  run: |
    echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
  shell: bash # For Windows, Linux and macOS default to bash already

- uses: actions/cache@v1
  with:
    path: ~/.cache/directory
    key: ${{ runner.OS }}-build-${{ steps.get-date.outputs.date }}
```

Leaving off `restore-key` if you don't want any other caches from previous dates.
