### ISSUE TITLE
How can I cache based on package-lock in case of tag (bump a verison)

### ISSUE THREAD

**Issue by johnico** [actions/cache#837]
i am  tagging a version using npm version prerelease that bump the version tag in package.json 
but then i lost the cache because package.json has been changed 

is there any option to make the cache working if only package.json version has changed ?

i am using the example

```
    - name: Cache node modules
      id: cache-nodemodules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # caching node_modules
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    
    - name: Install Dependencies
      if: steps.cache-nodemodules.outputs.cache-hit != 'true'
      run: npm ci
```
