### ISSUE TITLE
Cache miss even tho key exists

### ISSUE THREAD

**Issue by BeyondEvil** [actions/cache#843]
We're using `actions/cache@v3` in self-hosted runners (ubuntu-based).

We get a cache hit in one branch:

```
Cache restored successfully
Cache restored from key: v16.15.0-nodemodules-91bd5669329abf8e285e2b706e76bc9787848689b31ec5755f991616af28e407
```

Then, roughly an hour later, in a different branch (same workflow), we get a cache miss _for the same key_:

```
Cache not found for input keys: v16.15.0-nodemodules-91bd5669329abf8e285e2b706e76bc9787848689b31ec5755f991616af28e407
```

Why?

No other workflow runs took place between them.

This is the action we're using:

```yaml
name: 'Install Node dependencies'
description: 'Install Node dependencies'
author: 'proxyco'

inputs:
  path:
    default: '.'
    description: 'Location of node_modules'
    required: false
  node-version:
    description: 'The Node version'
    required: true

runs:
  using: "composite"
  steps:
    - name: Cache node_modules
      id: node-modules
      uses: actions/cache@v3
      with:
        path: ${{ inputs.path }}/node_modules
        key: ${{ inputs.node-version }}-nodemodules-${{ hashFiles(format('{0}/package-lock.json', inputs.path)) }}

    - name: Install dependencies
      if: steps.node-modules.outputs.cache-hit != 'true'
      # Skip post-install scripts here, as a malicious
      # script could steal NODE_AUTH_TOKEN.
      run: npm ci --ignore-scripts
      shell: bash
      working-directory: ${{ inputs.path }}
```

usage:

```yaml
      - name: Set Node version
        run: echo ::set-output name=NODE_VERSION::$(node --version)
        id: nvm

      - name: Install dependencies
        uses: ./.github/actions/npm-install
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
```

**Comment by kuhnroyal** [comment]
Had same thing happening, the cache API uses a version query param which you can see when you enable debug logging for Github Actions.

The version is just a hash of the cache paths and the compression algorithm, see https://github.com/actions/toolkit/blob/main/packages/cache/src/internal/cacheUtils.ts#L87

For me the version hash while the cache key was correct.
Solution was to uniformly install `zstd` on all nodes with `sudo apt install zstd` or `brew install zstd`.
One node had this already installed and was getting cache misses all the time.

**Comment by BeyondEvil** [comment]
> Had same thing happening, the cache API uses a version query param which you can see when you enable debug logging for Github Actions.
> 
> The version is just a hash of the cache paths and the compression algorithm, see https://github.com/actions/toolkit/blob/main/packages/cache/src/internal/cacheUtils.ts#L87
> 
> For me the version hash while the cache key was correct. Solution was to uniformly install `zstd` on all nodes with `sudo apt install zstd` or `brew install zstd`. One node had this already installed and was getting cache misses all the time.

Interesting, thanks for sharing! I will turn on debug logging and check.

Question: When you say "node" do you mean the runner?

**Comment by kuhnroyal** [comment]
> Question: When you say "node" do you mean the runner?

Yea

**Comment by vsvipul** [comment]
@BeyondEvil Yes, this is expected. You will get a cache miss on a different branch if the cache save happened on a different branch with the same key, unless the save happens in the main/master branch, in which case all the other branches can access it. Please let me know if you have any more questions.

**Comment by BeyondEvil** [comment]
Interesting, I'll have to check if the key exists in the main branch, as neither of the two branches involved here are main.

**Comment by aminya** [comment]
Cache restoration is very buggy. I am pretty sure that "restore-keys" doesn't help much. It misses even if I make a basic change.

**Comment by kotewar** [comment]
@aminya, can you please share examples (key and restore key) of when you saw the cache miss, along with the branch the cache was present in and the branch that trying to restore it?

**Comment by aminya** [comment]
Here is the configuration. The matrix values all exist.

```yaml
      - name: Cache
        id: my-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/
            ./target/
            ~/.pnpm-store
            D:\.pnpm-store
            ~/.local/share/pnpm/store/
            ~/AppData/Local/pnpm/store/
          key: "my-cache-OS:${{ matrix.os }}-Rust:${{ matrix.rust }}-${{ hashFiles('./**/Cargo.toml') }}-${{ hashFiles('./.cargo/config.toml') }}-Cpp:${{ matrix.cpp }}-Node:${{ matrix.node }}-${{ matrix.pnpm }}-${{ hashFiles('./.npmrc') }}-${{ hashFiles('./package.json') }}"
          restore-keys: |
            "my-cache-OS:${{ matrix.os }}-Rust:${{ matrix.rust }}-"
```

**Comment by kotewar** [comment]
Thanks @aminya. Did you try to restore keys across different branches? Please refer [this](https://github.com/actions/cache/issues/843#issuecomment-1179771256)

**Comment by aminya** [comment]
Well, surprisingly enough, the cache misses across different branches. But I am aware of that bug, and this was not that.

**Comment by kotewar** [comment]
Is your repo public @aminya ? If yes please share the link where you saw the failures. Else please run in DEBUG mode and share the logs here.

Moreover FYI, we recently released APIs for [cache management](https://docs.github.com/en/rest/actions/cache#list-github-actions-caches-for-a-repository) and [CLI extension ](https://github.com/actions/gh-actions-cache)for the same. Requesting you to please use the same to list caches and check if the cache you're expecting to hit is present or evicted. If present, please make sure it is present in the `default` branch (main/master).

Secondly, here's some info on [Cache scopes](https://github.com/actions/cache#cache-scopes), it is not a bug, rather a feature. 
> The cache is scoped to the key and branch. The default branch cache is available to other branches.

**Comment by vsvipul** [comment]
Closing this. Tracking the docs change for the same at https://github.com/actions/cache/issues/823 .

**Comment by aminya** [comment]
> Secondly, here's some info on [Cache scopes](https://github.com/actions/cache#cache-scopes), it is not a bug, rather a feature.

Not a good feature. It is undermining GitHub's biggest feature which is making a pull request.

https://github.com/actions/cache/issues/79#issuecomment-1204808650

**Comment by claycoleman** [comment]
I'm seeing a problem with this issue as well. I checked the caching docs for cache scopes and saw it says not only the `default` branch should be checked, but also the parent or upstream branches. Here's a quote from [the docs](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#matching-a-cache-key):

> The cache action first searches for cache hits for key and restore-keys in the branch containing the workflow run. If there are no hits in the current branch, the cache action searches for key and restore-keys in the parent branch and upstream branches.

However, the behavior i'm seeing is that i'm still getting cache misses for `restore-keys` when the parent branch has a cached value and the current branch has the same prefix as the parent branch. This makes me believe there's a bug in the cache scopes logic on the `ACTIONS_CACHE_URL` / 
 `artifactcache.actions.githubusercontent.com` endpoint at `/_apis/artifactcache/cache`.

Here are the outputs from a recent CI build:

parent branch output (which ran and completed first): `Cache restored from key: Linux-yarn-v1-f2a5eba87e3842f3c8af956155ff7665aaa716c5195121736d43345199595a0b`

child branch (which ran after parent branch CI): `Cache not found for input keys: Linux-yarn-v1-a3a9c5880d5a5f56809c4a05c1f01f2ddd9a86189280acfbaccb007e30578e6c, Linux-yarn-v1-`

In this instance, I don't expect a full cache match because the keys are different (which is due to a change in our `yarn.lock` file, see the config below). however, i do expect the `restore-keys` value of `Linux-yarn-v1-` to match the parent branch output so that we can get a partial cache restoration.

here's the relevant snippet from our `action.yml`:

```
    - name: Setup Yarn cache
      uses: actions/cache@v3
      id: yarn-cache
      with:
        ... some config omitted ...
        key: ${{ runner.os }}-yarn-v1-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-v1-
```

Would really appreciate if someone could look into if there's a bug on the GitHub implementation of cache scopes. cc @vsvipul @kotewar
