### ISSUE TITLE
Timeout waiting for emulator to boot. caused by actions/cache@v3

### ISSUE THREAD

**Issue by Gelassen** [actions/cache#844]
Sometimes github CI has an issue to launch avd from cached instance. `Timeout waiting for emulator to boot.` I have to remove your github action step from my build as it is not reliable to smooth CI process as it should be. I also consider option the issue might be on my side due not correct configuration.   

In case you would like to investigate this issue, here [a link on commit](https://github.com/Gelassen/government-rus/actions/runs/2607978558) and android.yaml file

```
name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [29]
        target: [default]

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    
    - name: checkout 
      uses: actions/checkout@v3
    
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Grant execute permission for gradle
      run: chmod +x gradle
      
    - name: AVD cache
      uses: actions/cache@v3
      id: avd-cache
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: avd-${{ matrix.api-level }}
        
    - name: create AVD and generate snapshot for caching
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: false
        script: echo "Generated AVD snapshot for caching."
    
    - name: Build with Gradle
      run: gradle build
      
    - name: Printing directory structure
      run: pwd && ls
    
    - name: Run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        force-avd-creation: false
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 5
        script: gradle connectedAndroidTest
        
    - name: Zip build reports
      id: zipBuildReports
      if: always()
      run: zip -r build-reports.zip app/build/reports
    
    - name: Upload build reports
      if: always() && steps.zipBuildReports.outcome == 'success'
      uses: actions/upload-artifact@v2
      with:
        name: build-reports
        path: build-reports.zip
        retention-days: 3
```

Steps to reproduce:
1. Add this config file
2. Write some UI\Espresso tests and confirm it works locally
3. Push to the remote github repo

Observed behavior:
CI starts, job ends with error `Timeout waiting for emulator to boot.` 

Expected behavior:
CI starts, job ends successfully
