### ISSUE TITLE
Wrong ref set for cache on release.type.published with explicit branch checkout

### ISSUE THREAD

**Issue by iamolegga** [actions/cache#846]
I have a workflow that is triggered on release

```
on:
  release:
    types: [published]
```

And I set ref to main branch explicitly for checkout action, because cache with tags' refs are cannot be reused for feature branches, see #556 . Checking out for main branch is ok for me as it's the same code version as the last release.

```
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
```

Anyway the cache is created with the tag ref

```
curl \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Authorization: token MY_TOKEN" \
  https://api.github.com/repos/org/repo/actions/caches

{
  "total_count": 5,
  "actions_caches": [
    {
      "id": 8,
      "ref": "refs/tags/<TAG>",
      "key": "MY_KEY",
      "version": "...",
      "last_accessed_at": "2022-07-04T11:58:15.810000000Z",
      "created_at": "2022-07-04T11:58:15.810000000Z",
      "size_in_bytes": 76343
    },
    ...
  ]
}
```

And for the feature branch the cache is not visible anyway:

```
Run actions/cache@v3
Cache not found for input keys: MY_KEY
```

**Comment by iamolegga** [comment]
Anyway for those who struggle I found a workaround, make a separate workflow with

```
on:
  workflow_run:
    types: [completed]
    workflows: [Original workflow]
```

then the cache is created successfully.
