### ISSUE TITLE
Windows path validation error

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [actions/cache#862]
It works in the rest of the runners but fails on Windows.

Log:
```
Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
```

Code:
```yaml
- name: Restore Kotlin native cache
  uses: actions/cache@v3.0.4
  with:
    path: ~/.konan
    key: ${{ runner.os }}-konan-${{ hashFiles('**/gradle/libs.versions.toml') }}
    restore-keys: |
      ${{ runner.os }}-konan-
```

**Comment by tiwarishub** [comment]
👋  @JavierSegoviaCordoba, can you confirm this directory ``~/.konan`` actually exist in windows.

**Comment by JavierSegoviaCordoba** [comment]
I haven't checked on CI, but in my Windows machine, it exists.

**Comment by Danielku15** [comment]
I have a similar issue on my workflow. I create a text file in a folder, but it is claimed that the file is not found. 

```yaml
      - run: |
          mkdir check-sha
          echo ${{ github.sha }} >> check-sha/github-sha.txt
        
      - uses: actions/cache@v3
        id: check_sha
        with:
          path: check-sha
          key: check-sha-${{ github.sha }}
```

Leads to 

````
Post job cleanup.
Warning: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
```

Workflow file: 
https://github.com/CoderLine/alphaTab/blob/5ee3fd60dd48798c3364b74157cbf5437bf261fa/.github/workflows/publish.yml#L12-L20

Workflow run: 
https://github.com/CoderLine/alphaTab/actions/runs/4129942850/jobs/7136110557


I think in an old version the same code was working fine but it started to fail with upgrading to `v3`.
