### ISSUE TITLE
Cache not requesed (not found) between workflows

### ISSUE THREAD

**Issue by pro100svitlo** [actions/cache#898]
Hi!

I have a shared (called) workflow, which I am reusing between few others. As an input param it receive a sha for the commit code. This sha is used as a key.
As result, when I run sequently those workflows with same sha
- for the first one cache obviously is empty, so caching happened
- for the second workflow cache should be present, but it missed

Here is my called workflow
```yaml
name: Prepare code

on:
  workflow_call:
    inputs:
      commit_sha:
        required: true
        type: string

jobs:
  main:
    runs-on: ubuntu-latest

    steps:

      - name: 📦 Activate cache for last commited code
        id: cached-commit
        uses: actions/cache@v3
        with:
          path: ./
          key: ${{ inputs.commit_sha }}

      - name: ⏬ Checkout repo last commit
        if: steps.cached-commit.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.commit_sha }}

```

And here is how I call it from 2 other workflows:

```yaml
jobs:

  Prepare_code:
    uses: ./.github/workflows/prepare_code.yaml
    with:
      commit_sha: ${{ github.event.pull_request.head.sha }}
```

```yaml
jobs:

  Prepare_code:
    uses: ./.github/workflows/prepare_code.yaml
    with:
      commit_sha: ${{ github.sha }}
```

Am I doing something wrong?
Thanks 🙏🏼
