### ISSUE TITLE
Unable to Cache Rust Build Output Due to Unreadable .lock Files

### ISSUE THREAD

**Issue by xanderdunn** [actions/cache#909]
I have a Rust build in GitHub Action and I'd like to cache the build output. I have:
```yml
      - name: Cache the Build
        id: cache-my-build
        uses: actions/cache@v3
        with:
          path: |
            target/
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-my-build
```

In the Post Cache step I see dozens of tar permission errors on .lock files:
```
Post job cleanup.
[2](https://github.com/ava-labs/teleporter/runs/8006774164?check_suite_focus=true#step:11:2)
/usr/bin/tar --posix --use-compress-program zstdmt -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/teleporter/teleporter --files-from manifest.txt
[3](https://github.com/ava-labs/teleporter/runs/8006774164?check_suite_focus=true#step:11:3)
/usr/bin/tar: target/debug/incremental/ic_types-38y9ygvd3lww8/s-gcwv8nghwl-1l0sm9e.lock: Cannot open: Permission denied
[4](https://github.com/ava-labs/teleporter/runs/8006774164?check_suite_focus=true#step:11:4)
/usr/bin/tar: target/debug/incremental/build_script_build-28ubg68lsk6r/s-gcwv8he75c-1w1htdu.lock: Cannot open: Permission denied
...
```

Due to the limitations of the glob pattern matching, as described [here](https://github.com/actions/toolkit/issues/713#issuecomment-1030643364), I'm unable to exclude `*.lock` files, and they're all in different directories. 

Is there any way for me to get around this? I would be content if the action just passed `--ignore-failed-read` to the tar command so that it would ignore these files and continue to pack up the files it can read.
