### ISSUE TITLE
Caching inside GitHub's built-in container support for jobs

### ISSUE THREAD

**Issue by dime10** [actions/cache#924]
Is there a way to make this action work with GitHub's built-in container support for jobs?

For example the step below results in a cache miss, whereas it would produce a cache hit if run without the `container:` parameter:

```
jobs:
  test:
    name: Test Job
    runs-on: ubuntu-22.04
    container: quay.io/pypa/manylinux2014_x86_64
    steps:
    - name: Cache Files
      id: cache-files
      uses: actions/cache@v3
      with:
        path: files
        key: some-key
```
