### ISSUE TITLE
Download speed on self-hosted runners is significantly slower

### ISSUE THREAD

**Issue by ajmnz** [actions/cache#928]
👋🏼

We've started working with self-hosted runners, but noticed that the download speed when downloading the cache is significantly slower than on hosted runners. Here's the breakdown of what is happening:

- Self-hosted runner version: `2.296.2`
- Cache size: `~300MB`
- Average download speed
  - Hosted runners: `50 MBs/s`
  - Self-hosted runners: `3.5 MBs/s`

Hosted:

<img width="414" alt="Screenshot 2022-09-19 at 18 34 01" src="https://user-images.githubusercontent.com/57961822/191067687-7b43ef3d-518d-40f7-9c5b-4149a97aab34.png">

Self-hosted:

<img width="490" alt="Screenshot 2022-09-19 at 18 33 38" src="https://user-images.githubusercontent.com/57961822/191067622-e24d7f2d-8110-431f-b960-7148d4d025c7.png">

Workflow:

```yml
      - name: Cache yarn dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile
```

I'm pretty confident there's no limitation on our machine, and I'm not sure if this is a limitation on the runner itself, but at that speed installing dependencies takes practically the same time as pulling the cache.

Thanks in advance!
