### ISSUE TITLE
Pipenv failing to locate python version.

### ISSUE THREAD

**Issue by lewiswolf** [actions/cache#932]
My github workflow which uses pipenv has stopped being able to locate python. I've tried to fix this in a couple of places, but have only seemed to make the problem worse. https://github.com/lewiswolf/kac_drumset/pull/17#partial-pull-merging

The error I am concerned about is 
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/.local/share/virtualenvs/kac_drumset-8k23AR3r/bin/python'
```

My workflow looks like this:

```
    all-tests:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]
                python: ["3.9", "3.10"]

        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - uses: lukka/get-cmake@latest
            - uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python }}
            - uses: actions/cache@v3
              id: cache-pipenv
              with:
                  path: ~/.local/share/virtualenvs
                  key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}

            - name: Install OS specific dependencies
              if: ${{ matrix.os == 'ubuntu-latest' }}
              run: sudo apt-get install libsndfile1

            - name: Install pipenv
              run: python -m pip install --upgrade pip pipenv setuptools wheel

            - name: Install python dependencies
              run: pipenv install -d --python ${{ matrix.python }}
```

The workflow always fails on the last step shown above. This initially was only happening on macos-latest, but is now also happening on other operating systems.

Thanks,
Lewis
