### ISSUE TITLE
Dynamic cache key not found under same cache scope

### ISSUE THREAD

**Issue by Luc45** [actions/cache#933]
I have workflow that runs many jobs in a matrix, and calls a workflow to warm up the cache for the matrix:

![image](https://user-images.githubusercontent.com/9341686/191846644-f6bc80f8-6955-4903-a3a2-ac5074582424.png)

In `setup-docker-cache.yml`, I warm up the cache:

```
- name: Warm up WordPress Docker Image Cache
  if: inputs.WORDPRESS_VERSION != '' && inputs.PHP_VERSION != ''
  uses: actions/cache@v3
  id: cache-docker-wordpress
  with:
    path: ci/cache/docker/wordpress
    key: ${{ steps.cache-docker-wordpress-sha.outputs.sha }}
    restore-keys: cache-docker-wordpress-${{ inputs.WORDPRESS_VERSION }}-php-${{ inputs.PHP_VERSION }}
```

See the `restore-keys`:

![image](https://user-images.githubusercontent.com/9341686/191853447-532365a6-1f1f-4e03-b7f8-d70c9985816e.png)

And in the matrix I restore the cache:

```
- name: Restore WordPress Image Cache - Step 1
  id: cache-docker-wordpress
  uses: actions/cache@v3
  with:
    path: ci/cache/docker/wordpress
    key: cache-docker-wordpress-${{ matrix.test_run.environment.wordpress_version }}-php-${{ github.event.client_payload.setup_cache.php_version }}
```

But it can't find the cache key:

![image](https://user-images.githubusercontent.com/9341686/191850538-fe0a9533-771a-49de-9f28-3093e732521c.png)

Notice that the cache `key` matches the `restore-keys`, but the cache is not found. **If instead I use a simple string such as `cache-docker-wordpress`, then it finds the cache.**

The keys produce the same string when evaluated, so I think it should have worked?

**Comment by Luc45** [comment]
To make sure there wasn't any rogue trailing spaces at play, I tried to normalize the inputs to test, still no luck:

In the warm-up job:
```
- name: Warm up WordPress Docker Image Cache
  uses: actions/cache@v3
  env:
    WORDPRESS_VERSION: 6.0.2
    PHP_VERSION: 7.4
  with:
    path: ci/cache/docker/wordpress
    key: ${{ steps.cache-docker-wordpress-sha.outputs.sha }}
    restore-keys: cache-docker-wordpress-${{ env.WORDPRESS_VERSION }}-php-${{ env.PHP_VERSION }}
```

![image](https://user-images.githubusercontent.com/9341686/191859548-8536cf46-a98a-487e-8f89-b67ac21705b3.png)


In the matrix:

```
- name: Restore WordPress Image Cache - Step 1
  uses: actions/cache@v3
  env:
    WORDPRESS_VERSION: 6.0.2
    PHP_VERSION: 7.4
  with:
    path: ci/cache/docker/wordpress
    key: cache-docker-wordpress-${{ env.WORDPRESS_VERSION }}-php-${{ env.PHP_VERSION }}
```

![image](https://user-images.githubusercontent.com/9341686/191859515-a0711543-a6ea-490b-9c1f-d509d97d34d1.png)

**Comment by Luc45** [comment]
It doesn't seem to be directly related to dynamic keys:

In the warm-up job:

```
- name: Warm up WordPress Docker Image Cache
  uses: actions/cache@v3
  with:
    path: ci/cache/docker/wordpress
    key: ${{ steps.cache-docker-wordpress-sha.outputs.sha }}
    restore-keys: cache-docker-wordpress-6.0.2-php-7.4
```
![image](https://user-images.githubusercontent.com/9341686/191859966-ff81c538-48ec-4bf0-9cd6-b7e8fc42755f.png)


In the matrix:

```
- name: Restore WordPress Image Cache - Step 1
  uses: actions/cache@v3
  with:
    path: ci/cache/docker/wordpress
    key: cache-docker-wordpress-6.0.2-php-7.4
```
![image](https://user-images.githubusercontent.com/9341686/191860104-707daff7-530c-4206-85aa-4c0d09e3848a.png)

**Comment by Luc45** [comment]
I eventually dropped `restore-keys` entirely and am now matching only direct `key`, I was bursting the cache when the SHA of the image changed, which would achieve a good cache retention, but given the issue above, I decided to use a simple `key` with a daily cache burst to make sure the cache is renewed at least daily.

```
- name: Daily Cache Burst.
  id: daily-cache-burst
  run: echo "::set-output name=cache-burst::$(date +'%j')"

- name: Warm up WordPress Docker Image Cache
  uses: actions/cache@v3
  id: cache-docker-wordpress
  with:
    path: ci/cache/docker/wordpress
    key: cache-docker-wordpress-${{ inputs.WORDPRESS_VERSION }}-php-${{ inputs.PHP_VERSION }}-${{ steps.daily-cache-burst.outputs.cache-burst }}
```

Then in the matrix:

```
- name: Daily Cache Burst.
  id: daily-cache-burst
  run: echo "::set-output name=cache-burst::$(date +'%j')"

- name: Restore WordPress Image Cache - Step 1
  uses: actions/cache@v3
  with:
    path: ci/cache/docker/wordpress
    key: cache-docker-wordpress-${{ matrix.test_run.environment.wordpress_version }}-php-${{ github.event.client_payload.setup_cache.php_version }}-${{ steps.daily-cache-burst.outputs.cache-burst }}
```

I still don't know what happened. I'm closing this issue since I couldn't isolate/reproduce the issue.
