### ISSUE TITLE
Too much configuration required

### ISSUE THREAD

**Issue by fregante** [actions/cache#94]
This is the [suggested configuration](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/caching-dependencies-to-speed-up-workflows#example-using-the-cache-action) to cache `npm`:

```yml
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-
```

This is the suggested configuration to cache `npm` on Travis:

```yml

```

Not a mistake. It's empty. It's [the default.](https://docs.travis-ci.com/user/caching/#npm-cache)

Can better defaults be provided? GitHub Actions workflows are 5x to 10x longer than Travis’ for the most common configurations.

**Comment by chrispat** [comment]
I am curious.  Other than pure aesthetics why is shorter better?  And how would you contrast this with all of the request to have a separate save and restore actions more like CircleCI?

**Comment by fregante** [comment]
You can make it both powerful and have sensible defaults. 

1. Could it detect and cache npm  if it was called without arguments?
2. Could it cache npm/yarn with `with: {npm: true}`
3. Could GitHub also wrap this action into another dependencies-specific action (which would include config for most languages)?

I’m sure many will pop up in userland soon enough if you don’t, but your docs will still suggest that wordy configuration if there isn’t an official one.

**Comment by hugovk** [comment]
+1

Compare the 1,000 characters needed for Python compared with 10 for Travis CI: https://github.com/actions/cache/issues/16#issuecomment-553435250.

**Comment by mrmckeb** [comment]
I think this also relates to #16. Less config is always desirable - and if it's better than CircleCI, Travis, GitLab - that's awesome.

**Comment by krcroft** [comment]
> @chrispat: I am curious. Other than pure aesthetics why is shorter better?

I mean this with the most respect, but statements of such nonsense would be career-ending among experienced and wise development teams.  The best code is none at all followed next by the least amount of readily maintainable code.

In this case, we're talking about unnecessary boiler-plate: is it possible to reduce it further? I'm not sure; maybe for the given functionality offered, the amount of required parameters needed in the boiler-plate is already at a minimum.

**Comment by MikailBag** [comment]
I think the only way to reduce boilerplate os to add some presets. E.g.
```yaml
uses: actions/cache@v1
with:
  profile: npm
```
It is impossible to derive key from path, because path is usually empty when action is called.
