### ISSUE TITLE
actions/cache : permissions error for /github/home/.cache/pip : parent directory is not owned or is not writable by the current user

### ISSUE THREAD

**Issue by sppears-genieai-tech** [actions/cache#947]
Hi,

I am trying to use cache pip dependencies using the [python pip example](https://github.com/actions/cache/blob/main/examples.md#python---pip). However I receive the following the permissions error:

```bash
WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
```

Can anyone help?
On further investigation it seems to work if I do not run the job in a container. If I run the job in a container I get the error message given above. Is there a way to change the working directory of a container and configure the pip cache or a virtual environment there?

```yaml
name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - pyproject.toml
      - poetry.lock
      - "src/**"
      - "tests/**"
      - ".github/workflows/pytest.yml"
  push:
    branches:
      - master
      - feat/*
    paths:
      - pyproject.toml
      - poetry.lock
      - "src/**"
      - "tests/**"
      - Dockerfile
      - ".github/workflows/pytest.yml"

jobs:
  test_job:
    runs-on: ubuntu-latest
    container: python:3.10

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Virtual environment
        id: cache
        run: |
          python -m venv ./.venv && . ./.venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          if: steps.cache-venv.outputs.cache-hit != 'true'
```
