### ISSUE TITLE
Post save cache step takes too long

### ISSUE THREAD

**Issue by vtereshyn** [actions/cache#951]
I have used `actions/cache` for a long time to cache dependencies and Typescript build results. I am moving my monorepo from `yarn` to `pnpm`, so I can save some time on installing dependencies, and I faced an issue probably related to how `actions/cache works.

After moving to `pnpm`, I see that post save cache step takes too long, while before moving to `pnpm`, it took only 5s (see the third screenshot). 

PNPM uses symlinked `node_modules` structure, but this shouldn't be related to `dist` folders produced by the Typescript compiler.

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/32247411/194503168-b5813b4c-713a-4b80-b715-7ce83a71eb49.png">
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/32247411/194503326-f1ced95b-8c1d-462a-9d38-9184031ef6c6.png">
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/32247411/194503593-42d88658-080e-44f5-bb5a-b0f3e82b4b81.png">

Here is the workflow from the first 2 screenshots:

```
  build:
    runs-on: self-hosted
    needs: dependencies

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
          run_install: false

      - uses: actions/setup-node@v3
        name: Install Node
        with:
          node-version-file: '.nvmrc'

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ env.CACHE_VERSION }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-${{ env.CACHE_VERSION }}-

      - name: Install dependencies
        run: pnpm install
        env:
          NODE_OPTIONS: ${{ env.NODE_OPTIONS }}

      - name: Build
        run: pnpm build:ts
        env:
          NODE_OPTIONS: ${{ env.NODE_OPTIONS }}

      - uses: actions/cache@v3
        id: build-cache
        name: Save build cache
        with:
          path: |
            packages/**/dist
            packages/**/tsconfig.tsbuildinfo
          key: ${{ github.sha }}
```

Let me know if you need more information from my side and if everything above makes sense for you. Thanks
