### ISSUE TITLE
Caching go modules not working?

### ISSUE THREAD

**Issue by miparnisari** [actions/cache#967]
I'm following this example: 

https://github.com/actions/cache/blob/4fe9c4bd54cc7f1a32249072c2256c718ea68a5b/examples.md?plain=1#L183-L194

My workflow in the PR i'm testing:

```yaml
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: './go.mod'

      - id: go-cache-paths
        run: |
          echo "go-build=$(go env GOCACHE)" >> $GITHUB_OUTPUT
          echo "go-mod=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        with:
          path: |
            ${{ steps.go-cache-paths.outputs.go-mod }}
            ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go

      - name: Test Functional
        run: make test-customers-functional-ci
```

The result:

<img width="1525" alt="image" src="https://user-images.githubusercontent.com/5374887/197615993-e192c870-3933-4319-a125-950d0258be98.png">

Shouldn't the part that I highlighted in red not be there?
