### ISSUE TITLE
duplicate cache with same key?

### ISSUE THREAD

**Issue by nalchevanidze** [actions/cache#968]
I don't know if it's a right place, problem can be caused by GitHub cache API. my Github workflow sometimes in Haskell doesn't use cache key. not even more general restore keys. 

as you can see there are multiple builds with same kay.

<img width="1224" alt="image" src="https://user-images.githubusercontent.com/18636038/197639308-df97a6c6-b6e7-4960-9e00-cfa8ee8e9619.png">

where pipeline each time could not find the cache and saves it again. 

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/18636038/197639668-1762ed66-04b6-4257-b453-e04dc4fe6433.png">

in my case i already have 5 duplicate caches with same key, which evoke my curiosity.
how it is possible? and what can be a reason?

**Comment by nalchevanidze** [comment]
my action description is following:

```yaml
    - name: Cache Stack
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os  }}-${{ inputs.ghc }}-stack-${{ hashFiles('stack.yaml') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.ghc }}-stack
```

**Comment by anuragc617** [comment]
Hi @nalchevanidze, this is because cache with same key can be restored from the parent branch or main branch and not across the branch. But if the cache with key is not present in parent/main branch, then individual branches which will create their own caches. For more details check this [doc](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#matching-a-cache-key)

**Comment by nalchevanidze** [comment]
thanks @anuragc617.  Is there anything I can do to change this behavior? since I don't really care about the branches and I would like to have one cache per key regardless of the branches?

**Comment by anuragc617** [comment]
If you want one cache per key, then you need to ensure that cache is created against main branch and the other branches can restore the cache.  
But if a branch changes the cache key then it will create a cache with new key and this can only be restored by that branch and children of that branch.

**Comment by anuragc617** [comment]
@sidekick-eimantas  the cross-branch caches protection is necessary because the cache created for a branch may have vulnerabilities and if that cache is used for building the main branch/ parent branch, then the build artifacts generated for main branch will also have those vulnerabilities. It poses a security threat for your production environment.

**Comment by Avasam** [comment]
But what if it comes from the same PR/Branch? Here I have 2 duplicates:
![image](https://user-images.githubusercontent.com/1350584/203858609-2e74add3-b476-4e52-9015-1413471b6820.png)

https://github.com/Avasam/Auto-Split/actions/caches

<details>
<summary>Details</summary>

```yml
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: Lint and build
on:
  workflow_dispatch: #  Allows manual builds
    inputs:
      excludeBuildNumber:
        description: "Exclude build number"
        required: true
        default: false
        type: boolean
  push:
    branches:
      - main
      - master
    paths:
      - "**.py"
      - "**.ui"
      - ".github/workflows/lint-and-build.yml"
      - "**/requirements.txt"
  pull_request:
    branches:
      - main
      - master
      - dev*
      - 2.0.0
    paths:
      - "**.py"
      - "**.pyi"
      - "**.ui"
      - ".github/workflows/lint-and-build.yml"
      - "**/requirements*.txt"

env:
  GITHUB_HEAD_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name }}
  GITHUB_EXCLUDE_BUILD_NUMBER: ${{ inputs.excludeBuildNumber }}

jobs:
  isort:
    runs-on: windows-latest
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "scripts/requirements*.txt"
      - uses: actions/cache@v3
        with:
          path: |
            "${{ env.pythonLocation }}/lib/site-packages"
            "${{ env.pythonLocation }}/scripts"
          key: ${{ runner.os }}-pip-${{ hashFiles('scripts/requirements*.txt') }}
      - run: scripts/install.ps1
        shell: pwsh
      - run: Get-Command pyuic6
        shell: pwsh
      - name: Analysing the code with add-trailing-comma
        run: isort src/ typings/ --check-only
  add-trailing-comma:
    runs-on: windows-latest
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install add-trailing-comma
      - name: Analysing the code with add-trailing-comma
        run: add-trailing-comma $(git ls-files '**.py*') --py36-plus
  Bandit:
    # Bandit only matters on the version deployed. Platform checks are ignored
    runs-on: windows-latest
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install bandit
      - name: Analysing the code with Bandit
        run: bandit src/ -n 1 --severity-level medium --recursive
  Pyright:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      # Pyright is version and platform sensible
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "scripts/requirements*.txt"
      - uses: actions/cache@v3
        with:
          path: |
            "${{ env.pythonLocation }}/lib/site-packages"
            "${{ env.pythonLocation }}/scripts"
          key: ${{ runner.os }}-pip-${{ hashFiles('scripts/requirements*.txt') }}
      - run: scripts/install.ps1
        shell: pwsh
      - name: Analysing the code with Pyright
        uses: jakebailey/pyright-action@v1
        with:
          working-directory: src/
          extra-args: --warnings
  Pylint:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      # Pylint is version and platform sensible
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "scripts/requirements*.txt"
      - uses: actions/cache@v3
        with:
          path: |
            "${{ env.pythonLocation }}/lib/site-packages"
            "${{ env.pythonLocation }}/scripts"
          key: ${{ runner.os }}-pip-${{ hashFiles('scripts/requirements*.txt') }}
      - run: scripts/install.ps1
        shell: pwsh
      - name: Analysing the code with Pylint
        run: pylint src/ --reports=y --output-format=colorized
  Flake8:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      # Flake8 is tied to the version of Python on which it runs. Platform checks are ignored
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "scripts/requirements*.txt"
      - uses: actions/cache@v3
        with:
          path: |
            "${{ env.pythonLocation }}/lib/site-packages"
            "${{ env.pythonLocation }}/scripts"
          key: ${{ runner.os }}-pip-${{ hashFiles('scripts/requirements*.txt') }}
      - run: scripts/install.ps1
        shell: pwsh
      - name: Analysing the code with Flake8
        run: flake8 src/ typings/
  Build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      # Only the Python version we plan on shipping matters.
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Checkout ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "scripts/requirements.txt"
      - uses: actions/cache@v3
        with:
          path: |
            "${{ env.pythonLocation }}/lib/site-packages"
            "${{ env.pythonLocation }}/scripts"
          key: ${{ runner.os }}-pip-${{ hashFiles('scripts/requirements.txt') }}
      - run: scripts/install.ps1
        shell: pwsh
      - run: scripts/build.ps1
        shell: pwsh
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: AutoSplit (Python ${{ matrix.python-version }})
          path: dist/AutoSplit*
          if-no-files-found: error
      - name: Upload Build logs
        uses: actions/upload-artifact@v3
        with:
          name: Build logs (Python ${{ matrix.python-version }})
          path: |
            build/AutoSplit/*.toc
            build/AutoSplit/*.txt
            build/AutoSplit/*.html
          if-no-files-found: error
```

</details>
