### ISSUE TITLE
Unnecessary cache writes in PR branch when cache-key is found on the default branch

### ISSUE THREAD

**Issue by pramodka-revefi** [actions/cache#975]
We're trying to make our PR builds fast by using the cache action. Our model right now:
* Create a daily cache on the main branch with a dated key
* Use the cache in every PR -> We use Bazel, which makes our builds & tests are incremental

However I noticed that each PR build workflow is spending time writing the cache. I would like some way to not copy/write back caches when the cache key is found. 

I've read the documentation on [cache isolation](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache) and [re-using caches across feature branches](https://github.com/actions/cache/blob/main/workarounds.md#use-cache-across-feature-branches) but this write back behavior is not discussed in either place. 

The creation of a copy of an existing cache from the default branch to the PR branch seems an unnecessary cost to us and I would like a way to turn it off.

Cache found with key, but still being recreated for the PR branch:
<img width="2977" alt="image" src="https://user-images.githubusercontent.com/103965979/200053297-d8c18687-d5ae-4f7b-bc7d-9b96abdc386b.png">

Duplicated caches across branches:
<img width="2994" alt="image" src="https://user-images.githubusercontent.com/103965979/200053187-528eaa6b-31a8-4582-9f33-564b5ff4915b.png">

**Comment by vsvipul** [comment]
@pramodka-revefi This should not happen unless you are using restore-keys. Can you recreate this in a public repo and share the runs with us ? 

I tried with this simple workflow-
```
name: Testing 

on: [push, workflow_dispatch]

jobs:
  CreateV2:
    runs-on: ubuntu-latest
    steps:
    - name: Create Cache Folder
      run: |
        mkdir cache-folder
        cd cache-folder
        truncate -s 14M samplefile
    - uses: actions/cache@v3
      with:
        path: "cache-folder"
        key: "test-cache-7/11/22"
```

and PRs are not creating separate cache if there is already a cache with the same key present on main branch.
