### ISSUE TITLE
Need new node npm example

### ISSUE THREAD

**Issue by linonetwo** [actions/cache#988]
Here are the version applied change from [https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-3](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-3) and [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) :

```
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "DIR=$(npm config get cache)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ steps.npm-cache.outputs.DIR }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
```

But it says 

```

Run actions/cache@v3
Error: Input required and not supplied: path
```

https://github.com/tiddly-gittly/TidGi-Desktop/actions/runs/3490700929/jobs/5842458974

I don't know how to solve this, because the example is staled https://github.com/actions/cache/blob/main/examples.md#node---npm

**Comment by aetos382** [comment]
In Windows Hosted Runner, the default shell is `pwsh`.
In pwsh, `${GITHUB_OUTPUT}` refers to a shell variable, but must refer to an environment variable, so you need to write `${env:GITHUB_OUTPUT}`.
If you are building on both Linux and Windows, you will need to specify the shell explicitly, as in one of the following examples.

```yaml
- name: Get npm cache directory
  id: npm-cache
  shell: bash
  run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
```

OR

```yaml
- name: Get npm cache directory
  id: npm-cache
  shell: pwsh
  run: echo "dir=$(npm config get cache)" >> ${env:GITHUB_OUTPUT}
```
